infrastructure/openhim-base-config.json
- Add polling channel for validation queue cleaner
=> [OCRVS-2621] Validation queue cleaner

README.md
we should look to tidy up the contents/headings so they are consistent
=> reordered a section, spelling mistake and removed extra line

packages/client/src/views/Performance/MonthlyReports.test.tsx, packages/client/src/views/Performance/MonthlyReports.tsx, packages/client/src/views/Performance/ReportList.test.tsx, packages/client/src/views/Performance/ReportList.tsx
=> Ocrvs 2700 fix location search performance

README.md
Please let me know if this was not the intended change 😊
=> Fix markdown for link

packages/client/src/i18n/messages/validations.ts, packages/client/src/utils/validate.test.ts, packages/client/src/utils/validate.ts
**Prior to this change:** BRN should be numeric and length should be within 17 and 18
**After this change:** BRN should be numeric and length must be 17
=> Ocrvs 2556 update BRN validation

packages/client/src/App.tsx, packages/client/src/i18n/messages/views/eventInfo.ts, packages/client/src/navigation/index.ts, packages/client/src/navigation/routes.ts, packages/client/src/views/EventInfo/EventInfo.test.tsx, packages/client/src/views/EventInfo/EventInfo.tsx, packages/client/src/views/SelectVitalEvent/SelectVitalEvent.test.tsx, packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx, packages/components/src/components/typography/BulletList.tsx
=> Ocrvs 2711 Create eventinfo component

infrastructure/nginx-default.conf
Reverts opencrvs/opencrvs-core#1526
=> Revert "Added security header on nginx config"

packages/client/src/i18n/messages/views/performance.ts, packages/client/src/views/Performance/OperationalReport.tsx, packages/client/src/views/Performance/reports/RegistrationRatesReport.test.tsx, packages/client/src/views/Performance/reports/RegistrationRatesReport.tsx, packages/client/src/views/Performance/utils.ts
**Desktop view**
**Tablet view**
=> [OCRVS-2744] Event registration rates report

infrastructure/nginx-default.conf
After merging this PR, we need to verify the whole application again. Each corner needs to tested properly.
=> Added proper content security prolicy on nginx config

packages/login/src/i18n/locales/en.ts
=> Ocrvs 2768 Copy change

packages/client/src/App.tsx, packages/client/src/i18n/messages/views/performance.ts, packages/client/src/navigation/index.ts, packages/client/src/navigation/routes.ts, packages/client/src/views/Performance/OperationalReport.test.tsx, packages/client/src/views/Performance/OperationalReport.tsx, packages/client/src/views/Performance/PerformanceContentWrapper.tsx, packages/client/src/views/Performance/PerformanceSelect.tsx, packages/client/src/views/Performance/RegistrationRates.test.tsx, packages/client/src/views/Performance/RegistrationRates.tsx, packages/client/src/views/Performance/queries.ts, packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.test.tsx, packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx, packages/client/src/views/Performance/utils.test.ts, packages/client/src/views/Performance/utils.ts, packages/gateway/src/features/location/root-resolvers.test.ts, packages/gateway/src/features/location/root-resolvers.ts, packages/gateway/src/features/location/schema.graphql, packages/gateway/src/graphql/schema.d.ts
=> Ocrvs 2751 RegistrationRates bootstrap

packages/client/src/i18n/messages/constants.ts, packages/client/src/views/Performance/RegistrationRates.test.tsx, packages/client/src/views/Performance/RegistrationRates.tsx, packages/client/src/views/Performance/queries.ts, packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.test.tsx, packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx, packages/components/src/components/interface/ListTable/ListTable.tsx, packages/gateway/src/features/fhir/utils.ts, packages/gateway/src/features/metrics/root-resolvers.test.ts, packages/gateway/src/features/metrics/root-resolvers.ts, packages/gateway/src/features/metrics/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/metrics/src/config/routes.ts, packages/metrics/src/features/eventEstimations/handler.test.ts, packages/metrics/src/features/metrics/metricsGenerator.ts, packages/metrics/src/features/metrics/utils.ts, packages/metrics/src/features/monthWiseEventEstimations/handler.test.ts, packages/metrics/src/features/monthWiseEventEstimations/handler.ts
@tahmidrahman-dsi I have integrated the table UI with the backend in this PR, please take a look on the changes
@Sadman-Ilham I think, this queries should be enough for your chart as well. so let's try to merge your branch with this one and see if we need to change anything else or not.
=> Registration rates backend queries for month wise estimation data and necessary UI changes for backend integration

packages/client/src/i18n/messages/views/performance.ts, packages/client/src/views/Performance/PerformanceSelect.test.tsx, packages/client/src/views/Performance/PerformanceSelect.tsx, packages/client/src/views/Performance/RegistrationRates.tsx, packages/client/src/views/Performance/queries.ts, packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.test.tsx, packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx, packages/gateway/src/features/fhir/utils.ts, packages/gateway/src/features/metrics/root-resolvers.test.ts, packages/gateway/src/features/metrics/root-resolvers.ts, packages/gateway/src/features/metrics/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/metrics/src/api.ts, packages/metrics/src/config/routes.ts, packages/metrics/src/features/locationWiseEventEstimations/handler.test.ts, packages/metrics/src/features/locationWiseEventEstimations/handler.ts, packages/metrics/test/setupJest.ts
For division level:
For district level:
For upazila level:
For union level:
=> [#1606 & #1672] Showing registration rates for different administrative areas 

packages/client/src/navigation/index.ts, packages/client/src/views/Performance/OperationalReport.test.tsx, packages/client/src/views/Performance/OperationalReport.tsx, packages/client/src/views/Performance/PerformanceHome.test.tsx, packages/client/src/views/Performance/PerformanceHome.tsx, packages/client/src/views/Performance/PerformanceSelect.tsx, packages/client/src/views/Performance/RegistrationRates.test.tsx, packages/client/src/views/Performance/RegistrationRates.tsx
Will need to wait until we resolve the Registrar user stories before fixing the header on the reports page in a future PR.
=> Sys Admin reports

packages/client/src/i18n/messages/constants.ts, packages/client/src/views/Performance/OperationalReport.tsx, packages/client/src/views/Performance/PerformanceContentWrapper.tsx, packages/client/src/views/Performance/PerformanceSelect.tsx, packages/client/src/views/Performance/RegistrationRates.tsx, packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx, packages/client/src/views/Performance/utils.ts, packages/client/src/views/Settings/SettingsPage.tsx, packages/client/src/views/SysAdmin/tabs/user/userTab.tsx, packages/components/src/components/fonts.ts, packages/components/src/components/grid.ts, packages/components/src/components/interface/GridTable/types.ts, packages/components/src/components/interface/ListTable/ListTable.tsx, packages/components/src/components/layout/Content.tsx, packages/metrics/src/features/legacy/handler.ts
Requires these copy amends:  https://github.com/opencrvs/opencrvs-bangladesh/pull/45
https://github.com/opencrvs/opencrvs-zambia/pull/30
=> maxWidth 1140px and RegistrationRates / Reports UI amends

packages/client/src/components/interface/ApplicationStatusWindow.tsx, packages/client/src/views/Performance/OperationalReport.test.tsx, packages/client/src/views/Performance/OperationalReport.tsx, packages/components/src/components/icons/Activity.tsx
=> [OCRVS-1667] Application status window

packages/client/src/components/DateRangePicker.tsx, packages/client/src/components/LocationPicker.tsx, packages/client/src/tests/util.tsx, packages/client/src/utils/locationUtils.ts, packages/client/src/views/Performance/FieldAgentList.test.tsx, packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/Performance/RegistrationRates.test.tsx, packages/client/src/views/Performance/RegistrationRates.tsx, packages/client/src/views/Performance/WorkflowStatus.test.tsx, packages/client/src/views/Performance/WorkflowStatus.tsx
Implemented in 
- Registration rates
- Field agent list 
- Application status progress list
=> Ocrvs 1694 Location picker

packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/Performance/WorkflowStatus.tsx, packages/client/src/views/Performance/reports/registrationRates/Within45DaysTable.tsx, packages/components/src/components/interface/ListTable/ListTable.tsx
Applied in `ListTable` implementations in 
- Field agent list
- Registration rates
- Application progress status
**Hover background covers full width**
=> Ocvrs 1692 ListTable mouse over effect

packages/client/src/views/Performance/OperationalReport.tsx, packages/client/src/views/Performance/utils.ts
=> Filtered report list based month picker value

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx
Closes #1733 
-  **When child birthdate is given input  first**
> ![father-birthdate-normal](https://user-images.githubusercontent.com/42269993/83877034-a6c4cf80-a75b-11ea-877b-44a5a5313235.gif)
- **When father birthdate is given input first** 
> ![father-birthdate](https://user-images.githubusercontent.com/42269993/83877180-e2f83000-a75b-11ea-9cf1-c1155f467db3.gif)
=> Ocrvs 1733 Father DoB validation fixes

packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx, packages/components/src/components/interface/ListTable/ListTable.tsx
=> Hotfix: Subpage content width and list table height

packages/client/src/DateUtils.test.ts, packages/client/src/DateUtils.ts, packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
=> [OCRVS-1706] Plain time duration tool-tip

packages/client/src/components/charts/RegRatesLineChart.tsx, packages/client/src/views/SysAdmin/Performance/RegistrationRates.test.tsx, packages/components/src/components/charts/TriLineChart.tsx
=> [OCRVS-1758] Registration line chart mobile view

packages/client/src/components/DateRangePicker.tsx, packages/client/src/components/LocationPicker.tsx
=> Ocrvs 1750 Responsive location picker

packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx, packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx
=> [OCRVS-1719] Status window responsiveness

packages/client/src/views/SysAdmin/Performance/utils.ts
**Field agent report**
**Application report**
=> [OCRVS-1758] Report filter mobile view

packages/client/src/components/DateRangePicker.test.tsx, packages/client/src/components/DateRangePicker.tsx, packages/client/src/components/LocationPicker.tsx, packages/client/src/i18n/messages/constants.ts, packages/client/src/views/SysAdmin/Performance/OperationalReport.test.tsx, packages/client/src/views/SysAdmin/Performance/RegistrationRates.test.tsx
=> Ocrvs 1640 Responsive time picker

infrastructure/server-setup/README.md, infrastructure/server-setup/playbook.yml, packages/client/src/components/interface/ApplicationStatusWindow.tsx, packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/RegistrationRates.tsx, packages/client/src/views/SysAdmin/Performance/Report.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Performance/reports/CertificationPaymentReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/Estimated45DayRegistrationReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/GenderBasisReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/TimeFrameReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/registrationRates/Within45DaysTable.tsx, packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx, packages/components/src/components/interface/ListTable/ListTable.tsx
Plus remove IP addresses from playbook.yml
=> ListTable fixed width and other Subpage / misc fixes

packages/client/src/forms/index.ts, packages/client/src/forms/utils.ts, packages/client/src/forms/validation.ts, packages/client/src/i18n/messages/buttons.ts, packages/client/src/i18n/messages/views/sysAdmin.ts, packages/client/src/user/user-audit.ts, packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.test.tsx, packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/client/src/views/SysAdmin/Team/utils.ts
=> Ocrvs 1771 User audit frontend (reactivation)

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
=> Fixed double line table row height

packages/components/src/components/interface/ListTable/ListTable.tsx
=> Fixed scroller width and visibility issue

packages/client/src/views/RegistrationHome/RowHistoryView.tsx, packages/client/src/views/RegistrationHome/tabs/approvals/approvalTab.test.tsx, packages/client/src/views/RegistrationHome/tabs/approvals/approvalTab.tsx, packages/client/src/views/RegistrationHome/tabs/review/reviewTab.test.tsx, packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx
=> Name in ready for review workqueue

packages/auth/src/constants.ts, packages/auth/src/features/authenticate/handler.ts, packages/auth/src/features/authenticate/service.ts, packages/auth/src/features/system/handler.test.ts, packages/auth/src/features/system/handler.ts, packages/auth/src/index.ts, packages/user-mgnt/src/config/routes.ts, packages/user-mgnt/src/features/system/handler.ts
Systems now have a new endpoint for authentication using client_id and client_secret returning a JWT with a different expiry length, default is 10 minutes.
=> System client authentication

packages/client/src/i18n/messages/views/performance.ts, packages/client/src/offline/actions.ts, packages/client/src/offline/reducer.ts, packages/client/src/setupTests.ts, packages/client/src/tests/util.tsx, packages/client/src/utils/locationUtils.ts, packages/client/src/utils/referenceApi.test.ts, packages/client/src/utils/referenceApi.ts, packages/client/src/views/RegisterForm/ReviewForm.test.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.test.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/SignatureForm.test.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.test.tsx
=> Load pilot areas based on country wise configuration 

packages/client/src/user/userReducer.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
=> #1876-Redirecting to appropriate team list

packages/client/src/views/SelectVitalEvent/SelectVitalEvent.test.tsx, packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
=> #1900-Error message for no option selection in event selection screen

packages/client/src/i18n/messages/views/performance.ts, packages/client/src/tests/languages.json, packages/client/src/views/SysAdmin/Performance/NoResultMessage.test.tsx, packages/client/src/views/SysAdmin/Performance/NoResultMessage.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
=> #1886-Activate pilot list on empty report screen

packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts, packages/client/src/forms/utils.ts, packages/client/src/views/SearchResult/SearchResult.test.tsx, packages/client/src/views/SearchResult/SearchResult.tsx
=> #1898-Adjusted phone number search to support with or without country code

packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx
=> #1885-Fix for date picker initial value issue on operational dashboard

packages/components/src/components/interface/ListTable/ListTable.tsx
=> #1895-Show 8px scrollbar when applicable for ListTable

packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/MonthlyReports.tsx, packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Performance/reports/CertificationPaymentReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/Estimated45DayRegistrationReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/GenderBasisReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/TimeFrameReports.tsx, packages/client/src/views/SysAdmin/Performance/reports/registrationRates/Within45DaysTable.tsx
Removed sort function from report list & alignment issue fixes
=> #1889 & 1892 - Fix for table list alignment issues, removed sort functionality from report list 

packages/client/src/i18n/messages/constants.ts, packages/client/src/views/SearchResult/SearchResult.tsx
=> #1906-Changed the column header to Started in search result

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Performance/queries.ts, packages/gateway/src/features/search/schema.graphql, packages/gateway/src/features/search/type-resolvers.test.ts, packages/gateway/src/features/search/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql
=> 1910 - Fixed application started time issue on workflow status list

packages/auth/src/features/authenticate/handler.test.ts, packages/auth/src/features/authenticate/handler.ts, packages/client/src/utils/apolloClient.ts, packages/gateway/src/graphql/config.test.ts, packages/gateway/src/graphql/config.ts, packages/login/src/i18n/locales/bn.ts, packages/login/src/i18n/locales/en.ts, packages/login/src/utils/authUtils.ts, packages/login/src/views/StepOne/StepOneForm.tsx, packages/user-mgnt/src/features/updateUser/handler.ts
=> 1951 - Logout user from current session in-case of deactivation or role change

packages/client/src/applications/index.ts, packages/client/src/search/transformer.ts, packages/client/src/views/PrintCertificate/Payment.tsx, packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx, packages/client/src/views/RegistrationHome/RowHistoryView.tsx, packages/client/src/views/RegistrationHome/tabs/approvals/approvalTab.tsx, packages/client/src/views/RegistrationHome/tabs/externalValidation/externalValidationTab.tsx, packages/client/src/views/RegistrationHome/tabs/print/printTab.tsx, packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx, packages/client/src/views/SearchResult/SearchResult.tsx
=> 1952 - Fix for started column values on search result screen

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/gateway/src/features/fhir/utils.ts, packages/gateway/src/features/search/type-resolvers.test.ts, packages/gateway/src/features/search/type-resolvers.ts, packages/metrics/src/api.ts, packages/metrics/src/config/routes.ts, packages/metrics/src/features/getEventDuration/handler.test.ts, packages/metrics/src/features/getEventDuration/handler.ts, packages/metrics/src/features/getTimeLogged/handler.ts, packages/metrics/src/features/legacy/handler.ts, packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap, packages/metrics/src/features/registration/handler.test.ts, packages/metrics/src/features/registration/handler.ts, packages/metrics/src/features/registration/pointGenerator.ts, packages/metrics/src/features/registration/test-data/mark-validated-request.json, packages/metrics/src/features/registration/test-data/mark-waiting-validation-request.json, packages/metrics/src/features/registration/test-data/new-in-progress-request copy.json
=> 1911 - Fixed timings for workflow status grid

packages/client/src/tests/register.json
BGD Form Definition update: https://github.com/opencrvs/opencrvs-bangladesh/pull/75
=> 2020 - Updated event form definitions for existing testcases

packages/client/src/applications/index.ts
=> 2018 - Updating fetched workqueue items with existing application data

packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx, packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx
=> Ocrvs 1787 Make header sticky

packages/client/src/applications/index.ts
=> Ocrvs 1928 Fix for processing application in offline mode

packages/search/src/features/registration/birth/service.ts
=> Ocrvs 1992 Fix reject comment issue

packages/client/src/applications/index.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx
=> Ocrvs 1955 Fix for radio button and view group mismatch issue

packages/client/src/views/RegistrationHome/tabs/inProgress/inProgressTab.tsx, packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx, packages/client/src/views/SearchResult/SearchResult.tsx, packages/components/src/components/buttons/ListItemAction.tsx, packages/components/src/components/interface/GridTable/GridTable.tsx
fixes #1956 
1. In progress tab
2. Review tab
3. Search result
4. Print tab column alignment
=> Ocrvs 1956 Work queue table column related fixes

packages/client/src/i18n/messages/constants.ts, packages/client/src/tests/languages.json, packages/client/src/views/FieldAgentHome/FieldAgentHome.tsx
=> Ocrvs 1943 Copy changes

packages/user-mgnt/src/features/system/handler.ts, packages/webhooks/src/constants.ts, packages/webhooks/src/features/event/handler.ts, packages/webhooks/src/features/event/service.test.ts, packages/webhooks/src/features/event/service.ts, packages/webhooks/src/features/manage/handler.test.ts, packages/webhooks/src/features/manage/handler.ts, packages/webhooks/src/features/manage/service.ts
MOSIP require a webhook bundle that contains the following information:
Birth Event
- Birth Certificate Number / Reference Number
- Name
- Date of Birth
- Gender
- Parent visual identity - an image document
- Contact Information (Phone)
This PR should hopefully bundle together what MOSIP require for integration
=> Formatted webhook bundle to MOSIP requirements

packages/client/src/components/ProtectedPage.tsx
This fixes #1958 and fixes #1960
=> Ocrvs 1958,1960 Fix for UI bugs 

packages/client/src/components/charts/RegRatesLineChart.tsx, packages/components/src/components/fonts.ts
=> Ocrvs 1849 Graph UI summary box fixes

packages/client/src/components/form/FormFieldGenerator.test.tsx, packages/client/src/components/form/FormFieldGenerator.tsx
=> Ocrvs 1957 Fix for form field validation issue

packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/components/src/components/interface/ListTable/ListTable.tsx
=> Ocrvs 1877 Fix for UI issue

packages/client/src/components/DateRangePicker.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceSelect.tsx
Style amends of filter buttons
=> Ocrvs 1792 Filter button ui fixes

packages/client/src/components/form/FormFieldGenerator.test.tsx, packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/index.ts, packages/client/src/i18n/messages/validations.ts, packages/client/src/utils/constants.ts, packages/client/src/utils/validate.test.ts, packages/client/src/utils/validate.ts
This change adds validator which checks whether a value is greater than the given value. In addition, it also adds restriction to number inputs which prevents taking input of some non-numeric characters (e,E,+,-)
Note: Validator is implemented in field in the resource repository
=> Ocrvs 1977 Fix for form validation issues

packages/components/src/components/interface/ListTable/ListTable.tsx
=> Ocrvs 2052 List table ui fixes

packages/client/src/utils/validate.test.ts, packages/client/src/utils/validate.ts
Bengali or English name validation supports brackets
=> Ocrvs 2051 Name validation updates

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/components/src/components/forms/InputField/InputField.tsx
=> Ocrvs 2050 Fix for input field header overlapping issue 

packages/client/src/navigation/index.ts, packages/client/src/views/PrintCertificate/ReviewCertificateAction.test.tsx, packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
=> Ocrvs 1959 Fix for review certificate back button issue

packages/client/src/components/form/FormFieldGenerator.test.tsx, packages/client/src/components/form/FormFieldGenerator.tsx
=> Ocrvs 2060 Fixes for UI issues

packages/client/src/views/SysAdmin/Performance/PerformanceSelect.tsx
Arrow color updates for both dark and light theme
=> Ocrvs 1786 Dropdown fixes

packages/client/src/applications/index.ts, packages/client/src/tests/util.tsx, packages/client/src/views/RegisterForm/ApplicationForm.test.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx
This change is not significantly visible in high-end devices, rather it is visible in low-end devices where writing a draft takes a longer time.
=> Ocrvs 2054 Section to section transition indicator

packages/client/src/utils/validate.ts, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx
=> Hot fix for name formatting

packages/client/src/i18n/messages/views/sysAdmin.ts, packages/client/src/user/mutations.ts, packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.test.tsx, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx, packages/gateway/src/features/user/root-resolvers.test.ts, packages/gateway/src/features/user/root-resolvers.ts, packages/gateway/src/features/user/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/user-mgnt/src/config/routes.ts, packages/user-mgnt/src/features/resendSMSInvite/handler.test.ts, packages/user-mgnt/src/features/resendSMSInvite/handler.ts
https://user-images.githubusercontent.com/42269993/102600801-8386ce00-4149-11eb-9740-50ec5644a05a.mp4
=> Ocrvs 1825 Resend sms invite flow

packages/client/src/components/ProtectedPage.tsx, packages/client/src/i18n/messages/buttons.ts, packages/client/src/i18n/messages/errors.ts, packages/client/src/user/queries.ts, packages/client/src/views/SecureAccount/SecureAccountView.tsx, packages/client/src/views/Unlock/ForgotPIN.test.tsx, packages/client/src/views/Unlock/ForgotPIN.tsx, packages/client/src/views/Unlock/Unlock.test.tsx, packages/client/src/views/Unlock/Unlock.tsx, packages/components/src/components/interface/PINKeypad.tsx, packages/gateway/src/features/user/root-resolvers.test.ts, packages/gateway/src/features/user/root-resolvers.ts, packages/gateway/src/features/user/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/user-mgnt/src/config/routes.ts, packages/user-mgnt/src/features/verifyPasswordById/handler.test.ts, packages/user-mgnt/src/features/verifyPasswordById/handler.ts
=> Ocrvs 1619 Forgotten pin flow

packages/client/src/components/Notification.test.tsx, packages/client/src/components/Notification.tsx, packages/client/src/components/ProtectedPage.tsx, packages/client/src/i18n/messages/errors.ts, packages/client/src/i18n/messages/views/notifications.ts, packages/client/src/notification/actions.ts, packages/client/src/notification/reducer.ts, packages/client/src/views/Unlock/ForgotPIN.test.tsx
- Show toast notification on successful PIN update
- Copy amends
=> Ocrvs 2073 UI and copy updates

packages/notification/src/features/sms/birth-handler.ts, packages/notification/src/features/sms/death-handler.ts
Change `birth-handler.ts` and `death-handler.ts` according to status wise SMS notification content
=> ocrvs-2107

packages/client/src/views/RegistrationHome/tabs/inProgress/localInProgressDataDetails.tsx
Informant info not found in the **In Progress** > **Yours tab** for the Registrar/Registration Agent fixed.
=> ocrvs-2152

packages/client/src/i18n/messages/views/review.ts, packages/client/src/tests/languages.json
Typing mistake in **Send for approval** confirmation message pop-up fixed
=> ocrvs-2159

packages/client/src/i18n/messages/validations.ts, packages/client/src/tests/languages.json, packages/client/src/utils/constants.ts, packages/client/src/utils/validate.ts
Range and Decimal Point validation has been added for **No. of Dependents** in death application.
=> [ocrvs-2142] range and decimal point validation for Dependents

packages/client/src/components/form/ReviewActionComponent.tsx, packages/client/src/i18n/messages/views/review.ts
Update **Send for Review/Send Incomplete** message logic while submitting application, make event name dynamic.
=> ocrvs-2178

packages/client/src/components/charts/RegRatesLineChart.tsx
lineBreak fixed inside statistical information text **Total registered**.
=> [ocrvs-2170] lineBreak inside text fixed

packages/client/src/i18n/messages/views/userSetup.ts, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
Renamed `Assigned office` to `Assigned registration office` and fixed padding for user profile.
=> [ocrvs-2169] Change user-profile office label

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Team/utils.ts
as we are handling with objets rather than arrays here, ```delete``` keyword is used instead of ```filter```
=> local language function added for perfomance column

packages/client/src/views/RegistrationHome/RowHistoryView.tsx
Wrong rejection reason showing to user if any application is rejected fixed.
=> [ocrvs-2177] Wrong rejection reason showing fixed

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/validation.ts, packages/client/src/i18n/messages/validations.ts, packages/client/src/utils/validate.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
=> ocrvs-2053 Added facilityMustBeSelected validation to place of birth - hospital field

packages/client/src/views/RegisterForm/RegisterForm.tsx
=> ocrvs-2213 - Fixed In-progress Application Removal On Exit Button Click

packages/client/src/views/SysAdmin/Performance/reports/operational/RegistrationRatesReport.tsx
=> ocrvs-1789: Fix font size and styling for registration rate widget

packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Performance/reports/registrationRates/Within45DaysTable.tsx, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx, packages/components/src/components/interface/GridTable/types.ts, packages/components/src/components/interface/ListTable/ListTable.tsx
All columns in field agent list and application workflow are made sortable, and the selected column by which rows are sorted are captioned bold on table header.
=> ocrvs-1794 Sorting implemented in field agent details view

packages/components/src/components/icons/BackArrowDeepBlue.tsx
=> back button colored to deepsea

packages/client/src/user/queries.ts, packages/gateway/src/features/user/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/user-mgnt/src/features/updateUser/handler.ts, packages/user-mgnt/src/model/user.ts
=> ocrvs-1937 device was saved as deviceId in gateway and in user mgnt, this is fixed

packages/components/src/components/select/Select.tsx, packages/components/src/components/select/index.ts, packages/login/src/App.tsx, packages/login/src/i18n/components/LanguageSelect.tsx, packages/login/src/i18n/locales/bn.ts, packages/login/src/i18n/locales/en.ts, packages/login/src/i18n/reducer.ts, packages/login/src/i18n/selectors.ts, packages/login/src/i18n/utils.ts, packages/login/src/views/StepOne/StepOneContainer.tsx, packages/login/src/views/StepOne/StepOneForm.tsx
- Language preference is saved in IndexedDB.
- Passing the selected language to client app is pending.
=> ocrvs-1814 Added language selection option in login

packages/client/src/components/interface/ApplicationStatusWindow.tsx
=> ocrvs-2337 Fixed the z-index for status window

packages/client/src/user/userReducer.ts
=> ocrvs-2318 showing all available type on update user

packages/client/src/components/form/FormFieldGenerator.tsx, packages/components/src/components/forms/InputField/InputField.tsx, packages/components/src/components/forms/Select.tsx, packages/components/src/components/forms/TextArea.tsx, packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
width on **Weight at birth** was fixed on ***2129*** ticket
width on **date of birth** was fixed on ***2130*** ticket
=> ocrvs-2128: input field max width set to 344px

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/index.ts, packages/client/src/review/reject-registration.ts, packages/client/src/views/RegistrationHome/RowHistoryView.tsx, packages/components/src/components/forms/TextArea.tsx
=> ocrvs 1944 Fixed rejected application long comment truncated issue and set maxLength to 500

packages/client/src/views/Unlock/Unlock.tsx
https://user-images.githubusercontent.com/42269993/147244370-03e21e55-0e3a-446d-8831-69081bbf52d0.mp4
https://user-images.githubusercontent.com/42269993/147244392-3e537b57-799b-4492-ad79-6f32c9fb1520.mp4
=> Ocrvs 1939 Fix lock screen name issue

packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx
=> ocrvs-1981: fix duplicate icon

packages/client/src/components/form/ReviewActionComponent.tsx, packages/components/src/components/interface/ResponsiveModal.tsx
=> ocrvs-1989:scrolbar height for sent incomplete modal

infrastructure/nginx-default.conf
*.sentry.io/ whitelisted on nginx-default-conf
=> ocrvs-2195: *.sentry.io/ whitelisted on nginx-default-conf

packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserAuditList.tsx, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
=> ocrvs-1969: ui bug fix on userProfile

packages/client/src/i18n/messages/user.ts
=> ocrvs-2336 Added message descriptor for DNRPC type

packages/client/src/i18n/messages/views/search.ts, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Team/TeamSearch.tsx, packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
=> Ocrvs 1871: Validation implemented on Performance and team tab search

packages/client/src/tests/register.json, packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx, packages/client/src/views/SysAdmin/Team/utils.ts
=> ocrvs-2371: dispatchOptions removed from registrationOffice fieldDefinition

packages/client/src/i18n/messages/validations.ts, packages/client/src/tests/register.json, packages/client/src/utils/validate.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx, packages/client/src/views/SysAdmin/Team/utils.ts
=> Ocrvs 1905: Validation showing when remove the location from user edit page

packages/client/src/applications/index.ts
=> ocrvs-1872: rejected birth/death application is not visible in sent for review tab

packages/client/src/i18n/messages/validations.ts, packages/client/src/tests/register.json, packages/client/src/utils/validate.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx, packages/client/src/views/SysAdmin/Team/utils.ts
Reverts opencrvs/opencrvs-core#2387
=> Revert "Ocrvs 1905: Validation showing when remove the location from user edit page"

packages/client/src/views/RegisterForm/RegisterForm.tsx
=> ocrvs-2292 Fixed previously visited sections/groups not updating

packages/client/src/views/CorrectionForm/CorrectorForm.tsx
=> ocrvs 2399 Correction Form

packages/client/src/App.tsx, packages/client/src/applications/index.ts, packages/client/src/forms/index.ts, packages/client/src/forms/register/review-selectors.ts, packages/client/src/forms/utils.ts, packages/client/src/i18n/messages/buttons.ts, packages/client/src/i18n/messages/views/review.ts, packages/client/src/navigation/index.ts, packages/client/src/navigation/routes.ts, packages/client/src/views/CorrectionForm/CorrectionForm.tsx, packages/client/src/views/CorrectionForm/ReviewForm.tsx, packages/client/src/views/CorrectionForm/index.ts, packages/client/src/views/RegisterForm/ApplicationForm.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/components/src/components/interface/ViewData/DataSection.tsx
=> ocrvs 2401 Correction review form

packages/client/src/views/SysAdmin/Team/user/UserList.tsx
=> ocrvs-2577: three dots menu made available only for national sysadmin, and sysadmin just for his office

packages/client/src/views/SearchResult/SearchResult.tsx
=> ocrvs-2376-hotfix: left navigation added on searchResult

packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx
=> ocrvs-1968-userProfile: menu button added on userProfile page in mobile view

packages/client/src/components/interface/Header/Header.tsx, packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx
=> (ocrvs-2382-fix) Disable back arrow button on landing page

.github/workflows/cd-manual-e2e.yml
Also adds the option to input specific docker images both for country config and core
=> CI: Check before building images in manual E2E action

packages/client/src/views/RegisterForm/RegisterForm.tsx
=> Ocrvs-2651: Fixed mother and father details bug when sending incomplete application

packages/client/src/i18n/messages/user.ts, packages/client/src/views/Settings/Settings.test.tsx, packages/client/src/views/Settings/SettingsPage.tsx, packages/components/src/components/buttons/LinkButton.tsx, packages/components/src/components/interface/Content.tsx
=> OCRVS-2381: List view simplified on settings page

packages/client/src/i18n/messages/views/performance.ts, packages/client/src/views/SysAdmin/Performance/CorrectionsReport.tsx, packages/client/src/views/SysAdmin/Performance/OperationalReport.tsx, packages/client/src/views/SysAdmin/Performance/utils.tsx, packages/gateway/src/features/metrics/root-resolvers.ts, packages/gateway/src/features/metrics/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/metrics/src/config/routes.ts, packages/metrics/src/features/corrections/handler.ts, packages/metrics/src/features/corrections/service.ts, packages/metrics/src/features/registration/handler.ts, packages/metrics/src/features/registration/index.ts, packages/metrics/src/features/registration/pointGenerator.ts, packages/metrics/src/influxdb/client.ts
=> [OCRVS-2827] Correction counts in improved performance view

packages/client/src/i18n/messages/views/performance.ts, packages/client/src/views/SysAdmin/Performance/CorrectionsReport.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceStats.tsx, packages/client/src/views/SysAdmin/Performance/metricsQuery.ts, packages/client/src/views/SysAdmin/Performance/queries.ts, packages/gateway/src/features/registration/root-resolvers.ts, packages/gateway/src/features/registration/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/config/routes.ts, packages/search/src/features/search/handler.ts, packages/search/src/features/search/utils.ts
=> Location stats frontend

packages/client/src/i18n/messages/views/formConfig.ts, packages/client/src/views/SysAdmin/Config/Forms/Home/DraftsTab.tsx, packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigMobileViewModal.tsx
=> OCRVS-2958 Added modal for form config mobile view

packages/client/src/components/interface/Navigation.test.tsx, packages/client/src/components/interface/Navigation.tsx, packages/client/src/i18n/messages/views/navigation.ts, packages/client/src/utils/authUtils.ts, packages/client/src/views/OfficeHome/LoadingIndicator.test.tsx, packages/client/src/views/OfficeHome/OfficeHome.test.tsx, packages/client/src/views/OfficeHome/OfficeHome.tsx, packages/client/src/views/OfficeHome/Outbox.tsx, packages/client/src/views/OfficeHome/tabs/WQContentWrapper.tsx, packages/client/src/views/OfficeHome/tabs/inExternalValidation/InExternalValidationTab.tsx, packages/client/src/views/OfficeHome/tabs/inExternalValidation/inExternalValidationTab.test.tsx, packages/client/src/views/OfficeHome/tabs/inProgress/InProgress.tsx, packages/client/src/views/OfficeHome/tabs/inProgress/inProgress.test.tsx, packages/client/src/views/OfficeHome/tabs/readyForReview/ReadyForReview.tsx, packages/client/src/views/OfficeHome/tabs/readyForReview/readyForReview.test.tsx, packages/client/src/views/OfficeHome/tabs/readyToPrint/ReadyToPrint.tsx, packages/client/src/views/OfficeHome/tabs/readyToPrint/readyToPrint.test.tsx, packages/client/src/views/OfficeHome/tabs/requiresUpdate/RequiresUpdateFieldAgent.tsx, packages/client/src/views/OfficeHome/tabs/requiresUpdate/RequiresUpdateRegistrar.tsx, packages/client/src/views/OfficeHome/tabs/requiresUpdate/requiresUpdateRegistrar.test.tsx, packages/client/src/views/OfficeHome/tabs/sentForApproval/SentForApproval.test.tsx, packages/client/src/views/OfficeHome/tabs/sentForApproval/SentForApproval.tsx, packages/client/src/views/OfficeHome/tabs/sentForReview/SentForReview.tsx, packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/ReviewForm.test.tsx, packages/client/src/views/SearchResult/SearchResult.tsx, packages/components/src/components/interface/GridTable/GridTable.tsx, packages/components/src/components/interface/GridTable/GridTableRowDeskop.tsx
=> Ocrvs 2775

packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/forms/utils.ts, packages/login/src/utils/dataCleanse.ts
Reverts opencrvs/opencrvs-core#3003
=> Revert "Revert FIN to ZMB"

packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/forms/utils.ts, packages/login/src/utils/dataCleanse.ts
Reverts opencrvs/opencrvs-core#3004
=> Revert "Revert "Revert FIN to ZMB""

packages/client/src/components/formConfig/CustomFieldForm.tsx, packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx, packages/client/src/components/formConfig/formTools/FormTools.tsx, packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigSettings.tsx, packages/components/src/components/buttons/Toggle.stories.tsx, packages/components/src/components/buttons/Toggle.tsx
=> FormConfig: Toggle button fix

packages/components/src/components/typography/BulletList.tsx
=> fix styling on bullet list

packages/client/src/views/OfficeHome/components.tsx, packages/client/src/views/OfficeHome/inExternalValidation/InExternalValidationTab.tsx, packages/client/src/views/OfficeHome/inExternalValidation/inExternalValidationTab.test.tsx, packages/client/src/views/OfficeHome/inProgress/InProgress.tsx, packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx, packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx, packages/client/src/views/OfficeHome/readyForReview/readyForReview.test.tsx, packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx, packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx, packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdateFieldAgent.tsx, packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdateRegistrar.tsx, packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdateRegistrar.test.tsx, packages/client/src/views/OfficeHome/sentForApproval/SentForApproval.test.tsx, packages/client/src/views/OfficeHome/sentForApproval/SentForApproval.tsx, packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx, packages/client/src/views/SearchResult/SearchResult.tsx
=> Ocrvs 3029: Only name is made clickable on WQ.

packages/client/src/forms/configuration/default.ts
=> informant dob in default.ts validation changed to allow informant younger than the child.

packages/client/src/declarations/index.ts, packages/components/src/components/interface/ExpandableNotification/ExpandableNotification.tsx
Related to: https://github.com/opencrvs/opencrvs-farajaland/pull/258
=> E2E: Add new test handles and fix e2e timing issues

packages/client/src/components/interface/Header/Header.tsx, packages/client/src/views/CorrectionForm/CorrectionReasonForm.tsx, packages/client/src/views/CorrectionForm/CorrectionSummary.tsx, packages/client/src/views/CorrectionForm/CorrectorForm.tsx, packages/client/src/views/CorrectionForm/IDVerifier.tsx, packages/client/src/views/CorrectionForm/SupportingDocumentsForm.tsx, packages/client/src/views/Home/RecordAudit.tsx, packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/Settings/SettingsPage.tsx, packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/Performance/utils.tsx, packages/components/src/components/interface/Content.stories.tsx, packages/components/src/components/interface/Content.tsx, packages/components/src/components/interface/Header/AppHeader.tsx, packages/components/src/components/interface/Header/Desktop/DesktopHeader.tsx, packages/components/src/components/interface/Header/Mobile/MobileHeader.tsx, packages/components/src/components/interface/Header/PageHeader.tsx
1. Title prop for mobile view
2. Back button for mobile view
=> Refactored Content component

packages/client/src/components/interface/Header/Header.tsx, packages/client/src/i18n/messages/constants.ts
Has Dependency branch - https://github.com/opencrvs/opencrvs-farajaland/pull/261
=> ocrvs-2553-fix Fixed config mobile view header

packages/client/src/tests/mock-offline-data.ts, packages/client/src/utils/locationUtils.ts, packages/client/src/views/Home/RecordAudit.tsx, packages/client/src/views/Home/utils.ts
=> ocrvs-3016: location format changed in record audit page

docker-compose.yml, packages/config/src/config/constants.ts, packages/config/src/config/database.ts, packages/config/src/handlers/formDraft/createFormDraft/handler.test.ts, packages/config/src/handlers/formDraft/updateFormDraft/handler.test.ts, packages/config/src/server.ts, packages/config/src/services/fhirService.test.ts, packages/config/src/services/fhirService.ts, packages/config/src/services/formDraftService.ts
=> Ocrvs 3094

docker-compose.deps.yml
Updates made in this PR: https://github.com/jembi/hearth/pull/203 now merged into [our forked version](https://github.com/opencrvs/hearth) of Hearth. 
I've run E2E tests locally and everything seems to be working still.
=> Use the latest version of Hearth

packages/client/generate-form.sh, packages/client/src/forms/configuration/default.ts, packages/client/src/generate-form.ts, packages/client/src/tests/default.json
=> Ocrvs 3061

packages/client/src/forms/configuration/default.ts, packages/client/src/tests/default.json
=> Ocrvs 3062 Fixed incomplete declaration attachment update issue 

packages/client/src/views/RecordAudit/History.tsx, packages/client/src/views/RecordAudit/RecordAudit.test.tsx, packages/client/src/views/RecordAudit/utils.ts
=> ocrvs-2833 Started row for DRAFT declarations

packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
=> Hotfix 2426

packages/client/src/components/DateRangePicker.tsx, packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/components/src/components/buttons/SecondaryButton.tsx, packages/components/src/components/forms/Select.tsx, packages/components/src/components/select/Select.tsx
- fixes filters button styling bug in Performance
- fixes menu styling
=> bug fixes styling for selects

docker-compose.deploy.yml, packages/auth/src/constants.ts, packages/auth/src/server.ts, packages/client/extract-translations.sh, packages/client/src/extract-translations.ts, packages/config/src/config/constants.ts, packages/config/src/logger.ts, packages/config/src/server.ts, packages/gateway/src/constants.ts, packages/gateway/src/server.ts, packages/login/extract-translations.sh, packages/login/src/extract-translations.ts, packages/notification/extract-translations.sh, packages/notification/src/extract-translations.ts
Depends on: https://github.com/opencrvs/opencrvs-farajaland/pull/269
=> Setup CORS and refactored farajaland to remove the farajaland directory

packages/gateway/src/features/registration/type-resolvers.ts
Should resolve this bug: https://github.com/opencrvs/opencrvs-core/issues/3197
=> Fix for undefined valueQuantity for weightAtBirth

packages/auth/src/server.ts, packages/client/src/forms/configuration/administrative/addresses.ts, packages/gateway/src/server.ts
Will fix this issue: https://github.com/opencrvs/opencrvs-core/issues/3031
=> Show fathers address option if mothers details not available

packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.tsx
=> ocrvs-3174 Showed default configuration in preview tab

packages/client/src/components/formConfig/Canvas.tsx, packages/client/src/forms/configuration/default.ts, packages/client/src/forms/configuration/formConfig/utils.ts, packages/client/src/tests/default.json, packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
=> ocrvs-3155,59,61,62 FormConfig content keys & canvas scroll

packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
Signature image should have `data-content="signature"` attribute
=> Certificate fixes

packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/forms/utils.ts, packages/login/src/utils/dataCleanse.ts
Reverts opencrvs/opencrvs-core#3005
=> Finland numbers for Pen Test

packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/forms/utils.ts, packages/login/src/utils/dataCleanse.ts
Reverts opencrvs/opencrvs-core#3232
=> Revert "Finland numbers for Pen Test"

packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx, packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx, packages/client/src/components/formConfig/formTools/components.tsx, packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx
=> ocrvs-3165 Fixed alignment in CustomFieldTools

packages/gateway/src/features/user/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql
Signature is only needed in LocalRegistrar and not in User
=> Removed signature from User schema

packages/client/src/views/PIN/CreatePin.tsx, packages/client/src/views/SecureAccount/SecureAccountView.tsx, packages/client/src/views/Unlock/Unlock.tsx, packages/components/src/components/colors.ts, packages/login/src/common/DarkPage/DarkPage.tsx
=> OCRVS-2924 Removed login background image and changed background color

packages/gateway/src/features/correction/root-resolvers.ts, packages/gateway/src/features/fhir/constants.ts, packages/gateway/src/features/fhir/utils.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts, packages/workflow/src/features/registration/fhir/fhir-utils.ts, packages/workflow/src/features/registration/handler.ts, packages/workflow/src/features/task/fhir/constants.ts, packages/workflow/src/features/task/handler.ts
=> ocrvs-2834 Show request correction on record audit

packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx, packages/client/src/views/SysAdmin/Team/utils.ts
User type is not assignable to any user except Field Agent.
https://github.com/opencrvs/opencrvs-core/issues/2849
=> Hotfix: User Profile user's type check was missing

packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx, packages/gateway/src/features/registration/schema.graphql, packages/gateway/src/features/registration/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql
=> Ocrvs 3173 Fix for reason not showing

packages/client/src/forms/configuration/default.ts, packages/client/src/tests/default.json, packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
DEPENDENT PR : https://github.com/opencrvs/opencrvs-farajaland/pull/275
=> ocrvs-2944 Modified preview certificate dummy data to show child names and location

packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
=> ocrvs-3169 Showed correct record button for registrar only

packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Team/TeamSearch.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx
=> ocrvs-3130 Team and Performance page offline state fix

packages/user-mgnt/src/utils/userUtils.ts
=> ocrvs-3281  Added roleScopeMapping on user-mgnt

packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
=> ocrvs-3252 Checked correct section for finding edited row

packages/client/src/navigation/index.ts, packages/client/src/tests/default.json, packages/client/src/views/OfficeHome/OfficeHome.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Performance/metricsQuery.ts, packages/metrics/src/api.ts, packages/metrics/src/features/certifications/service.ts, packages/metrics/src/features/corrections/service.ts, packages/metrics/src/features/locationStatistics/service.ts, packages/metrics/src/features/metrics/metricsGenerator.ts
=> Performance fixes

packages/client/src/views/OfficeHome/inProgress/InProgress.tsx, packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx, packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx, packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx, packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx, packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx, packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx, packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx, packages/client/src/views/OfficeHome/utils.ts
=> Ocrvs 3212: sorting in wq is being done by last column

packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx, packages/client/src/forms/configuration/customUtils.ts, packages/client/src/forms/configuration/formConfig/utils.ts, packages/client/src/user/userReducer.ts, packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.test.tsx, packages/config/src/handlers/formDraft/createFormDraft/handler.ts
=> ocrvs-3278 Custom phone number fixes

packages/client/src/forms/register/fieldMappings/birth/mutation/registration-mappings.ts, packages/client/src/tests/default.json
=> ocrvs-3290 Fix submission issues with custom number fields

packages/client/src/views/Settings/PasswordChangeModal.tsx, packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx
=> ocrvs-3114 Show full-screen modal on change password and deactivate user page

packages/components/src/components/interface/Tabs.tsx
=> scrollbar added on Tabs

packages/client/src/i18n/messages/location.ts, packages/client/src/i18n/messages/user.ts, packages/client/src/tests/languages.json
=> Intl messages hotfix

packages/client/src/views/OfficeHome/inProgress/InProgress.tsx
=> ocrvs-3196: pagination for in progress/field-agents made independent from my-drafts

packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
=> ocrvs-3081: event column copy bug fixed on ready for review

packages/metrics/src/features/certifications/service.ts
=> Performance fixes continued

packages/client/src/views/OfficeHome/LoadingIndicator.tsx, packages/client/src/views/SearchResult/SearchResult.tsx
=> ocrvs-3000: loading in search made same as workqueue

packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx, packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts
https://user-images.githubusercontent.com/42269993/171850499-ff2658d5-58d2-46d8-afdf-ed65ea40afa1.mp4
=> Ocrvs 3024 Preview certificate print

packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx, packages/components/src/components/interface/ListViewSimplified/ListViewSimplified.tsx
=> ocrvs-3098: document uploader alignment fixed in user review form

packages/components/src/components/interface/PaginationModified.tsx
=> ocrvs-3057: circle button modified in pagination

packages/client/src/views/RecordAudit/utils.ts
FARAJALAND PR: https://github.com/opencrvs/opencrvs-farajaland/pull/290
=> ocrvs-3375 Changed verbiage for Corrected record history

packages/gateway/src/features/registration/fhir-builders.ts
=> ocrvs-3308 Used proper ENCOUNTER_CODE depending on the event

packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx, packages/client/src/views/RecordAudit/History.tsx, packages/client/src/views/SearchResult/SearchResult.tsx
wq column changed from Sent for approval to Sent for review
location in history disabled for FA
download is being enabled from search
=> ocrvs-3120: FA bug fixed

packages/client/src/forms/configuration/default.ts, packages/client/src/i18n/messages/form.ts, packages/login/src/i18n/messages/views/stepOneForm.ts, packages/login/src/i18n/messages/views/stepTwoForm.ts, packages/login/src/views/StepTwo/StepTwoForm.tsx
Depends on this Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/292
=> Copy changes to names and login 

packages/client/src/forms/user/fieldDefinitions/createUser.ts, packages/client/src/tests/default.json
https://user-images.githubusercontent.com/42269993/172540445-762d07db-df4d-44c5-b3ae-3e94ce49c07d.mp4
=> Ocrvs 3340  Show signature selection form group for National Registrar 

packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
=> ocrvs-3282 Updated state when selected field changes

packages/client/src/components/formConfig/formTools/DefaultFieldTools.tsx, packages/client/src/components/formConfig/formTools/components.tsx, packages/client/src/i18n/messages/views/formConfig.ts
Associated PR on farajaland: https://github.com/opencrvs/opencrvs-farajaland/pull/294
=> ocrvs-3156: tooltip message added for form config

packages/client/src/views/SysAdmin/Config/Application/DynamicModal.tsx
=> ocrvs-3269 Fixed application config fee input alignment issue

packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
=> ocrvs-3418 Added cross button on user audit page

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/mappings/deserializer.ts, packages/client/src/i18n/messages/validations.ts, packages/client/src/i18n/messages/views/eventInfo.ts, packages/client/src/utils/timeoutLink.ts, packages/client/src/utils/validate.ts
=> Increased upload timeout and changed validation message on collector

packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/PrintCertificate/Payment.tsx, packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx, packages/client/src/views/PrintCertificate/VerifyCollector.tsx, packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
=> Ocrvs 3275 Fixed system crash after user creation and FA name sorting issue

packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx
=> ocrvs-2156: tooltip added on custom field tools

packages/client/src/views/Performance/FieldAgentList.tsx
=> ocrvs-3274 Fixed deactivated FA list filter issue on performance

packages/client/src/views/RegisterForm/DeclarationForm.tsx
=> ocrvs-3452 Fixed system crash when clicked back button after closing an incomplete declaration

packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/components/src/components/interface/TableView.tsx
Updating padding of TableView heading and content wrapper causes this result on Status table
Other results
=> Ocrvs 3423

packages/components/src/components/interface/RadioButton.stories.tsx, packages/components/src/components/interface/RadioButton.tsx
=> ocrvs-3053: radio button aligned to top

packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
=> ocrvs-3418-fix Fixed back button issue on team page

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.test.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
*** This screenshot is being taken by setting pageSize 2, just to show that pagination works ***
=> ocrvs-3462: pagination added on workflowStatus on performance

packages/client/src/components/LocationPicker.tsx, packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/i18n/messages/views/sysAdmin.ts, packages/client/src/views/RecordAudit/DeclarationInfo.tsx, packages/client/src/views/SysAdmin/Team/TeamSearch.tsx, packages/client/src/views/SysAdmin/Team/user/UserAuditActionModal.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/components/src/components/interface/LocationSearch/LocationSearch.stories.tsx, packages/components/src/components/interface/LocationSearch/LocationSearch.tsx
FARAJALAND PR: https://github.com/opencrvs/opencrvs-farajaland/pull/305
=> ocrvs-2977-fix Some languages related change

packages/client/src/forms/configuration/administrative/addresses.ts
=> ocrvs-3420 Changed secondary address preview group label

packages/client/public/index.html, packages/client/src/components/Page.tsx, packages/login/public/index.html, packages/login/src/login/selectors.ts, packages/login/src/views/StepOne/StepOneForm.tsx, packages/login/src/views/StepTwo/StepTwoContainer.tsx, packages/login/src/views/StepTwo/StepTwoForm.tsx
=> ocrvs-3478 Tab name changed according to application name

packages/client/src/i18n/messages/views/formConfig.ts
FARAJALAND PR: https://github.com/opencrvs/opencrvs-farajaland/pull/307
=> ocrvs-3239 Fixed form config messages

packages/client/src/views/SysAdmin/Config/Application/Application.tsx, packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx, packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx, packages/client/src/views/SysAdmin/Performance/CompletenessRates.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx, packages/client/src/views/SysAdmin/SysAdminContentWrapper.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/client/src/views/SysAdmin/Team/user/userProfilie/UserProfile.tsx, packages/components/src/components/interface/ActionPageLight.tsx
=> ocrvs-2841: padding issue fixed with ActionPageLight and SysAdminContentWrapper

packages/client/src/views/SysAdmin/Config/Application/DynamicModal.tsx
=> ocrvs-3269 Fixed appconfig input alignment

packages/client/src/SubmissionController.ts
=> Ocrvs 3516 Fixed record stays assigned to Registrar after printing issue

packages/client/src/SubmissionController.test.ts, packages/client/src/SubmissionController.ts, packages/client/src/declarations/index.ts, packages/client/src/declarations/selectors.ts, packages/client/src/forms/index.ts, packages/client/src/views/DataProvider/birth/mutations.ts, packages/client/src/views/DataProvider/death/mutations.ts, packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/src/views/RecordAudit/mutations.ts, packages/client/src/views/RecordAudit/utils.ts, packages/client/src/views/SysAdmin/Config/Forms/Wizard/SaveActionModal.tsx
=> ocrvs-2689 Properly updated status to Reinstated

packages/client/src/views/PrintCertificate/PDFUtils.test.ts, packages/client/src/views/PrintCertificate/PDFUtils.ts, packages/client/src/views/PrintCertificate/Payment.tsx
=> ocrvs-2895: deleted all code related to print receipt

packages/client/src/components/interface/Navigation.tsx, packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
=> ocrvs-3530 Hide form config not published config for mobile device

packages/client/src/views/SysAdmin/Config/Forms/Wizard/FormConfigWizard.tsx, packages/components/src/components/icons/SettingsBlue.tsx
=> ocrvs-3158 Changed FormConfig settings icon color and shape

packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx
modifiedAt at is being changed if anyone assign or unassign declaration, so modifiedAt can't be used.
=> 'createdAt' is being used in sentForReview column

packages/workflow/src/features/events/handler.ts, packages/workflow/src/utils/authUtils.ts
=> ocrvs-3551 Fixed FA can't download assigned declarations

packages/client/src/views/SearchResult/SearchResult.tsx
=> duplicate icon removed from WQ in search

packages/workflow/src/utils/formDraftUtils.ts
=> ocrvs-3578 Fixed from config update bug

packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/src/views/RecordAudit/queries.ts
Instead of redirecting to HOME, showing an errorNotification with a retry button. As the error was not reproducible, tried to simulate the scenario by going offline
=> ocrvs-3568 Provided a way to recover from error

packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx, packages/notification/src/constants.ts
=> Add cert link and rename SMS env vars

.github/ISSUE_TEMPLATE/user-story.md
removes ?? from the template which I have to delete every time i create an issue.
=> removes ?? from templete

packages/client/src/views/RecordAudit/RecordAudit.tsx
https://user-images.githubusercontent.com/42269993/177281543-596f2857-4445-4e98-955b-dfe71260dbe4.mp4
=> Ocrvs 3580 Fix assigned user not showing in record audit

packages/client/src/tests/default.json, packages/client/src/views/RecordAudit/RecordAudit.tsx
=> ocrvs-2871 Archive in progress declarations

packages/client/src/forms/configuration/administrative/addresses.ts, packages/client/src/forms/configuration/customUtils.ts, packages/client/src/forms/configuration/formConfig/utils/index.ts
=> ocrvs-3575 Added default conditionals for custom fields

packages/client/src/views/Unlock/Unlock.tsx
=> ocrvs-2747 Removed spinner from Unlock component

packages/components/src/components/interface/Header/PageHeader.tsx
=> OCRVS 3800 / Fix `<PageHeader>` being 1px too tall

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/components/interface/Header/Header.tsx, packages/client/src/i18n/messages/views/userForm.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/333
=> ocrvs-2917 Fix user flow bugs

package.json, yarn.lock
=> OCRVS-3820 / Fix incompatible TS types by pinning @types/react version

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/correction/corrector.ts, packages/client/src/i18n/messages/constants.ts, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Associated PR in farajaland:
https://github.com/opencrvs/opencrvs-farajaland/pull/334
=> Fix OCRVS-2703

packages/client/src/components/interface/Navigation.tsx, packages/client/src/storage.ts, packages/client/src/utils.ts, packages/client/src/utils/constants.ts, packages/components/src/components/interface/Navigation/LeftNavigation.tsx
=> ocrvs-3731 Added application version validation and clear declarations draft

packages/client/src/views/OfficeHome/sentForReview/SentForReview.tsx, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts
- Pass assignment data to download button of sent for approval work queue
- Add a check before task update assignment; if the practitioner is reg agent and task businessStatus is validated then dont assign
=> ocrvs-3814 Fix assignment bugs for registration agent

packages/client/src/components/interface/DownloadButton.test.tsx, packages/client/src/components/interface/DownloadButton.tsx
https://user-images.githubusercontent.com/42269993/188856743-ba8fd34f-6426-41c2-a633-92c2c622cd83.mp4
=> Ocrvs 3836

.github/workflows/cd-manual-e2e.yml, .github/workflows/e2e.yml, infrastructure/server-setup/example-1.ini, packages/client/src/forms/configuration/default.ts
Requires this Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/349
=> OCRVS-3561: Date of informant etc

packages/client/src/tests/default.json, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/RegisterForm/PreviewForm.test.tsx
This PR has a farajaland dependency PR
https://github.com/opencrvs/opencrvs-farajaland/pull/350
=> ocrvs-3977 Fixed multipleBirth of mother field value on declaration

package.json, packages/components/.storybook/main.js, packages/components/Dockerfile
Reverts opencrvs/opencrvs-core#3862
=> Revert "Get styleguide hosted"

docker-compose.deploy.yml, infrastructure/traefik.toml, package.json, packages/components/.storybook/main.js, packages/components/Dockerfile, packages/components/package.json
Reverts opencrvs/opencrvs-core#4006
=> Revert "Revert "Get styleguide hosted""

packages/client/src/forms/questionConfig/transformers.ts
=> ocrvs-3985 Fixed default configurable field required issue 

packages/client/src/views/RegisterForm/RegisterForm.tsx
=> Ocrvs 3650 Fix declaration icon color bug

packages/client/src/views/SysAdmin/Config/Forms/Home/FormConfigHome.tsx
=> ocrvs-4019 Fixed publishedWarning message on declaration form config page

packages/client/src/views/Unlock/ForgotPIN.tsx
=> ocrvs-4032 Fixed ForgotPIN page UI issue

packages/client/src/forms/configuration/customUtils.ts
=> Invert conditional logic for customize field

packages/client/src/views/OfficeHome/OfficeHome.tsx, packages/client/src/workqueue/reducer.ts
Multiplied pageSize with pageNo to produce pageSkip and stopped fetching data when paginating the drafts.
=> ocrvs-3671 Fixed issues with officeHome pagination

packages/client/graphql.schema.json, packages/client/src/i18n/messages/views/sysAdmin.ts, packages/client/src/user/mutations.ts, packages/client/src/user/queries.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/SysAdmin/Team/user/UserList.test.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/gateway/src/features/user/root-resolvers.test.ts, packages/gateway/src/features/user/root-resolvers.ts, packages/gateway/src/features/user/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/notification/src/config/routes.ts, packages/notification/src/features/sms/user-handler.test.ts, packages/notification/src/features/sms/user-handler.ts, packages/notification/src/features/sms/utils.ts, packages/notification/src/i18n/messages.ts, packages/notification/src/tests/util.ts, packages/user-mgnt/src/config/routes.ts, packages/user-mgnt/src/features/resstPassword/handler.test.ts, packages/user-mgnt/src/features/resstPassword/handler.ts
=> ocrvs-4039 Reset password feature

packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/components/src/Icon/types.ts, packages/components/src/TextArea/TextArea.tsx
- make review section readonly.
=> readonly review section

docker-compose.yml, packages/client/src/offline/reducer.ts, packages/client/src/tests/mock-offline-data.ts, packages/client/src/tests/util.tsx, packages/client/src/utils/referenceApi.test.ts, packages/client/src/utils/referenceApi.ts, packages/client/typings/window.d.ts, packages/config/src/config/constants.ts, packages/config/src/config/routes.ts, packages/config/src/handlers/application/applicationConfigHandler.ts, packages/config/src/handlers/system/systemHandler.ts, packages/config/src/models/config.ts, packages/config/src/services/userManagementService.ts, packages/config/src/utils/auth.ts, packages/gateway/src/features/application/root-resolvers.ts, packages/gateway/src/features/application/schema.graphql, packages/gateway/src/features/application/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/metrics/test/setupJest.ts, packages/user-mgnt/src/config/routes.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts, packages/workflow/src/features/registration/handler.test.ts, packages/workflow/src/test/utils.ts
Exposes Integration configuration from user-mgnt to frontend through config-microservice.
=> OCRVS-4142 Expose integrations from user-mgnt to frontend

packages/client/src/i18n/messages/views/integrations.ts, packages/client/src/utils/referenceApi.ts, packages/client/src/views/SysAdmin/Config/Integrations/Integrations.tsx
Adds the integrations from config to list them on IntegrationsList on SysAdmin configuration.
Closes #3592
=> OCRVS-3592 Fetch integrations from config to list them on IntegrationsList

packages/client/src/views/Unlock/ForgotPIN.test.tsx, packages/client/src/views/Unlock/ForgotPIN.tsx, packages/login/src/Page.tsx, packages/login/src/i18n/components/LanguageSelect.tsx, packages/login/src/views/resetCredentialsForm/forgottenItemForm.tsx
- Retain language on the can't login page.
=> ocrvs-4032: retain language on the can not login page

infrastructure/clear-all-data.sh, packages/metrics/scripts/VSExportGenerator.ts
FARAJALAND PR - https://github.com/opencrvs/opencrvs-farajaland/pull/403
=> Vs-export - Fix HEARTH_MONGO_URL & clear data

packages/migration/migrations/hearth/20221017133354-restore-supporting-document.js, packages/migration/migrations/hearth/20221110092434-add_identifiers_DOB_gender_location.js, packages/migration/package.json, packages/migration/utils/elasticsearch-helper.js, packages/migration/utils/hearth-helper.js
**This is what the log looks like:** 
Migration - ElasticSearch :: Processing 50 of 368 compositions...
Migration - ElasticSearch :: Processing done 13.59% of 100%
Migration - ElasticSearch :: Processing 100 of 368 compositions...
Migration - ElasticSearch :: Processing done 27.17% of 100%
Migration - ElasticSearch :: Processing 150 of 368 compositions...
Migration - ElasticSearch :: Processing done 40.76% of 100%
Migration - ElasticSearch :: Processing 200 of 368 compositions...
Migration - ElasticSearch :: Processing done 54.35% of 100%
Migration - ElasticSearch :: Processing 250 of 368 compositions...
Migration - ElasticSearch :: Processing done 67.93% of 100%
Migration - ElasticSearch :: Processing 300 of 368 compositions...
Migration - ElasticSearch :: Processing done 81.52% of 100% …
=> ocrvs-4118 elasticSearch migration to add missing identifiers, DOB, gender, eventJurisdictionIds and eventCountry

packages/client/src/App.tsx, packages/client/src/components/ProtectedPage.tsx, packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/i18n/messages/views/recordAudit.ts, packages/client/src/navigation/routes.ts, packages/client/src/profile/profileReducer.ts, packages/client/src/utils/authUtils.ts, packages/client/src/views/PrintCertificate/DeclarationInfo.tsx, packages/client/src/views/PrintCertificate/VerifyDetails.tsx, packages/login/src/login/reducer.ts
[verify-qr.webm](https://user-images.githubusercontent.com/42269993/201888329-27734423-29dd-424b-9051-d1ff6c087c32.webm)
=> Verify qr code

docker-compose.deploy.yml, packages/client/vite.config.js, packages/login/vite.config.js, packages/migration/migrations/openhim/20221121124457-remove-old-transactions.cjs
Includes a migration to delete legacy openhim transactions
Also increased wait for unit tests
=> OCRVS-4070: Disable OpenHIM API endpoint unless whitelisted

packages/auth/src/features/retrievalSteps/sendUserName/service.ts, packages/client/package.json, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/user-mgnt/src/features/createUser/service.ts
Should fix login Sentry issues on PerformanceHome
=> Show error toast at correct point so as to avoid Sentry error

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
- Registration by status page of performance is broken
=> ocrvs-4217: Registration by status page of performance is broken

packages/client/src/views/RecordAudit/ActionDetailsModal.tsx, packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/vite.config.js, packages/login/vite.config.js
Please ignore the ID check table as it should be fixed with #4331
=> ocrvs-3544 Fix rejected reason showing for retrieved action

packages/client/src/views/CorrectionForm/ReviewForm.tsx, packages/client/src/views/CorrectionForm/VerifyCorrector.tsx, packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx
Reverts opencrvs/opencrvs-core#4303
I just realized that this makes a user unable to go back through history more than once.
=> Revert "Fixed bug for system crashing  if back arrow is clicked  after printing or correcting a  record"

packages/client/src/i18n/messages/views/integrations.ts, packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx, packages/gateway/src/features/search/root-resolvers.ts, packages/gateway/src/graphql/config.ts, packages/user-mgnt/src/features/system/handler.ts, packages/webhooks/src/features/event/handler.ts, packages/webhooks/src/features/event/service.ts, packages/workflow/src/features/user/utils.test.ts, packages/workflow/src/features/user/utils.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/441
Closes #4299
=> Fixes to Webhook & RecrdSearch integration

packages/components/src/Pill/Pill.tsx
- updated to using theme colours
- sizings tweaked
=> Update Pill to use colors

packages/migration/migrate-mongo-config-user-mgnt.js, packages/migration/migrations/application-config/20221212134153-update-systems.js, packages/migration/migrations/user-mgnt/20221212134201-update-systems.js, packages/migration/package.json
Migrates for integration configuration:
* adds a new `type` -param to `systems` -collection in user-mgnt
* adds a empty `settings.webhook` array in user-mgnt
* removes `INTEGRATIONS` array from application-config
* migrates `createdBy` and `name` in `systems` -collection user-mgnt
=> chore(integration-configuration): System migrations for integration configuration

packages/client/src/forms/configuration/administrative/addresses.ts, packages/client/src/forms/configuration/default.ts, packages/client/src/i18n/messages/form.ts, yarn.lock
- informant section amends
- hide informant radio and point of contact view group
=> NGA Death form changes - informant

infrastructure/clear-all-data.sh, packages/migration/migrations/user-mgnt/20221212134201-update-systems.js, packages/migration/package.json, packages/migration/revertMigrations.sh, packages/migration/runMigrations.sh
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/444
=> OCRVS-4433: We need to make sure that default backups do not have run migrations in them

packages/auth/src/features/authenticate/service.ts, packages/auth/src/features/retrievalSteps/sendUserName/service.ts, packages/auth/src/features/verifyCode/service.ts
Also needs this to enable SMS: https://github.com/opencrvs/opencrvs-farajaland/pull/453
=> Add countryconfig service to SMS token audience

packages/client/src/i18n/messages/constants.ts, packages/client/src/offline/reducer.ts, packages/client/src/tests/mock-offline-data.ts, packages/client/src/views/SysAdmin/Config/Certificates/previewDummyData.ts, packages/client/src/views/SysAdmin/Team/user/UserList.tsx
This PR is related to [460](https://github.com/opencrvs/opencrvs-farajaland/pull/460).
=> ocrvs-4536: Fix location showing in team page

packages/client/graphql.schema.json, packages/client/src/declarations/index.ts, packages/client/src/i18n/messages/views/duplicates.ts, packages/client/src/transformer/index.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/RecordAudit/queries.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/ReviewForm.tsx, packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx, packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/client/src/views/ViewRecord/query.ts, packages/components/src/DocumentViewer/DocumentViewer.tsx, packages/components/src/FormTabs/FormTabs.tsx, packages/components/src/FormTabs/components/Tabs.tsx, packages/gateway/src/features/fhir/utils.ts, packages/gateway/src/features/registration/schema.graphql, packages/gateway/src/features/registration/type-resolvers.test.ts, packages/gateway/src/features/registration/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, yarn.lock
FARAJALAND PR - https://github.com/opencrvs/opencrvs-farajaland/pull/464
=> Duplicates view on review page

packages/client/src/declarations/index.ts
=> Fix field agent sent for review wq discrepency after downloading a declaration

packages/client/src/forms/configuration/default.ts
Removed father & mother's nid check against informant as it kinda creates a cycle
=> ocrvs-4594 Check only informant's nid against father & mother

packages/components/src/ComparisonListView/ComparisonListView.stories.tsx, packages/components/src/ComparisonListView/ComparisonListView.tsx, packages/components/src/ComparisonListView/RowView.tsx
=> Added new ComparisonList view component

.gitignore, packages/client/src/components/UnprotectedRoute.tsx, packages/client/src/hooks/useTimeout.ts, packages/client/src/i18n/messages/views/verifyCertificate.ts, packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx, packages/components/src/Toast/Toast.stories.mdx, packages/components/stories/releases.stories.mdx
This PR allows an anonymous user to verify his certificate from the QR code visible on it. After 1 minute, he receives a message asking him to close the verification page for his certificate. After 10 minutes, the information on the certificate page is no longer visible.
=> Opencrvs 4418 reviewed

packages/client/graphql.schema.json, packages/client/src/i18n/messages/views/performance.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/OfficeHome/OfficeHome.test.tsx, packages/client/src/views/OfficeHome/readyToPrint/readyToPrint.test.tsx, packages/client/src/views/OfficeHome/requiresUpdate/requiresUpdate.test.tsx, packages/client/src/views/Performance/FieldAgentList.tsx, packages/client/src/views/Settings/items/Role.tsx, packages/client/src/views/SysAdmin/Config/UserRoles/utils.ts, packages/client/src/views/SysAdmin/Performance/queries.ts, packages/client/src/views/SysAdmin/Team/TeamSearch.test.tsx, packages/client/src/views/UserSetup/SetupReviewPage.test.tsx, packages/client/src/views/UserSetup/SetupReviewPage.tsx, packages/gateway/src/features/user/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/metrics/src/api.ts, packages/user-mgnt/src/config/routes.ts, packages/user-mgnt/src/features/countUsersByLocation/handler.ts, packages/user-mgnt/src/features/countUsersByLocation/service.ts
This PR is related to [#496]( https://github.com/opencrvs/opencrvs-farajaland/pull/496)
=> Ocrvs 4445

docker-compose.deploy.yml, docker-compose.deps.yml, package.json, packages/auth/package.json, packages/client/package.json, packages/client/src/utils/constants.ts, packages/commons/package.json, packages/components/package.json, packages/config/package.json, packages/documents/package.json, packages/gateway/package.json, packages/integration/package.json, packages/login/package.json, packages/metrics/package.json, packages/migration/package.json, packages/notification/package.json, packages/search/package.json, packages/user-mgnt/package.json, packages/webhooks/package.json, packages/workflow/package.json
=> Hotfix v1.2.1

packages/client/src/App.tsx, packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/components/interface/DownloadButton.tsx, packages/client/src/forms/configuration/default.ts, packages/client/src/forms/index.ts, packages/client/src/forms/utils.ts, packages/client/src/i18n/messages/form.ts, packages/client/src/utils.ts, packages/client/src/views/AdvancedSearch/RemoveBookmarkModal.tsx, packages/client/src/views/AdvancedSearch/SaveBookmarkModal.tsx, packages/client/src/views/OfficeHome/LoadingIndicator.tsx, packages/client/src/views/OfficeHome/outbox/Outbox.tsx, packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/src/views/Settings/items/Password.tsx, packages/client/src/views/Settings/items/PhoneNumber.tsx, packages/client/src/views/SysAdmin/InformantSMSNotification/InformantSMSNotification.tsx, packages/components/src/Icon/all-icons.ts, packages/components/src/VerificationButton/VerificationButton.stories.tsx, packages/components/src/VerificationButton/VerificationButton.tsx, packages/user-mgnt/src/features/system/handler.ts
* shows an error message if user is offline
* refactors "useOnlineStatus" into generic utils
* fixes App.tsx & Icon -issues in base branch
* fixes Joi validation on user-mgnt systems
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/512
=> feat(national-id-verification): handle when user is offline

packages/client/graphql.schema.json, packages/client/src/forms/configuration/formConfig/utils/defaultConfig.ts, packages/client/src/forms/configuration/formConfig/utils/index.ts, packages/client/src/forms/configuration/formConfig/utils/previewGroup.ts, packages/client/src/forms/index.ts, packages/client/src/forms/mappings/deserializer.ts, packages/client/src/forms/questionConfig/index.ts, packages/client/src/forms/questionConfig/transformers.ts, packages/client/src/forms/validation.ts, packages/client/src/i18n/messages/validations.ts, packages/client/src/utils/gateway.ts, packages/client/src/utils/validate.ts, packages/config/src/models/question.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql
Related Cameroon PR here: https://github.com/agence-digital/opencrvs-cameroon/pull/53
=> [OCRVS-4818] Enable making a default field optional, flag to run validations on empty fields

packages/client/src/i18n/messages/views/formConfig.ts
This PR is related to [519](https://github.com/opencrvs/opencrvs-farajaland/pull/519)
=> ocrvs-4556

packages/client/src/declarations/submissionMiddleware.ts, packages/client/src/views/DataProvider/death/mutations.ts, packages/search/src/features/registration/deduplicate/deduplicate.test.ts, packages/search/src/features/registration/deduplicate/service.ts
=> Shows death duplicate notification toast and added deceaseDob for duplicate logic

packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx
https://user-images.githubusercontent.com/32668488/227484085-5c2436dc-3047-4083-a514-30173892a6a5.mp4
=> duplicate comparison page DOB fix

packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/530
=> Correction record option fix for marriage

packages/client/src/i18n/messages/views/advancedSearchResult.ts, packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx, packages/client/src/views/AdvancedSearch/BookmarkAdvancedSearchResult.tsx, packages/client/src/views/SearchResult/AdvancedSearch.tsx
- fixes supporting copy to use Content subtitle param
- reduce Pill size
- updates colour of Save icon
- updates copy of pill params
- fixes Search button to use Button component
https://github.com/opencrvs/opencrvs-farajaland/pull/533
=> fix: Advance search and results ui

packages/client/src/components/Header/HistoryNavigator.tsx
- changes the forward and back button to medium Buttons
=> fix: changes nav buttons to medium

packages/components/src/TextArea/TextArea.tsx
=> refactor: TextArea background to white

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/correction/corrector.ts, packages/client/src/i18n/messages/views/correction.ts, packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx, packages/client/src/views/ViewRecord/ViewRecord.test.tsx, packages/gateway/src/features/fhir/utils.ts, packages/gateway/src/features/registration/fhir-builders.ts, packages/gateway/src/features/registration/root-resolvers.test.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/536
=> certified tab in record audit history for marriage fix

infrastructure/server-setup/playbook-1.yml, infrastructure/server-setup/playbook-3.yml, infrastructure/server-setup/playbook-5.yml
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/537
=> Force disk encryption and enable configurable diskspace

infrastructure/server-setup/playbook-1.yml, infrastructure/server-setup/playbook-3.yml, infrastructure/server-setup/playbook-5.yml
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/547
=> Force disk encryption and add encrypted_disk_size param for Ansible

packages/workflow/src/features/events/handler.ts, packages/workflow/src/features/registration/fhir/constants.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts, packages/workflow/src/features/registration/handler.ts
=> Reject an application if any error occurs in country config

packages/client/src/i18n/messages/form.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/550
=> marriageForm lastName title fix

infrastructure/license-config.json, packages/components/src/DocumentViewer/DocumentViewer.tsx
Expected result: 
[ocrvs-5157.webm](https://user-images.githubusercontent.com/11840131/234578670-4b6e5e3b-603f-45dd-bf1d-33b05656c3a7.webm)
=> ocrvs-5157

packages/workflow/src/features/events/handler.ts, packages/workflow/src/features/registration/fhir/constants.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts, packages/workflow/src/features/registration/handler.ts
Reverts opencrvs/opencrvs-core#5158
=> Revert "Reject an application if any error occurs in country config"

packages/client/src/forms/configuration/default/birth.ts, packages/client/src/forms/configuration/default/death.ts, packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/views/SysAdmin/Team/utils.ts
This PR add new value for office location in template certificate.
PR of Cameroon-config : https://github.com/agence-digital/opencrvs-cameroon/pull/81
=> Certificate: office location in the top header must be dynamically populated

docker-compose.yml, packages/gateway/src/constants.ts, packages/gateway/src/features/systems/root-resolvers.ts, packages/user-mgnt/src/features/system/handler.ts, packages/webhooks/src/config/routes.ts, packages/webhooks/src/features/manage/handler.ts
Webhooks Joi validation incorrect, additionally when an integration is deleted, its associated webhooks must be deleted
=> Fix webook Joi validation and delete webhooks when an integration is deleted

packages/migration/migrations/openhim/20230210112528-marriage-channels.cjs
[ocrvs-5155.webm](https://user-images.githubusercontent.com/11840131/235851459-8a6ccf55-fcae-4d98-90bf-70daee3d4baa.webm)
=>  ocrvs-5155

packages/client/graphql.schema.json, packages/client/src/forms/configuration/customUtils.ts, packages/client/src/forms/index.ts, packages/client/src/forms/questionConfig/index.ts, packages/client/src/forms/questionConfig/transformers.ts, packages/client/src/tests/schema.graphql, packages/client/src/utils/gateway.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/gateway/src/features/questions/schema.graphql, packages/gateway/src/graphql/schema.graphql
With these, you should be able to add new custom file inputs
=> [OCRVS-5227] Add support for new questions config fields: mapping, conditionals, extraValue

docker-compose.dev-deps.yml, packages/workflow/src/features/registration/handler.ts
=> populate composition with id on markCertified and markIssuedHandler. fix #5242

.vscode/settings.json
Reverts opencrvs/opencrvs-core#5262
=> Revert "add organize imports to settings.json"

packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql, packages/gateway/src/features/search/schema.graphql, packages/gateway/src/features/search/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/features/search/types.ts, packages/search/src/features/search/utils.ts
Search params added:
* groomIdentifier (Marriage Event)
* brideIdentifier (Marriage Event)
Return values added:
* groomIdentifier (Marriage Event)
* brideIdentifier (Marriage Event)
* deceasedGender (Death Event)
=> Add new search params & return value

packages/client/src/forms/configuration/default/marriage.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/560
=> Removed label for witness 1 and witness 2 in marriage declaration

packages/client/src/views/CorrectionForm/utils.ts, packages/client/src/views/RecordAudit/utils.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
[5240.webm](https://github.com/opencrvs/opencrvs-core/assets/11840131/83c71bde-2221-4bbd-a440-0c7a1007cc28)
=> ocrvs-5240

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
=> [OCRSV-5286] Make marriage signatures optional

docker-compose.deploy.yml, docker-compose.yml, packages/scheduler/Dockerfile, packages/scheduler/cronTabFile/crontab, packages/scheduler/crontab, packages/scheduler/jobs/clearOpenHIMTransactions.sh, packages/scheduler/start.sh
Reverts opencrvs/opencrvs-core#5318
=> Revert "clear old OpenHIM transactions every night"

packages/client/src/views/RecordAudit/utils.ts
updated 'getLocation' function to include 'internationalDistrict' and  'internationalState' for marriage event #5333
=> fixes #5333 

docker-compose.deploy.yml, docker-compose.replicas-3.yml, docker-compose.replicas-5.yml, docker-compose.yml, infrastructure/license-config.json, packages/scheduler/Dockerfile, packages/scheduler/cronTabFile/crontab, packages/scheduler/crontab, packages/scheduler/jobs/clearOpenHIMTransactions.sh, packages/scheduler/start.sh
Reverts opencrvs/opencrvs-core#5335
=> Revert "Revert "clear old OpenHIM transactions every night""

packages/metrics/src/features/performance/viewRefresher.ts
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/564
=> Fix viewRefresher logic in OpenCRVS prod server

packages/client/src/utils/validate.ts
[ocrvs-5334.webm](https://github.com/opencrvs/opencrvs-core/assets/11840131/a4a7987c-f601-407c-b246-20d6ea2af662)
=> ocrvs-5334

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/i18n/messages/views/correction.ts, packages/client/src/views/CorrectionForm/CorrectionSummary.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/566
=> correction summary warning fix

packages/client/src/forms/user/fieldDefinitions/createUser.ts, packages/client/src/i18n/messages/views/userForm.ts
=> Ocrvs 5217 Add type of organisation field 

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Cameroon-config PR : https://github.com/agence-digital/opencrvs-cameroon/pull/108
=> Add declarant label  for a better reading

packages/client/src/forms/user/fieldDefinitions/createUser.ts, packages/client/src/forms/utils.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
=> Fix user form issues

packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx, packages/components/src/Tooltip/Tooltip.stories.tsx, packages/components/src/Tooltip/Tooltip.tsx
=> #5444 fixed missing event type in ready to issue

packages/client/src/forms/configuration/administrative/addresses.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Reverts opencrvs/opencrvs-core#5189
The approach [@Nil20](https://github.com/Nil20) cant work if the address configuration is in Farajaland as per the new config requirements. I need to revert the pull request. I will move to tech design for a new approach to be defined.
=> Revert "Ocrvs 5086 - fix address for same residence"

packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/DataProvider/marriage/queries.ts, packages/gateway/src/features/registration/type-resolvers.ts
[Cameroon-CRVS.webm](https://github.com/opencrvs/opencrvs-core/assets/42269993/6be2ed2b-a876-4ec5-8a86-0a654cfb62b6)
=> Fix download issues

packages/client/src/components/Header/Header.tsx, packages/client/src/views/OfficeHome/OfficeHome.tsx
=> Hide add event button for registrar

packages/client/src/forms/register/customFieldMappings/query/customField-mappings.ts, packages/client/src/i18n/messages/constants.ts, packages/client/src/views/PrintCertificate/PDFUtils.ts, packages/client/src/views/RecordAudit/DeclarationInfo.tsx, packages/client/src/views/RecordAudit/History.tsx
=> Cameroon some fix translate

packages/client/src/forms/user/fieldDefinitions/createUser.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx, packages/gateway/src/index.test.ts, packages/search/src/index.test.ts, packages/user-mgnt/src/index.test.ts
=> User creation user-name fix

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/utils.ts
Support for https://github.com/newlegacydigital/opencrvs-cameroon/pull/126
=> Add support for conditional expression to get agentDefault initial value

packages/client/src/components/form/FormFieldGenerator.tsx
improve form `<select>` performance by memoizing renders in FormFieldGenerator. A performance issue was found in Cameroon QA testing.
=> improve form `<select>` performance by memoizing renders

packages/client/src/i18n/messages/form.ts
[farajaland pr](https://github.com/opencrvs/opencrvs-farajaland/pull/602)
=> removed unused message descriptions

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/views/RecordAudit/utils.ts
This PR displays the place of birth in the record audit page of a declaration of birth. And also to display the place of death in the record audit page of a declaration of death.
=> Cameroon update record audit birth and death

packages/config/src/models/certificate.ts, packages/gateway/src/features/dataSeeding/certificateSeeding.ts, packages/gateway/src/features/dataSeeding/index.ts
[farajaland pr](https://github.com/opencrvs/opencrvs-farajaland/pull/608)
#5539
=> seeding certificate

packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/pdfRenderer/transformer/userTransformer.ts
This PR add new function to get FirstName and FamilyName for secretary and registar
=> Stack {{name}} {{Givennames}} for Registrar and Secretary

packages/client/src/utils/locationUtils.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/DataProvider/marriage/queries.ts, packages/client/src/views/Organisation/AdministrativeLevels.tsx, packages/client/src/views/RecordAudit/History.tsx, packages/client/src/views/RegisterForm/review/RegistrationOfficeSelect.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx
In 
- record audit history
- organization list
- user list page
- location picker of the user list 
- field agent registration office select
=> Cameroon: Localize office names

packages/client/src/utils/locationUtils.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/DataProvider/marriage/queries.ts, packages/client/src/views/Organisation/AdministrativeLevels.tsx, packages/client/src/views/RecordAudit/History.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx
In 
- record audit history
- organization list
- user list page
- location picker of the user list 
- field agent registration office select
=> Localize location names

packages/client/src/forms/mappings/mutation/field-mappings.ts, packages/client/src/tests/schema.graphql, packages/gateway/src/features/registration/type-resolvers.ts
FAR PR - https://github.com/opencrvs/opencrvs-farajaland/pull/616
=> Ocrvs 5514  Death Declaration Form

packages/client/src/components/interface/Navigation.tsx, packages/client/src/utils/constants.ts, packages/client/src/views/OfficeHome/OfficeHome.test.tsx, packages/client/src/views/OfficeHome/OfficeHome.tsx, packages/client/src/workqueue/reducer.ts
In this PR, the registrar no longer has access to the "In progress" workqueue. And in the "Ready to review" workqueue, it only sees declarations with the status "DECLARED", i.e. only those validated by the secretary.
=> Cameroon GN 037

packages/gateway/src/features/dataSeeding/index.ts, packages/gateway/src/features/restLocation/utils.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/606
=> ocrvs-5538 seed the locations

packages/config/src/handlers/application/applicationConfigHandler.test.ts, packages/config/src/handlers/application/applicationConfigHandler.ts
changing getConfig() and updateConfig() to include default config from country-config
=> serving application config from country-config

packages/gateway/src/features/dataSeeding/certificateSeeding.ts, packages/migration/src/migrations/application-config/20230301124048-add-marriage-certificate-configuration.ts
=> seeding certificate only when there is no active certificate

packages/client/src/views/PrintCertificate/PDFUtils.ts
This PR publishes the getLocalizedLocationName function as a handlerbar for translating municipalities in certificates
=> GN-041: publish getLocalizedLocationName function 

packages/client/src/i18n/messages/views/review.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, yarn.lock
=> Added missing french translation in hide/show option in review section

packages/client/src/components/ProtectedPage.tsx, packages/client/src/utils/authUtils.ts
=> Handle non 2XX response from /refreshToken endpoint

packages/client/src/components/form/ReviewActionComponent.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx
https://github.com/opencrvs/opencrvs-core/issues/5510#issuecomment-1655471150
=> fixed exit modal not showing after save and exit

packages/client/src/components/form/ReviewActionComponent.tsx
=> fixed title of reviewActionComponent for rejected declarations

packages/client/src/i18n/messages/validations.ts, packages/client/src/utils/validate.ts
This PR contains a validator only for checking the format of a date and giving the corresponding error message.
=> Validator to check that a date is valid

packages/client/src/i18n/messages/views/duplicates.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/651
=> duplicate review page bug fix

packages/client/src/forms/questionConfig/index.ts, packages/client/src/forms/questionConfig/transformers.ts, packages/client/src/index.tsx
This PR can be used to modify the maxLength from the country-config
=> update maxLength from cameroon config

packages/client/src/views/RegisterForm/RegisterForm.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/654
=> ocrvs 5733 - add key in form

packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx, packages/components/src/BulletList/BulletList.tsx, packages/components/src/Content/Content.tsx
- fixes AppBar button sizes in Form
- updates Content padding
- updates Bullet padding
=> refactor: small ui fixes

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
- fixes padding
- removes icon from button
=> Fix: Continue button on Correction flow padding

packages/components/src/Heading3/Heading3.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/663
=> heading component update

packages/gateway/src/features/registration/fhir-builders.ts, packages/gateway/src/features/registration/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql
Removed unimplemented registration inputs & implemented possible input values of informant
=> Data generator fix: Update schema and fhir-builders

packages/client/src/i18n/messages/views/certificate.ts, packages/client/src/views/CorrectionForm/IDVerifier.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/678
=> id verifier for correction modal title fix

packages/client/src/components/Notification.tsx, packages/client/src/i18n/messages/views/notifications.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/682
=> creating user in offline toast message fix

packages/client/src/src-sw.ts
TBH I am not sure exactly what this was doing but I'm guessing something along the lines of queueing the gql requests when offline and retrying them after being back online. Maybe it was relevant at some point but I don't think it is now because we don't really have any requirements like this.
=> Remove request queue

packages/user-mgnt/package.json, packages/user-mgnt/src/features/verifyPassword/handler.ts, packages/user-mgnt/src/utils/hash.ts
To resolve issues logging in after migrating 1.2 data
=> OCRVS-5851: Add old hashing functions

packages/components/src/TimeField/TimeField.tsx
updates width of segment so the placeholder copy is visible
=> refactor: update time input segment width

development-environment/clear-all-data.sh, package.json, packages/client/src/forms/index.ts, packages/client/src/forms/register/mappings/mutation/field-mappings.ts, packages/client/src/forms/register/mappings/query/field-mappings.ts, yarn.lock
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/693
=> Fix typo and move clear command

docker-compose.deps.yml
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/695
=> Upgrade minio

packages/client/src/forms/register/mappings/event-specific-fields/marriage/mutation/registration-mappings.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
This reverts commit 31846be9181e571c1e2fd902424ab3ecb70cdebf.
#5869
=> signature payload fix for marriage

packages/client/src/i18n/messages/views/correction.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/726
=> typo fix for correction

development-environment/clear-all-data.sh, packages/scheduler/jobs/clearOpenHIMTransactions.sh
OpenHIM backups are still massive even after30 days.  Lets reduce to 7 days of logs
=> Fix clear command and reduce storage time of OpenHIM transactions

packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/src/views/RecordAudit/utils.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx
This PR adds a new function for displaying the place of death based on our form logic, and also takes into account the display of the Health facility entered when it is not in the list.
=> Add place of death in record audit

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/certificate/fieldDefinitions/messages.ts, packages/client/src/utils/validate.ts
This PR creates a new validation function which will be used to display an error when the date entered is not in the past in relation to a date on the form.
=> create validation function dateNotPastFieldDate

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/correction/verifyCorrector.ts, packages/client/src/i18n/messages/views/certificate.ts, packages/client/src/i18n/messages/views/correction.ts, packages/client/src/views/CorrectionForm/IDVerifier.tsx, packages/client/src/views/CorrectionForm/VerifyCorrector.tsx, packages/client/src/views/PrintCertificate/IDVerifier.tsx, packages/client/src/views/PrintCertificate/VerifyCollector.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/762
=> refactor id verifier for print and issue

packages/data-seeder/src/locations.ts, packages/gateway/src/config/routes.ts, packages/gateway/src/features/eventNotification/eventNotificationHandler.ts, packages/gateway/src/features/restLocation/locationHandler.ts, packages/migration/src/migrations/hearth/20230905130632-elastic-search-property-rename.ts
farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/761
=> ocrvs-6063 query validation for location endpoint

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/utils.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/config/src/handlers/forms/validation.ts, packages/login/src/common/LoginBackgroundWrapper.tsx, packages/login/src/login/selectors.ts
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/745
=> Requirements for Niue

packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx, packages/documents/src/features/uploadSvg/handler.ts, packages/notification/src/features/sms/birth-handler.test.ts, packages/notification/src/features/sms/birth-handler.ts, packages/notification/src/features/sms/death-handler.test.ts, packages/notification/src/features/sms/death-handler.ts, packages/notification/src/index.test.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.test.ts, packages/workflow/src/features/registration/fhir/fhir-template.test.ts, packages/workflow/src/features/registration/fhir/fhir-utils.ts, packages/workflow/src/features/registration/handler.test.ts, packages/workflow/src/features/registration/handler.ts, packages/workflow/src/features/registration/utils.test.ts, packages/workflow/src/features/registration/utils.ts, packages/workflow/src/features/task/fhir/fhir-bundle-modifier.test.ts, packages/workflow/src/features/task/handler.test.ts, packages/workflow/src/test/utils.ts
Currently we only have the name of the office as an email handlebar.  With this PR we can add the location of the office.
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/764
=> Add registration location to email as a variable

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/correction/corrector.ts, packages/client/src/i18n/messages/views/certificate.ts, packages/client/src/i18n/messages/views/correction.ts, packages/client/src/views/CorrectionForm/VerifyCorrector.tsx, packages/client/src/views/CorrectionForm/utils.ts, packages/client/src/views/PrintCertificate/VerifyCollector.tsx, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/769
=> Id verifier and collector form fix

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/views/PrintRecord/Body.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx, yarn.lock
This PR enables :
- Prevent the form from resetting when you are on the informant's details page.
- Saves changes to informant information when FIELD_AGENT is selected as the informant.
=> Opencrvs form flashes

packages/client/src/components/form/ReviewActionComponent.tsx, packages/client/src/i18n/messages/views/review.ts, packages/workflow/src/features/registration/utils.ts
Copy is here: https://github.com/opencrvs/opencrvs-farajaland/pull/778
=> Fix death reg notification and copy amend on review page

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/i18n/messages/views/selectInformant.ts, packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueCollectorForm.tsx, packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
this PR translate :
- Capacity inn death certificate
=> Opencrvs translation for field agent

packages/gateway/src/features/registration/fhir-builders.ts, packages/migration/package.json, packages/migration/src/migrations/hearth/20231123125224-deceased-birth-date.ts, packages/migration/src/utils/progressTracker.ts
=> ocrvs-6191 Use deceased death date to calculate birth

packages/client/src/views/PrintCertificate/PDFUtils.ts, packages/client/src/views/PrintCertificate/VerifyCollector.tsx, packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx, packages/components/src/Workqueue/Workqueue.tsx, packages/workflow/src/features/registration/handler.test.ts
- Fix : https://new-legacy-digital-ltd.sentry.io/issues/4703640645
- Fix : https://new-legacy-digital-ltd.sentry.io/issues/4684453308/
=> Fix error when you click in back button

packages/client/src/i18n/reducer.ts, packages/login/src/i18n/reducer.ts
=> fix issue : cannot read properties of null (reading 'label'

packages/client/src/views/RegisterForm/RegisterForm.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/899
=> ocrvs-6517 Handle absence of informant section

packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
=> Update informant info for incomplete declaration

CHANGELOG.md, packages/client/src/i18n/messages/user.ts, packages/client/src/i18n/messages/views/config.ts, packages/client/src/i18n/reducer.ts, packages/client/src/setupTests.ts, packages/client/src/tests/mock-offline-data.ts, packages/client/src/views/Settings/items/Language.tsx, packages/client/src/views/UserRoles/UserRoleManagementModal.tsx, packages/client/typings/window.d.ts, packages/login/src/App.test.tsx, packages/login/src/i18n/components/LanguageSelect.tsx, packages/login/src/i18n/reducer.ts, packages/login/src/setupTests.ts, packages/login/typings/window.d.ts
This change also removes the dependency to `AVAILABLE_LANGUAGES_SELECT` which the country config doesn't have to provide anymore
=> Remove dependency to displayName field for country config provided language

CHANGELOG.md, packages/client/graphql.schema.json, packages/client/src/i18n/messages/views/verifyCertificate.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx, packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts, packages/commons/src/fhir/transformers/index.ts, packages/gateway/src/features/registration/type-resolvers.ts, packages/workflow/src/records/handler/verify.ts, packages/workflow/src/records/state-transitions.ts
fixes #6422 where the verify certificate page crashes when gender is unknown
fixes #6614 where the verify certificate page is missing registrar information
fixes #6230 where the verify certificate page crashes on death certificate
=> fix(qr-code): page crash on verify certificate and add missing registrar information

CHANGELOG.md, packages/client/index.html, packages/client/src/components/ProtectedPage.tsx, packages/login/index.html
Approved the spinner design via JPF and also the background change from white to light grey when the application itself is loading in ProtectedPage.
=> feat: add a spinner to login & client after 2 seconds

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
fixes instance of list-review on Declaration Review page.
=> fix: review padding on mobile

package.json
Farajaland: https://github.com/opencrvs/opencrvs-farajaland/pull/955
=> Upgrade node support to versions 18.x.x

docker-compose.deps.yml
=> fix: remove renovate pinned docker deps

docker-compose.dev.yml, packages/auth/Dockerfile, packages/client/Dockerfile, packages/components/Dockerfile, packages/config/Dockerfile, packages/dashboards/Dockerfile, packages/documents/Dockerfile, packages/gateway/Dockerfile, packages/login/Dockerfile, packages/metrics/Dockerfile, packages/migration/Dockerfile, packages/notification/Dockerfile, packages/scheduler/Dockerfile, packages/search/Dockerfile, packages/user-mgnt/Dockerfile, packages/webhooks/Dockerfile, packages/workflow/Dockerfile
Too much noise, too little 'why'
=> revert: remove Dockerfile pinned sha digests

packages/auth/package.json, packages/client/package.json, packages/commons/package.json, packages/components/package.json, packages/config/package.json, packages/data-seeder/package.json, packages/documents/package.json, packages/gateway/package.json, packages/login/package.json, packages/metrics/package.json, packages/migration/package.json, packages/notification/package.json, packages/search/package.json, packages/user-mgnt/package.json, packages/webhooks/package.json, packages/workflow/package.json, yarn.lock
This makes the commit phase faster
=> refactor: move ESLint --fix run on staged files instead of every time in pre-commit

CHANGELOG.md, packages/client/src/forms/register/mappings/event-specific-fields/death/query/deceased-mappings.ts
* fix: validate date string before converting
* docs: update CHANGELOG
=> fix: validate date string before converting to LocalDate (v1.4)

CHANGELOG.md, packages/client/src/forms/register/mappings/event-specific-fields/death/query/deceased-mappings.ts
* fix: validate date string before converting
* docs: update CHANGELOG
=> fix: validate date string before converting to LocalDate (v1.3)

packages/client/package.json, packages/login/package.json, yarn.lock
Reverts opencrvs/opencrvs-core#6887
=> Revert "chore(deps): update dependency eslint-plugin-flowtype to v8"

docker-compose.yml
=> fix: add webhooks url env variable for workflow

packages/components/src/Divider/Divider.tsx, packages/components/src/Headings/Headings.tsx
- updates to padding in Headings and Dividers
=> UI Refactor: Heading and Divider

packages/client/src/components/form/DocumentUploadfield/DocumentListPreview.tsx, packages/client/src/components/form/DocumentUploadfield/DocumentPreview.tsx, packages/client/src/components/form/DocumentUploadfield/DocumentUploaderWithOption.tsx, packages/client/src/components/form/DocumentUploadfield/SimpleDocumentUploader.tsx, packages/components/src/Button/Button.styles.ts, packages/components/src/ErrorText/ErrorText.tsx, packages/components/src/Icon/all-icons.ts, packages/components/src/LocationSearch/LocationSearch.tsx, packages/components/src/Select/Select.tsx, packages/components/stories/iconography.stories.mdx
Updates document upload components:
Plus:
- Replace TrashSimple with Trash
- Removes ErrorMessage and just uses ErrorText
- add flex-shrink: 0 to Button
=> UI Refactor: Document Upload components:

packages/client/src/views/RegisterForm/RegisterForm.tsx
=> Sets declaration form bottom buttons to column direction

packages/components/src/Checkbox/Checkbox.tsx, packages/components/src/Radio/RadioButton.tsx
- applies same fix used with RadioButton
Checkbox was being selected WHEN the Select dropdown was over it AND you try to select an option
=> Fix: Checkbox being selected when Select dropdown is active

packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
=> fix(ocrvs-7068): show requester, reason, comment, id verfied sections in action modal for action CORRECTED

CHANGELOG.md, packages/commons/src/fhir/extension.ts, packages/workflow/src/records/fhir.ts
https://github.com/opencrvs/opencrvs-core/issues/7024
=> Removed duplicateTrackingId check in createDuplicateTask method

package.json, packages/components/package.json, packages/data-seeder/package.json, packages/documents/package.json, packages/gateway/package.json, packages/metrics/package.json, packages/notification/package.json, packages/search/package.json, packages/workflow/package.json, yarn.lock
This reverts commit 95bf1ee90c24e0e6b18890243b5d8ca56657b90d.
=> Revert "chore(deps): update dependency lint-staged to v15 (#6942)"

packages/client/src/views/RegisterForm/duplicate/DuplicateForm.tsx
=> fix: missing heading in mobile view for duplicate

packages/client/src/views/SysAdmin/Performance/reports/completenessRates/CompletenessDataTable.tsx
=> fix: sort not working in performance on completenessRate

packages/data-seeder/src/roles.ts, packages/data-seeder/src/users.ts
Requires: https://github.com/opencrvs/opencrvs-countryconfig/pull/165
=> Enforce token for seeding roles and users

CHANGELOG.md, packages/client/src/views/Settings/ChangeEmailModal/ChangeEmailModal.test.tsx, packages/client/src/views/Settings/ChangeEmailModal/ChangeEmailView.tsx, packages/client/src/views/Settings/ChangePhoneModal/ChangeNumberView.tsx, packages/client/src/views/Settings/ChangePhoneModal/ChangePhoneModal.test.tsx, packages/client/src/views/Settings/queries.ts, packages/gateway/src/features/user/usersAPI.ts
* fix: handle unauthorized error in gateway for no users found
* fix: handle unknown error for contact info change
* chore: amend using apollo query in changing contact info
* fix: amend error handlers
* fix: update change view tests
* chore: remove unused functions
* fix: update duplicate error state
* docs: update changelog(#7003)
=> fix: handle unauthorized error in gateway for no users found (#7025)

packages/client/src/search/advancedSearch/utils.ts
=> fix: remove extra param from adv search form state

docker-compose.yml, packages/webhooks/src/constants.ts
Checked by deploying to development environment and the error log had stopped after the deploy
=> fix: redis hostname

packages/search/src/features/records/service.ts
=> fix: fetch Documents after resolving Encounters

packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx, packages/client/src/views/SearchResult/SearchResult.tsx
=> fix: sync review button logic in adv search result

docker-compose.yml
Mistakenly merged without double checking the rebase result
=> fix duplicate env property on compose file

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
https://github.com/opencrvs/opencrvs-core/issues/7504
=> hide signature in correction request mode

packages/client/src/components/form/SignatureField/SignatureUploader.tsx, packages/client/src/forms/index.ts
Country Config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/259
=> fix: update allowing file type condition for signature

packages/client/src/components/form/FormFieldGenerator.tsx
=> fix: nested field update issue

packages/client/src/i18n/messages/views/search.ts, packages/client/src/views/AdvancedSearch/SaveBookmarkModal.tsx
countryconfig: https://github.com/opencrvs/opencrvs-countryconfig/pull/283
=> fix: hardcoded copy in advanced search input

CHANGELOG.md, packages/client/src/components/DateRangePickerForFormField.tsx
=> fix: layout issue with AdvancedSearch's edit button not properly showing on mobile view

packages/client/src/views/CorrectionForm/CorrectionSummary.tsx, packages/client/src/views/CorrectionForm/utils.ts, packages/client/src/views/PrintRecord/Body.tsx, packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/client/src/views/ReviewCorrection/ReviewCorrection.tsx
These changes are in develop but not in v1.6.0
https://github.com/opencrvs/opencrvs-core/commits/release-v1.6.0?author=tahmidrahman-dsi
https://github.com/opencrvs/opencrvs-core/commits?author=tahmidrahman-dsi
=> fix: cherry pick label params related changes

CHANGELOG.md, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
=> fix: handle label param in action details modal

package.json
Fixes users not being activated automatically on farajaland-dev.
=> fix(env-vars): do not force activate users even on prod

packages/client/src/components/Header/Header.tsx
Fixes a bug introduced in #7640 advanced search button being not dispatched, also removed some stale code.
=> fix(header): advanced search button fixed and remove unused code

packages/client/src/components/interface/Navigation.test.tsx, packages/client/src/components/interface/Navigation.tsx
Added tests to ensure any refactoring won't break the existing functionality going forward
=> (User roles)Tests for NavigationItems for new scope based access

CHANGELOG.md, packages/components/src/TextInput/TextInput.tsx
| before | after |
|----------|--------|
|![image](https://github.com/user-attachments/assets/49138b2c-5c2a-4e45-b7dc-a37a1301a03a)|![image](https://github.com/user-attachments/assets/03c7d586-4362-4637-82ce-f33b560c6f3a)|
=> fix: prefix text overlap issue

packages/client/src/components/form/FormFieldGenerator.tsx
https://github.com/user-attachments/assets/07b36541-6b94-4afb-8845-d6e7d8389f99
=> fix(ocrvs-7746): wrong address id issue

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
=> fix: hide signature for duplicate record

packages/client/src/components/ProtectedComponent.tsx, packages/client/src/views/OfficeHome/OfficeHome.test.tsx, packages/client/src/views/OfficeHome/OfficeHome.tsx, packages/client/src/views/SelectVitalEvent/SelectVitalEvent.test.tsx, packages/client/src/views/SelectVitalEvent/SelectVitalEvent.tsx
Dependent on: https://github.com/opencrvs/opencrvs-core/pull/7741
Issue: https://github.com/opencrvs/opencrvs-core/issues/7419
=> (User roles) Add scopes to control what declarations can be created

.github/workflows/build-images-from-branch.yml, CHANGELOG.md, packages/client/src/forms/register/mappings/query/field-mappings.ts, trivy.yaml
https://github.com/opencrvs/opencrvs-countryconfig/pull/305
=> fix(ocrvs-5952): `informantType` in handlebars template object 

.github/workflows/deploy-to-feature-environment.yml, .github/workflows/on-label-added-for-pr.yml, .github/workflows/trigger-e2e.yml
This is to reduce the number of PR environments deployed at once
=> Require PRs to have "🚀 Ready to deploy" label to be deployed

.github/workflows/publish-toolkit-to-npm.yml
Main branch must include action in order to run it
=> feat(toolkit): create empty action to allow testing

packages/gateway/src/features/metrics/root-resolvers.ts
Issue link: https://github.com/opencrvs/opencrvs-core/issues/7433
=> chore: add vs export scope in query

packages/client/src/declarations/utils.ts, packages/client/src/views/RecordAudit/ActionMenu.tsx
Fix of https://github.com/opencrvs/opencrvs-core/issues/8048
Based on `configurable-roles` since this branch has the updated ActionMenu works.
=> fix: update action menu options for draft declarations

.github/workflows/build-images-from-branch.yml, .github/workflows/deploy-to-feature-environment.yml
We don't really need to build images on every commit to a PR unless it has the "Ready to deploy" label
=> feat: trigger build only on deploy to feature branch

packages/gateway/src/utils/documents.ts, packages/workflow/src/documents.ts, packages/workflow/src/records/handler/certify.test.ts, packages/workflow/src/records/handler/correction/request.ts, yarn.lock
Reverts opencrvs/opencrvs-core#8170
=> Revert "🍒 Merge changes from PR #8010 to release-v1.6.2"

packages/data-seeder/src/users.ts, packages/toolkit/README.md, packages/toolkit/package.json, packages/toolkit/src/scopes/index.ts, packages/toolkit/tsconfig.json
So that they can be used in countryconfig
=> feat: export scopes via toolkit

packages/commons/src/fhir/index.ts, packages/commons/src/fhir/practitioner.ts, packages/workflow/src/features/user/utils.ts, packages/workflow/src/records/fhir.ts, packages/workflow/src/records/state-transitions.ts
This reverts commit 935d5de77e38bdf70aa19f8c360dda6ffcde6838.
=> Revert "fix: include role resources for view record"

packages/client/src/forms/advancedSearch/fieldDefinitions/Birth.ts, packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts, packages/client/src/forms/index.ts, packages/client/src/search/advancedSearch/utils.ts, packages/client/src/tests/util.tsx, packages/client/src/utils/locationUtils.ts, packages/client/src/views/OfficeHome/OfficeHome.tsx, packages/client/src/views/SearchResult/AdvancedSearch.tsx, packages/commons/src/client.ts, packages/workflow/src/features/user/utils.ts, packages/workflow/src/records/handler/view.ts, packages/workflow/src/records/state-transitions.ts
This PR is to address [this issue](https://github.com/opencrvs/opencrvs-core/issues/8169#issuecomment-2569060854)
=> fix: save additional practitioner role entry in bundle during view action

packages/client/src/App.tsx, packages/client/src/v2-events/README.md, packages/client/src/v2-events/layouts/workqueues/index.tsx, packages/client/src/v2-events/routes/config.tsx, packages/client/src/v2-events/routes/routes.ts, packages/client/typings/window.d.ts
https://github.com/opencrvs/opencrvs-countryconfig/pull/395
=> Events v2: use V2 events as default events when config.FEATURES.V2_EVENTS config variable is enabled

packages/gateway/src/features/fhir/service.ts
=> fix(ocrvs-8542): remove extra slash

packages/client/src/views/SysAdmin/Config/Systems/Systems.test.tsx, packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx
=> fix(ocrvs-8340): provide unique keys to ToggleMenu

packages/client/src/views/OfficeHome/OfficeHome.tsx
=> fix(ocrvs-8525): sentForReview pagination mapping

packages/config/src/handlers/dashboardQueries/dashboardQueries.ts, packages/config/src/handlers/dashboardQueries/defaultQueries.ts
The main change is made in the countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/399
=> fix(ocrvs-8505): sync dashboard queries from countryconfig

packages/notification/src/features/sentForUpdates/handler.ts, packages/notification/src/features/utilsForPartiallyCompletedRecord.ts
countryconfig: https://github.com/opencrvs/opencrvs-countryconfig/pull/400
=> fix(ocrvs-8568): make subject name optional for notification

packages/client/src/forms/user/fieldDefinitions/createUser.ts
=> fix(ocrvs-8444): make signature required

packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx
=> fix(ocrvs-8678): show title on mobile

packages/client/src/components/DraftLoadingSpinner.tsx, packages/client/src/views/CorrectionForm/CorrectionForm.tsx, packages/client/src/views/CorrectionForm/CorrectionSummary.tsx, packages/client/src/views/CorrectionForm/VerifyCorrector.tsx, packages/client/src/views/PrintCertificate/usePrintableCertificate.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx
=> fix(ocrvs-8582): correction flow back button

docker-compose.yml, packages/metrics/src/api.ts, packages/user-mgnt/src/config/routes.ts, packages/user-mgnt/src/environment.ts, packages/user-mgnt/src/features/countUsersByLocation/service.ts
=> fix(ocrvs-8587): stats block in performance page

packages/client/src/components/interface/Navigation.tsx
=> fix(ocrvs-8586): use primary office as the default locationId

packages/client/src/views/SysAdmin/Performance/ApplicationSourcesReport.tsx, packages/gateway/src/features/user/root-resolvers.ts
=> fix(ocrvs-8598): cater sources of registrations to scopes

packages/client/src/views/RecordAudit/ActionDetailsModal.tsx
=> fix(ocrvs-8560): show collector's name if available

packages/components/src/Dropdown/Dropdown.tsx
=> fix(ocrvs-8640): add fallback options for anchor position

packages/client/src/views/RecordAudit/ActionMenu.tsx
=> fix(ocrvs-8650): disable unassign action when offline

packages/commons/src/fhir/transformers/index.ts, packages/workflow/src/records/handler/correction/correction.test.ts, packages/workflow/test/mocks/correctBirthRecord.ts
=> fix(ocrvs-8365): handle correcting informant relationship

packages/workflow/src/records/handler/reject.ts, packages/workflow/src/server.ts
=> fix(ocrvs-8602): check flag before sending notification

packages/client/graphql.schema.json, packages/client/src/search/queries.ts, packages/client/src/utils/gateway-deprecated-do-not-use.d.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/DataProvider/marriage/queries.ts, packages/client/src/views/OfficeHome/queries.ts, packages/client/src/views/PrintCertificate/utils.ts, packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/src/views/RecordAudit/queries.ts, packages/commons/src/assignment.ts, packages/commons/src/search.ts, packages/gateway/src/features/registration/type-resolvers.ts, packages/gateway/src/features/search/schema.graphql, packages/gateway/src/features/search/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/elasticsearch/utils.ts, packages/search/src/features/registration/assignment/service.ts, packages/search/src/features/registration/birth/service.ts, packages/search/src/features/registration/death/service.ts, packages/search/src/features/registration/marriage/service.ts
=> fix(ocrvs-8516): determine assignment based on creation time

packages/client/src/forms/advancedSearch/fieldDefinitions/Death.ts
=> fix(ocrvs-8550): make location fields optional

packages/client/src/v2-events/features/events/registered-fields/Date.tsx
Date input used to require an additional character input from the user before actually accepting values
Shouldn't happen anymore
=> fix date input requiring additional click

packages/client/src/i18n/messages/workQueue.ts
https://github.com/opencrvs/opencrvs-countryconfig/pull/442
=> fix(ocrvs-8778): update translation for no drafts

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/451
=> fix(ocrvs-8270): hide upload button in correction

packages/login/src/views/ResetCredentialsForm/SecurityQuestionForm.tsx, packages/user-mgnt/src/features/verifyUser/handler.ts
=> fix(ocrvs-8434): reset credentials flow

packages/client/src/views/CorrectionForm/utils.ts
=> fix(ocrvs-8688): consider CorrectionRequested as correction

packages/client/src/hooks/useHomePage.ts, packages/client/src/views/Performance/Dashboard.tsx, packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx
=> fix(ocrvs-8586-2): set office location in all navigation

packages/client/src/utils/gateway-deprecated-do-not-use.d.ts, packages/client/src/views/OfficeHome/inProgress/InProgress.tsx, packages/client/src/views/OfficeHome/readyForReview/ReadyForReview.tsx, packages/client/src/views/OfficeHome/readyToIssue/ReadyToIssue.tsx, packages/client/src/views/OfficeHome/readyToPrint/ReadyToPrint.tsx, packages/client/src/views/OfficeHome/requiresUpdate/RequiresUpdate.tsx
=> fix(ocrvs-8516): disable workqueue actions when assigned to others

packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx, packages/commons/src/events/ActionConfig.ts
https://github.com/opencrvs/opencrvs-core/issues/8725
country config: https://github.com/opencrvs/opencrvs-countryconfig/pull/471
=> Removed CREATE from action config

CHANGELOG.md, packages/client/src/i18n/messages/validations.ts, packages/client/src/utils/constants.ts, packages/client/src/utils/validate.ts
Add the isAgeInYearsBetween validator
Linked Country-config PR:https://github.com/opencrvs/opencrvs-countryconfig/pull/439
Issue: https://github.com/opencrvs/opencrvs-core/issues/7636
=> fix: Add the isAgeInYearsBetween validator

packages/commons/src/fhir/transformers/index.ts, packages/workflow/src/records/handler/update.test.ts
=> fix(ocrvs-8615): allow deletion of attachments when updating

packages/auth/src/features/retrievalSteps/sendUserName/handler.ts, packages/notification/src/config/routes.ts
As this route is used in username retrieval, all users should be able to access this route.
=> fix(ocrvs-8434-2): remove scope check for retrieveUserName

packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts, packages/client/src/v2-events/features/events/useEvents/useEvents.ts
this fixes an issue where the hidden fields were not being stripped on the custom event actions
=> add useEventCustomAction() function, which strips the hidden fields

packages/client/src/views/RegisterForm/duplicate/DuplicateFormTabs.tsx, packages/components/src/ComparisonListView/RowView.tsx, packages/components/src/ListUser/ListUser.tsx, packages/components/src/Table/Table.tsx
=> fix(ocrvs-5350): ui issues

packages/events/src/router/middleware/validate/index.ts
Include submitted metadata fields to the data payload that gets validated against with all of the action fields
=> Events v2: include metadata fields in the payload validation

packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx, packages/client/src/v2-events/components/forms/utils.ts, packages/client/src/v2-events/features/events/actions/declare/Review.interaction.stories.tsx, packages/client/src/v2-events/features/events/actions/declare/Review.tsx, packages/client/src/v2-events/features/events/components/Review.tsx
- add function `makeFormFieldIdFormikCompatible()`
- use it on the fieldId when user changes a value from review page
- this focuses the user to correct input
https://github.com/user-attachments/assets/fb3fdcef-59b9-4e67-84fc-1f8d1add78a8
=> When clicking a 'change' link on review page, user will be focused on correct input

packages/client/src/v2-events/features/events/useCertificateTemplateSelectorFieldConfig.ts
https://github.com/opencrvs/opencrvs-countryconfig/pull/518
=> Certificate collector template label changed according to e2e

packages/gateway/src/features/registration/type-resolvers.ts
[Issue 8337](https://github.com/opencrvs/opencrvs-core/issues/8337)
=> fix (ocrvs-8337) issue about father's/mother's details not available

packages/client/src/v2-events/features/events/components/Pages.tsx
**Option A** for scrolling to top on form page change. 
Use element ID to find scrollable element.
=> scroll to top of page with element id

packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx, packages/client/src/v2-events/messages/utils.tsx
Supply workqueue title and overview title with event details
=> Events v2: Add empty token support for formatMessage

packages/client/src/extract-translations.ts
- ignore stories in translation checker
- run prettier
=> chore: ignore translations under stories

packages/client/src/v2-events/features/events/actions/print-certificate/Review.tsx, packages/client/src/v2-events/features/events/actions/print-certificate/pdfUtils.ts, packages/client/src/v2-events/hooks/usePrintableCertificate.ts
https://github.com/opencrvs/opencrvs-core/issues/8739
now it looks like this:
=> latest print action document available to certificate template while printing pdf

packages/commons/src/conditionals/conditionals.test.ts, packages/commons/src/conditionals/conditionals.ts
Country config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/581
=> chore: add matches validator for a matching regex

packages/client/src/v2-events/README.md, packages/client/src/v2-events/features/events/AdvancedSearch/AdvancedSearch.stories.tsx, packages/client/src/v2-events/features/events/AdvancedSearch/AdvancedSearch.tsx, packages/client/src/v2-events/features/events/AdvancedSearch/index.tsx, packages/client/src/v2-events/features/events/actions/delete/index.tsx, packages/client/src/v2-events/routes/config.tsx
- Update documentation regarding suspense and routes
- Check routes and ensure they match
=> chore: update suspense documentation and match components to it

packages/client/src/v2-events/features/events/actions/declare/Review.interaction.stories.tsx, packages/client/src/v2-events/features/events/actions/declare/useReviewActionConfig.tsx, packages/commons/src/events/ActionType.ts, packages/commons/src/events/test.utils.ts, packages/events/src/router/event/__snapshots__/event.actions.notify.test.ts.snap, packages/events/src/router/event/event.actions.notify.test.ts, packages/events/src/router/event/event.get.test.ts, packages/events/src/service/files/index.ts, packages/events/src/tests/utils.ts
Fixes:
- Backend crashing when reading notify actions
- Add missing incomplete configuration in declare review
https://github.com/opencrvs/opencrvs-core/issues/9059
=> Ocrvs 9059

packages/client/src/utils/locationUtils.ts
This should go some way to improving performance on the search page.
Should resolve an issue on https://github.com/opencrvs/opencrvs-core/issues/8575
=> feat: Memoize generating locations as it was causing re-renders and slowing search

packages/client/src/transformer/index.ts, packages/commons/src/fhir/transformers/index.ts, packages/workflow/src/records/handler/correction/correction.test.ts, packages/workflow/test/mocks/correctBirthRecord.ts
Cherry pick fixes for issues #7821 and #8622
=> Cherry pick fixes for issues 7821 and 8622

packages/client/src/v2-events/components/forms/FormFieldGenerator.tsx, packages/client/src/v2-events/features/events/registered-fields/Data.stories.tsx, packages/client/src/v2-events/features/events/registered-fields/Data.tsx
Issue: https://github.com/opencrvs/opencrvs-core/issues/8441#issuecomment-2789037957 (see comment)
Countryconfig: https://github.com/opencrvs/opencrvs-countryconfig/pull/618
* `FieldType.DATA` now filters out hidden fields, i.e. fields where, in the original field config, the there is a `ConditionalType.SHOW` and conditions are not met.
* Refactor data component
=> FieldType.DATA now hides hidden fields

packages/workflow/src/records/handler/correction/approve.ts, packages/workflow/src/records/handler/correction/make-correction.ts, packages/workflow/src/records/handler/correction/request.ts
Link to the GitHub issue https://github.com/opencrvs/opencrvs-core/issues/8651
=> feat: notify countryconfig on correction events

packages/client/src/utils/data-formatting.ts
Fix for: https://github.com/opencrvs/opencrvs-core/issues/6830
Seems to resolve the smoke test issue:
https://www.loom.com/share/7a17610ac2ef4823abcb8ab5934a6028?sid=7d054a18-cb75-4d4f-ae13-b98183d576b2
=> Handle undefined in getLocalisedName

packages/components/src/IDReader/readers/QRReader/QRReader.tsx
Link to the GitHub issue https://github.com/opencrvs/opencrvs-core/issues/9293
=> fix: empty error message when dialog opens

.github/workflows/deploy-to-feature-environment.yml, packages/client/src/v2-events/features/events/components/Output.stories.tsx, packages/client/src/v2-events/features/events/components/Output.tsx
https://github.com/opencrvs/opencrvs-core/issues/9295#issue-3008136470
Check existing of previous value with `previousValue !== undefined`, so it works correctly with falsy values.
=> Fix output not working correctly with falsy values

packages/client/src/v2-events/features/events/actions/declare/Review.tsx, packages/client/src/v2-events/features/events/actions/declare/useReviewActionConfig.tsx, packages/client/src/v2-events/features/events/actions/register/Review.tsx, packages/client/src/v2-events/features/events/actions/validate/Review.tsx, packages/client/src/v2-events/features/events/actions/validate/useReviewActionConfig.tsx, packages/client/src/v2-events/features/events/components/Review.stories.tsx, packages/client/src/v2-events/features/events/components/Review.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/EventSummary.tsx
https://github.com/opencrvs/opencrvs-core/issues/9059#issuecomment-2796721443
Configure icons correctly for different review action
=> Configure correct icons for review action button

packages/client/src/v2-events/components/forms/inputs/FileInput/FileInput.tsx, packages/client/src/v2-events/components/forms/inputs/FileInput/SimpleDocumentUploader.tsx
https://github.com/opencrvs/opencrvs-core/issues/9211#issuecomment-2829935780
Use given label as document preview page title
=> Use given label as document preview page title

packages/client/src/v2-events/features/events/registered-fields/DateField.tsx
=> remove eslint disable comment on datefield

packages/commons/src/events/EventConfig.ts, packages/commons/src/events/WorkqueueConfig.ts, packages/commons/src/events/defineConfig.ts, packages/commons/src/events/utils.ts, packages/commons/src/fixtures/tennis-club-membership-event.ts
=> feat: separate workqueue from event

packages/api-docs/build.sh
Creating separate spec files for Core and countryconfig
ISSUE : [#9362](https://github.com/opencrvs/opencrvs-core/issues/9362)
=> Creating seperate yml spec files for events and countryconfig

.github/workflows/init-release.yml
=> Added a workflow for initiate a release process

.github/TEMPLATES/RELEASE_PR_TEMPLATE.md
Introducing new template for release.
=> Added a new template for release

packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.tsx, packages/client/src/v2-events/features/events/actions/print-certificate/Review.tsx, packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts, packages/client/src/v2-events/features/workqueues/EventOverview/components/EventSummary.tsx, packages/client/src/v2-events/features/workqueues/Workqueue.tsx, packages/commons/src/events/state/index.ts, packages/commons/src/events/test.utils.ts, packages/commons/src/events/utils.ts, packages/events/src/router/middleware/validate/index.ts
Resolves https://github.com/opencrvs/opencrvs-core/issues/9341 comments
Countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/704
Farajaland test change PR: https://github.com/opencrvs/opencrvs-farajaland/pull/1367
* Omit hidden fields from action annotation payloads
* Correctly omit hidden verification page ids from payloads
* Add Certified status to available statuses
* Remove duplicate status translation
* Minor refactoring
=> Fix bug with certification action payload, add 'Certified' status

.github/workflows/lint-and-test.yml, packages/client/src/v2-events/features/workqueues/EventOverview/components/useActionMenuItems.ts
No github issue.
Fix chromatic workflow, the .git directory was removed from core artifact, so we need to sync the current dir to be the repo: https://opencrvsworkspace.slack.com/archives/C07NQAULENB/p1746686192883929
Navigate to front page on event deletion, instead of staying on the event overview page.
=> Navigate to front page on event deletion, fix chromatic workflow

packages/client/src/v2-events/features/events/components/Action/DeclarationAction.tsx, packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
Resolves: https://github.com/opencrvs/opencrvs-core/issues/9275#issuecomment-2853486737
If no annotation for previous action is found, we try to use notify action annotation.
=> Use notify action annotation

packages/client/src/v2-events/features/drafts/useDrafts.ts
Resolves: https://github.com/opencrvs/opencrvs-core/issues/9395
Save annotation data to draft.
https://github.com/user-attachments/assets/bb28fcfa-9a3a-4b42-acde-96f02da0d917
=> Save annotation data to draft

CHANGELOG.md, packages/client/src/components/DateRangePicker.tsx, packages/client/src/utils/validate.ts, packages/components/src/DateField/DateField.tsx, yarn.lock
[GitHub issue](https://github.com/opencrvs/opencrvs-core/issues/9247)
[Country config PR](https://github.com/opencrvs/opencrvs-countryconfig/pull/671)
In this PR, I have removed the function `isDateNotPastLimit` with its reference use and update the `onchane` function of the date to take any date
=> refactor: remove the dob limit under death declaration form

packages/client/src/i18n/messages/errors.ts, packages/client/src/views/SearchResult/AdvancedSearch.test.tsx, packages/client/src/views/SearchResult/AdvancedSearch.tsx
[Issue: #9276](https://github.com/opencrvs/opencrvs-core/issues/9276)
[Country confif PR](https://github.com/opencrvs/opencrvs-countryconfig/pull/674)
https://www.loom.com/share/e7ad03861f09455c8134dac01baa2661?sid=8abce198-f21a-4557-bfaf-31ed4967a4d6
=> Add warning/error message on search for less than one parameter

packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx, packages/commons/src/events/utils.ts
Resolves comment https://github.com/opencrvs/opencrvs-core/issues/9412#issuecomment-2875790709
=> Save drafts as ActionStatus.Accepted, use eventWithDrafts while resolving title on overview page

packages/client/src/v2-events/features/events/EventSelection.tsx, packages/client/src/v2-events/features/events/actions/declare/Pages.interaction.stories.tsx, packages/client/src/v2-events/features/events/components/Action/AnnotationAction.tsx, packages/client/src/v2-events/features/events/components/Action/DeclarationAction.tsx, packages/client/src/v2-events/layouts/form/FormHeader.tsx, packages/commons/src/events/utils.ts
Resolves: https://github.com/opencrvs/opencrvs-core/issues/9395#issuecomment-2875751181
And: https://github.com/opencrvs/opencrvs-core/issues/9395#issuecomment-2875751181
E2e tests: https://github.com/opencrvs/opencrvs-farajaland/pull/1386
Clear form and annotation data on action unmount and new event.
=> Clear form and annotation data on action unmount and new event.

CHANGELOG.md, infrastructure/nginx-default.conf, packages/client/nginx.conf, packages/login/nginx.conf
Our CSP is not restrictive enough currently, making this more strict in this PR.
ISSUE [#9584](https://github.com/opencrvs/opencrvs-core/issues/9584)
=> CSP policy is reconfigured(ocrvs-9594)

.github/workflows/build-images-from-branch.yml, .github/workflows/deploy-to-feature-environment.yml, packages/client/src/i18n/messages/views/correction.ts, packages/client/src/v2-events/features/events/AdvancedSearch/SearchResult.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx, packages/client/src/v2-events/features/events/components/Output.stories.tsx, packages/client/src/v2-events/features/events/components/Output.tsx, packages/client/src/v2-events/features/workqueues/Workqueue.interaction.stories.tsx, packages/commons/src/events/test.utils.ts, packages/components/src/ActionPageLight/ActionPageLight.tsx, packages/components/src/EventTopBar/EventTopBar.tsx
=> summary page

packages/commons/src/events/ActionType.ts, packages/commons/src/events/EventIndex.ts, packages/commons/src/events/EventMetadata.ts, packages/commons/src/events/state/index.test.ts, packages/commons/src/events/state/index.ts, packages/commons/src/events/state/utils.ts, packages/commons/src/events/test.utils.ts, packages/commons/src/users/systemRole.ts, packages/events/src/router/event/__snapshots__/event.search.test.ts.snap, packages/events/src/router/event/event.search.test.ts, packages/events/src/server.test.ts, packages/events/src/service/indexing/indexing.ts, packages/events/src/service/indexing/query.ts
Ensure updatedAt matches what is tested for.
- Redefine timestamps based on the latest accepted status change.
- Write test cases for search endpoint, fix obvious bugs
=> Ocrvs 9731

.github/workflows/build-images-from-branch.yml, .github/workflows/deploy-to-feature-environment.yml
* pr e2e deployment uses base branch as farajaland branch
* use elif
* use elif
* add if clause
* remove if
* only run security check on develop
* only run security check on main or develop
=> PR e2e deployment uses base branch as farajaland branch (#9733)

packages/client/src/i18n/messages/buttons.ts, packages/client/src/i18n/messages/views/correction.ts, packages/client/src/v2-events/features/events/actions/correct/request/Onboarding/Onboarding.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/CorrectionDetails.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx, packages/client/src/v2-events/features/events/actions/correct/request/routes.ts, packages/client/src/v2-events/features/events/registered-fields/Number.tsx
=> progress with new summary page styling

packages/client/src/v2-events/features/events/Search/SearchResult.tsx, packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
=> fix: update message in outbox

packages/client/src/v2-events/components/DownloadButton.tsx, packages/client/src/v2-events/features/events/Search/SearchResult.tsx
=> fix: Enabled download button in my draft workqueue for different browser

CHANGELOG.md
Adding item missed from CHANGELOG
=> doc: Fix release notes

packages/client/src/v2-events/features/events/Search/QuickSearchIndex.tsx
=> fix: add defeault actions on quicksearch results

CHANGELOG.md
For PR: https://github.com/opencrvs/opencrvs-core/pull/9029
=> chore(v1.8.0): update CHANGELOG.md 

packages/client/src/v2-events/features/events/useEvents/api.ts, packages/client/src/v2-events/features/events/useEvents/outbox.ts, packages/client/src/v2-events/features/users/cache.ts, packages/client/src/v2-events/hooks/useUsers.ts
=> Fix workqueues losing items temporarily & showing incorrect avatars

CHANGELOG.md, infrastructure/nginx-default.conf, packages/client/nginx.conf, packages/login/nginx.conf
=> Ocrvs 9594 b

packages/client/src/v2-events/features/events/Search/EventMetadataSearchOptions.ts, packages/commons/src/event-config/event-configuration.ts, packages/commons/src/events/event.ts
- Also removes select option configuration from eventFn
https://github.com/opencrvs/opencrvs-countryconfig/pull/881
=> [OCRVS-9702] Do not allow searching for drafts in advanced search

CHANGELOG.md, packages/client/src/forms/index.ts, packages/client/src/forms/utils.ts, packages/client/src/offline/reducer.ts, packages/client/src/tests/mock-offline-data.ts, packages/client/src/tests/util.tsx, packages/client/src/utils/validate.ts
Addresses: https://github.com/opencrvs/opencrvs-core/issues/9311
Country-Config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/880
Inactive health facilities still appear in the Place of birth / death select.
Countries can decide to use the FHIR Location API to deactivate a health facility if it has closed down. However the place of birth / death still renders a status: "inactive" health facility.
=> Ocrvs 9311

package.json, packages/auth/package.json, packages/client/package.json, packages/commons/package.json, packages/components/package.json, packages/config/package.json, packages/dashboards/package.json, packages/data-seeder/package.json, packages/documents/package.json, packages/events/package.json, packages/gateway/package.json, packages/login/package.json, packages/metrics/package.json, packages/migration/package.json, packages/notification/package.json, packages/search/package.json, packages/toolkit/package.json, packages/user-mgnt/package.json, packages/webhooks/package.json, packages/workflow/package.json
Forgot to do this on branch creation
=> Bump version to 1.7.4

packages/client/src/v2-events/features/events/Search/EventMetadataSearchOptions.ts, packages/client/src/v2-events/features/events/Search/utils.test.ts, packages/client/src/v2-events/features/events/actions/declare/Review.tsx, packages/client/src/v2-events/features/events/actions/register/Review.tsx, packages/client/src/v2-events/features/events/actions/validate/Review.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenuStories/LocalRegistrarInteraction/Rejected.stories.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenuStories/RegistrationAgentInteraction/Rejected.stories.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/useActionMenuItems.ts, packages/commons/src/events/EventMetadata.ts, packages/commons/src/events/state/availableActions.ts, packages/commons/src/events/state/flags.ts, packages/commons/src/events/state/index.ts, packages/commons/src/fixtures/forms.ts, packages/events/src/router/event/actions/index.ts, packages/events/src/router/event/event.get.test.ts, packages/events/src/router/event/index.ts, packages/events/src/service/events/events.ts, packages/events/src/service/indexing/indexing.test.ts
=> fix: remove rejected status, use flag instead

packages/client/src/v2-events/components/forms/utils.ts, packages/client/src/v2-events/features/events/Search/SearchCriteriaPanel.stories.tsx, packages/client/src/v2-events/features/events/Search/SearchCriteriaPanel.tsx, packages/client/src/v2-events/features/events/Search/SearchResultIndex.tsx, packages/client/src/v2-events/features/events/Search/TabSearch.tsx, packages/client/src/v2-events/features/events/Search/utils.test.ts, packages/client/src/v2-events/features/events/Search/utils.ts, packages/client/src/v2-events/features/events/registered-fields/Data.tsx, packages/client/src/v2-events/features/events/registered-fields/DateRangeField.tsx, packages/commons/src/event-config/event-configuration.ts, packages/commons/src/events/AdvancedSearchConfig.ts, packages/commons/src/events/FieldConfig.ts, packages/commons/src/events/event.ts, packages/events/src/router/middleware/validate/index.ts, packages/events/src/service/indexing/query.ts
Selecting date range was only working for event fields and not declaration fields
https://github.com/opencrvs/opencrvs-countryconfig/pull/901
=> fix(ocrvs-10029): date range selection for declaration fields

packages/client/src/v2-events/features/events/registered-fields/LocationSearch.stories.tsx, packages/client/src/v2-events/features/events/registered-fields/LocationSearch.tsx
=> [OCRVS-10182] Emit undefined from location search if an invalid value is given

packages/client/src/i18n/messages/views/correction.ts, packages/client/src/v2-events/features/events/actions/correct/request/CorrectionRequest.stories.tsx, packages/client/src/v2-events/features/events/actions/correct/request/ReviewCorrection.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/CorrectionDetails.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryDialog/EventHistoryDialog.stories.tsx, packages/commons/src/events/test.utils.ts, packages/commons/src/fixtures/tennis-club-membership-event.ts
Fix of this [issue](https://github.com/opencrvs/opencrvs-core/issues/9345#issuecomment-3163728325)
Fix of this [label related issue](https://github.com/opencrvs/opencrvs-core/issues/9645#issuecomment-3167724484)
Country Config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/926
=> Add "Verify ID" fields in summary page and make `Correction Request` button have full width 

packages/client/vite.config.ts, packages/commons/package.json, packages/commons/src/conditionals/conditionals.ts, packages/commons/src/conditionals/validate.ts, packages/components/package.json, packages/gateway/src/graphql/schema.d.ts, packages/login/vite.config.ts, packages/toolkit/package.json, yarn.lock
=> enable AJV caching

packages/client/vite.config.ts, packages/commons/package.json, packages/commons/src/conditionals/conditionals.ts, packages/commons/src/conditionals/validate.ts, packages/gateway/src/graphql/schema.d.ts, packages/login/vite.config.ts, packages/toolkit/package.json, yarn.lock
=> Cherry-pick AJV fix

packages/commons/src/events/AdvancedSearchConfig.ts, packages/commons/src/events/EventConfig.ts, packages/commons/src/events/field.ts, packages/commons/src/field-config/field-configuration.ts, packages/events/src/router/event/event.search.test.ts, packages/events/src/router/event/index.ts, packages/events/src/service/indexing/indexing.test.ts, packages/events/src/service/indexing/indexing.ts, packages/events/src/service/indexing/query.ts, packages/events/src/service/indexing/utils.ts
[**Country config**
](https://github.com/opencrvs/opencrvs-countryconfig/pull/930)
=> [OCRVS-10104] Make type of place of birth a part of search query

packages/client/src/v2-events/features/events/actions/print-certificate/Review.tsx
=> [OCRVS-10145] Show print certificate title on mobile device

packages/client/src/v2-events/features/events/actions/correct/utils.ts, packages/client/src/v2-events/features/events/components/Output.tsx
issue: https://github.com/opencrvs/opencrvs-core/issues/10319
Scenario:
=> Refactor hasFieldChanged for readability and correct null/undefined handling

packages/client/src/v2-events/features/events/actions/dedup/DuplicateComparison.tsx
=> fix: misc dedup comparison view fixes

packages/commons/src/events/FileUtils.test.ts, packages/commons/src/events/FileUtils.ts, packages/events/src/service/files/index.ts
=> do not delete files from requested actions

docker-compose.deps.yml
=> Switch redis image

license-config.json
=> fix: add .kube to license ignore

CHANGELOG.md, docker-compose.deps.yml
Goal of this PR is to get rid bitnami redis image
Related issue is: https://github.com/opencrvs/opencrvs-core/issues/10173
k8s tests were performed at: https://github.com/opencrvs/infrastructure/pull/98
docker swarm changes were tested on Farajaland repo: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/17830644819, PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/1019
Redis authentication was enabled:
```
(.venv) NB01NSTL012:infrastructure vmudryi$ k get secret redis-opencrvs-users redis-opencrvs-acl
NAME                   TYPE     DATA   AGE
redis-opencrvs-users   Opaque   9      64m
redis-opencrvs-acl     Opaque   2      64m
```
Secret redis-opencrvs-users copied to main namespace at deploy time:
```
(.venv) NB01NSTL012:infrastructure vmudryi$ k get secret …
```
=> fix: Switch to official redis image (#10173)

packages/client/src/v2-events/features/events/registered-fields/Http.interaction.stories.tsx, packages/client/src/v2-events/features/events/registered-fields/Http.tsx
Handle text and json response types from external api for http field
=> handle text and json response types from external api for http field
