README.md
tidyup.
line breaks.
moved logo's above description paragraph
indented paragraphs for instruction lists
moved a 'how secure is opencrvs' to after 'what is opencrvs'
contents now only shows high level sections
* tried to get the build status icons to center align. failed
=> styling updates to readme

packages/gateway/src/features/fhir/utils.ts, packages/gateway/src/features/registration/schema.graphql, packages/gateway/src/features/registration/type-resolvers.test.ts, packages/gateway/src/features/registration/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/routes/registrations/export-route.ts, packages/metrics/src/config/routes.ts, packages/metrics/src/features/getTimeLogged/constants.ts, packages/metrics/src/features/getTimeLogged/handler.test.ts, packages/metrics/src/features/getTimeLogged/handler.ts, packages/metrics/src/features/getTimeLogged/utils.ts
- Added a new end point on metrics service to get timeLogged for a given status of an application
- Added type resolver for timeLogged property under RegWorkFlow in gateway
- Adjusted birth and death export registration query to include time logged, practitioner name and role
=> [ocrvs 2682 & 2683] added timeLogged type resolver and adjusted export query

packages/workflow/src/constants.ts, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts, packages/workflow/src/features/registration/handler.ts
Resolves 3 issues.
1. This is a potential fix for https://jembiprojects.jira.com/browse/OCRVS-2590. The error occurs because FS Cache takes time to spin up for elastic search. I reckon that could happen at periods of inactivity when the server might be saving resources. The only solution I could come up with is forcing a delay into the workflow > resources > workflow loop. Perhaps there is a better way to resolve this.
2. This PR also contains a necessity for countries that do not have external validation of BRNs. Zambia BRN generation is instantaneous, so the loop from workflow > resources and back to workflow happens too fast before workflow saves the Task into hearth. So I moved the call to resources so it happens after the Task is saved. Hopefully this doesn't cause any issues but …
=> Fixes OCRVS-2590 and issue with no external validation setup

packages/client/src/i18n/messages/buttons.ts, packages/client/src/i18n/messages/views/register.ts, packages/client/src/views/RegisterForm/RegisterForm.test.tsx, packages/client/src/views/RegisterForm/RegisterForm.tsx
Modal shows up only when both of the below conditions are met
- User has `register` or `validate` scope
- `registrationStatus` is either `DECLARED` or `REJECTED`
=> Ocrvs 2371 save confirmation modal

packages/client/src/views/Performance/OperationalReport.tsx, packages/client/src/views/Performance/PerformanceContentWrapper.tsx, packages/client/src/views/Performance/reports/operational/RegistrationRatesReport.tsx, packages/client/src/views/Performance/utils.ts
Closes #1716 UI - OpsDash - page padding and filter bar
1. paddingtop = 32px
2. H2 page title - 54px
3. filterBar div = 56px. pT: 12px, pB=11px
4. Divider line = 1140px wide
5. MarginBottom = 32px
**1**
**2**
**3,4**
**5**
=> Ocrvs 1716 Operational dashboard style amends

packages/client/src/views/RegistrationHome/tabs/review/reviewTab.test.tsx, packages/client/src/views/RegistrationHome/tabs/review/reviewTab.tsx, packages/client/src/views/SearchResult/SearchResult.tsx, packages/gateway/src/features/registration/root-resolvers.test.ts, packages/gateway/src/features/registration/root-resolvers.ts, packages/search/src/elasticsearch/utils.ts, packages/search/src/features/registration/deduplicate/service.ts
fixes #1913 
Prior to this change, after calling `notADuplicate` resolver used to update hearth composition but did not update the search service. As a result, in spite of calling the resolver, the duplicate flag did not go and produce the above mentioned issue.
After this change, the duplicate flag goes after calling the `notADuplicate` resolver which keeps hearth and search service synchronized.
=> Ocrvs 1913 Fix for review duplicate issue

packages/client/src/utils/validate.test.ts, packages/client/src/utils/validate.ts
fixes #2033 
Note: In case of death, there is already a validation that shows error if the birth date of applicant is after death date. Birth date of applicant can be after birth date of the deceased and not a bug, considering the applicant is a descendant.
=> Ocrvs 2033 Fix for validation issue

packages/client/src/SubmissionController.test.ts, packages/client/src/SubmissionController.ts, packages/client/src/applications/index.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/FieldAgentHome/SentForReview.tsx, packages/client/src/views/Home/Details.tsx
This change deletes application when submitted, validated, registered, or rejected to optimize usage of indexedDB. Also, it fixes an unaddressed bug, in which a registration agent can download a validated application from details page on small devices but we restrict the user on desktop. After this change, a registration agent cannot download a validated application.
Notice the usage decrease after every submit action
=> IndexedDB usage optimization

packages/search/src/elasticsearch/utils.test.ts, packages/search/src/elasticsearch/utils.ts
Add checking and throw an error if going to create duplicate operation history in search service
This change passes all unit test cases
This change also passes all e2e tests
=> Fix for duplicate history issue

packages/notification/src/extract-translations.ts
OpenCRVS core is set up to use [ISO 639-1 language codes](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) like this:
English = "en"
In December 2020 we configured OpenCRVS to optionally use a CMS like [Contentful](https://www.contentful.com/).
Contentful is set up to use an ISO 639-1 language code followed by a hyphen then an [Alpha-2 country code](https://www.iban.com/country-codes) like this:
U.S. English = "en-US"
When writing the import process to Contentful, we temporarily changed the language codes in the fallback langauge JSON files to the COntentful style and forgot to change it back.  This caused a bug where languages were not loading properly.  
This change in core is to resolve the check for new language keys and is not a breaking change.
=> Change language code used for extract translations

packages/client/src/components/DateRangePicker.tsx
Fixed incorrect statistics data showing on **performance operational** tab while use custom date picker.
=> [ocrvs-2202] Incorrect statistics on performance data

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/index.ts, packages/components/src/components/forms/InputField/InputField.tsx, packages/components/src/components/forms/TextInput.tsx
weight at birth input field fixed to 78px and padding and label fixed
=> ocrvs-2129 weight at birth input field fixed to 78px and padding and label fixed

packages/client/src/views/SysAdmin/Team/user/UserList.tsx, packages/components/src/components/fonts.ts
newfont created, pill fontStyle changed as 12px semibold, padding: 4px 8px, border-radius: 2px
=> ocrvs-1963: newfont created, pill fontStyle changed as 12px semibold, padding: 4px 8px, border-radius: 2px

packages/client/src/utils/validate.ts, packages/client/typings/window.d.ts
=> ocrvs-1908 NID validation moved from core to contry-wise config

package.json
Commons must be built before other modules when running yarn dev.  Otherwise Mac will not generate Typescript files in time and cannot start up
=> Commons build issue

packages/client/src/components/interface/DownloadButton.tsx
=> ocrvs-1962: hover and active state on download button made circle same as expand button.

packages/client/src/views/SysAdmin/Performance/NoResultMessage.tsx, packages/client/src/views/SysAdmin/Performance/Report.tsx
- The main problem in this issue was that `props.history.location`, which is mutable, was used instead of `props.location` which in turn affected the react life-cycle hooks.
- There might other places where this issue might be present so this should be taken into consideration.
=> ocrvs-2308 Fixed back button not working

packages/login/src/i18n/locales/bn.ts, packages/login/src/i18n/locales/en.ts, packages/login/src/views/resetCredentialsForm/resetCredentialsForm.ts
The other field is now required in {select} format messages. Adding it thus fixed the issue.
=> ocrvs-2316 Added the required other field in {select} format messages

packages/client/src/i18n/messages/constants.ts
=> ocrvs-1936: time period represented using '-'

package.json, yarn.lock
Restricted the version of react-error-overlay which introduced
some bugs due to conflicting dependencies. More on this can be
found here:
https://github.com/facebook/create-react-app/issues/11773
The resolution for babel-loader was required because otherwise
it needed to be resolved manually when genereting the lock file.
=> Fix the react-error-overlay not showing up and hot reload

packages/gateway/package.json
Make sure schema and types are generated before the server starts and not rewritten while the server is reading the files. I also reorganised the scripts a little
=> Make sure schema and types are generated before the server starts

packages/gateway/src/features/registration/death-fhir-builders.test.ts, packages/gateway/src/features/registration/fhir-builders.test.ts, packages/gateway/src/features/registration/fhir-builders.ts, packages/gateway/src/features/transformation/index.ts, packages/gateway/src/features/user/root-resolvers.test.ts, packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap, packages/metrics/src/features/registration/index.ts, packages/metrics/src/features/registration/pointGenerator.test.ts, packages/metrics/src/features/registration/pointGenerator.ts, packages/workflow/package.json, packages/workflow/src/features/registration/fhir/fhir-bundle-modifier.ts, packages/workflow/src/index.ts
* allow setting declarations 'created at' value from outside
this is needed so mass data generator can create declarations retrospectively
* remove console.log from component file
* fix linting error
* fix broken tests
* fix other tests that were not being run properly
* use fhir data also for influxdb creation timestamps
* update tests
=> Allow setting declarations 'created at' value from outside (#2537)

packages/metrics/src/features/registration/pointGenerator.ts, packages/metrics/src/features/registration/utils.test.ts, packages/metrics/src/features/registration/utils.ts
Without this, all births sent with a creation date more than 45 days ago (think data generator) would be registered as late declarations
=> [OCRVS-2522] Make age calculation functions use composition date, not current timestamp

.github/workflows/build-images-from-branch.yml
I realised I cannot build images locally as I'm on ARM architecture 🤦  something like this would be often useful
=> Add workflow to publish Docker images from any branch

packages/client/src/i18n/messages/views/review.ts, packages/client/src/tests/languages.json, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
- removes the messaging "Check responses with the informant before sending for review" and "Review the answers with the supporting documents"
- these reminders should be handle in dialog prompt onClick of register and send for review
- unable to test as there is a bug when navigating to Review page
=> removes messaging at top of Review Section

docker-compose.deploy.yml, infrastructure/monitoring/apm/apm-server.yml, infrastructure/monitoring/beats/metricbeat.yml, infrastructure/monitoring/beats/rollover-policy.json, infrastructure/server-setup-checklist.md
By default, both Application Performance Monitoring (APM) and Metricbeat store data for 30 days. This functionality is something called a "rollover policy". As we don't need to store data for that long, this PR changes those defaults to 7 days instead. This configuration happens automatically on install, and no manual config is required.
=> Setup 7 day data retentions for Metricbeat and APM

deploy.sh, docker-compose.deploy.yml, infrastructure/clear-all-data.sh, infrastructure/elasticsearch/elasticsearch.yml, infrastructure/elasticsearch/roles/kibana_user.json, infrastructure/elasticsearch/roles/search_user.json, infrastructure/elasticsearch/setup-helpers.sh, infrastructure/elasticsearch/setup-users.sh, infrastructure/emergency-backup-metadata.sh, infrastructure/emergency-restore-metadata.sh, infrastructure/mongodb/on-deploy.sh, infrastructure/monitoring/apm/apm-server.yml, infrastructure/monitoring/beats/metricbeat.yml, infrastructure/monitoring/kibana/alert-rules.json, infrastructure/monitoring/kibana/setup-alerts.js, infrastructure/server-setup/README.md, infrastructure/server-setup/playbook-1.yml, infrastructure/server-setup/playbook-3.yml, infrastructure/server-setup/playbook-5.yml, infrastructure/setup-deploy-config.sh
This PR secures our data in Elasticsearch, making it writable to only one user, whose password is rotated on every deployment
Other additions:
- Super user account for Elasticsearch with credentials stored in 1password
- It would be better to have dynamic credentials for this, but our current way of backups makes this a little difficult
- Predefined user accounts with automatically rotating passwords
- applications using ElasticSearch (`search`)
- for internal tools like Metricbeat, APM...
- Kibana user that uses actual ElasticSearch authentication mechanism and whose access rights are explicitly defined
=> [OCRVS-2807] Setup basic credentials and authentication for ElasticSearch and applications using it

packages/gateway/src/features/metrics/root-resolvers.ts, packages/gateway/src/features/metrics/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/metrics/src/config/routes.ts, packages/metrics/src/features/payments/handler.ts, packages/metrics/src/features/payments/service.ts, packages/metrics/src/features/registration/__snapshots__/handler.test.ts.snap, packages/metrics/src/features/registration/fhirUtils.ts, packages/metrics/src/features/registration/handler.test.ts, packages/metrics/src/features/registration/handler.ts, packages/metrics/src/features/registration/index.ts, packages/metrics/src/features/registration/pointGenerator.test.ts, packages/metrics/src/features/registration/pointGenerator.ts, packages/metrics/src/influxdb/client.ts
Querying
```graphql
query data($event: String!, $timeStart: String!, $timeEnd: String!, $locationId: String!) {
getTotalPayments(
timeStart: $timeStart
timeEnd: $timeEnd
locationId: $locationId
event: $event
) {
total
paymentType
}
}
```
should give you the following data
```
{
"data": {
"getTotalPayments": [
{
"total": 3792,
"paymentType": "certification"
},
{
"total": 5283,
"paymentType": "correction"
}
]
}
}
```
=> [OCRVS-2886] Add payments resolver

.github/workflows/lint-and-test.yml
This action causes unit tests to depend on the country config PR.  Core unit tests should be independent
=> Remove extract translations from git actions

packages/client/src/components/form/FormFieldGenerator.tsx
=> [OCRVS-2997] Fix input errors not being shown / persisted correctly

packages/components/src/components/forms/InputField/InputField.tsx, packages/components/src/components/forms/TextInput.tsx
- removes max-width on Input field. That cause ui issues with radio buttons. 
- sets width of text input to 344px
=> removes max-width on fields

deploy.sh, packages/client/graphql.schema.json, packages/client/src/user/queries.ts, packages/client/src/utils/gateway.ts, packages/gateway/src/features/registration/root-resolvers.test.ts, packages/gateway/src/features/user/type-resolvers.test.ts, packages/gateway/src/features/user/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql
I tried writing a test for this, but there's just so many FHIR requests being made in type resolvers, that I gave up
=> [OCRVS-3148] Hide registrar signature from field agents

package.json, packages/client/src/views/SysAdmin/Performance/ApplicationSourcesReport.tsx, packages/metrics/src/features/registration/fhirUtils.ts
I noticed Health Systems source showing 0 as the number of declarations
Taking a closer look in the data, it seems we get `AUTOMATED` to InfluxDB
=> use AUTOMATED as the source name for Health System notifications

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
=> ocrvs-2971 Fixed 'no' appearing instead of '-'

packages/client/src/i18n/messages/views/review.ts
=> ocrvs-3363: default message added for registerConfirmationTitle

packages/client/src/views/OfficeHome/inProgress/InProgress.tsx, packages/client/src/views/OfficeHome/inProgress/inProgress.test.tsx, packages/client/src/views/RecordAudit/RecordAudit.test.tsx, packages/client/src/views/RecordAudit/RecordAudit.tsx
Opening the record audit of a declaration from any page > 1 does a
refetch of the workqueue for the first page thus replacing the
workqueue data for the selected record.
=> [hotfix]Queried for declaration info as a fallback

packages/client/src/views/SysAdmin/Performance/WorkflowStatus.tsx
=> ocrvs-2544-fix: column alignmnt set to left on workflow status

packages/gateway/src/features/search/root-resolvers.ts, packages/gateway/src/features/search/schema.graphql, packages/gateway/src/features/search/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/features/search/types.ts, packages/search/src/features/search/utils.ts
Our query builder logic wasn't handling multiple location ids properly, which caused issues in districts with multiple CRVS offices. This change makes the query with multiple location ids into an OR statement
=> Fix multi-location-id queries not finding anything

.vscode/settings.json, infrastructure/license-config.json, packages/client/src/components/formConfig/formTools/CustomFieldTools.tsx, packages/client/src/components/interface/Header/Header.tsx, packages/components/.storybook/main.ts, packages/components/.storybook/manager.ts, packages/components/.storybook/preview.tsx, packages/components/package.json, packages/components/src/components/buttons/CircleButton.tsx, packages/components/src/components/buttons/DangerButton.tsx, packages/components/src/components/buttons/FloatingActionButton.tsx, packages/components/src/components/buttons/IconButton.tsx, packages/components/src/components/buttons/LinkButton.tsx, packages/components/src/components/buttons/PrimaryButton.tsx, packages/components/src/components/buttons/SecondaryButton.tsx, packages/components/src/components/buttons/SuccessButton.tsx, packages/components/src/components/buttons/Toggle.tsx, packages/components/src/components/colors.ts, packages/components/src/components/fonts.ts, packages/components/src/components/forms/Select.tsx, packages/components/src/components/interface/ExpandableNotification/ExpandableNotification.tsx, packages/components/src/components/interface/InvertSpinner.tsx, packages/components/src/components/select/Select.tsx, packages/components/src/stories/colors.stories.mdx, packages/components/src/stories/typography.stories.mdx, yarn.lock
Closes #3775
Closes #3752 
* `indigoDark` -> `primaryDark`
* `redDark` -> `negativeDark` 
* `greenDark` -> `positiveDark`
* ^ autogenerate dark shades for primary, negative, positive and teal. This is to help support theming in the future.
* Create documentation for colors and typography
* Installs `polished` for `lighten` / `darken` functions. **Question:** do we want to install a new dependency for this or to create our own functions? `polished` should support tree-shaking but [Bundlephobia](https://bundlephobia.com/package/polished@4.2.2) says that every export is the same size 🤔
=> Auto-generate shades in colour palette & document Colors and Typography in Storybook

packages/components/src/components/buttons/Action.stories.tsx, packages/components/src/components/buttons/ArrowExpansionButton.stories.tsx, packages/components/src/components/buttons/ExpansionButton.stories.tsx, packages/components/src/components/buttons/IconButton.stories.tsx, packages/components/src/components/charts/Bar.stories.tsx, packages/components/src/components/charts/Legend.stories.tsx, packages/components/src/components/interface/ActionPage.stories.tsx, packages/components/src/components/interface/Banner.stories.tsx, packages/components/src/components/interface/Chip.stories.tsx, packages/components/src/components/interface/DataTable/DataTable.stories.tsx, packages/components/src/components/interface/DataTable/Pagination.stories.tsx, packages/components/src/components/interface/DataTable/SortAndFilter.stories.tsx, packages/components/src/components/interface/ExpandableNotification/ExpandableNotification.stories.tsx, packages/components/src/components/interface/HamburgerMenu.stories.tsx, packages/components/src/components/interface/InvertSpinner.stories.tsx, packages/components/src/components/interface/ListItem.stories.tsx, packages/components/src/components/interface/ListItemExpansion.stories.tsx, packages/components/src/components/interface/Modal.stories.tsx, packages/components/src/components/interface/ResultList.stories.tsx, packages/components/src/components/interface/SectionDrawer.stories.tsx, packages/components/src/components/interface/SelectGroup.stories.tsx, packages/components/src/components/interface/SubPage.stories.tsx, packages/components/src/components/interface/TopBar.stories.tsx, packages/components/src/components/interface/ViewData/DataRow.stories.tsx, packages/components/src/components/interface/ViewData/DataSection.stories.tsx, packages/components/src/components/interface/ViewData/LabelValuePair.stories.tsx
Moves for example `ActionButton (deprecated)` into a section called `Deprecated`, to make the Storybook look nicer.
=> Move deprecated components to their own section

packages/client/src/components/ProtectedPage.tsx
On some devices, it might take so long to read data from the storage that the timeout for a minimum time of showing the main loader finishes before reading from storage does. This caused the app to stay in a state where the loader is shown infinitely.
=> Fix app main loader spinning infinitely

packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.test.tsx, packages/client/src/views/SysAdmin/Config/Forms/Home/PreviewTab.tsx, packages/config/src/handlers/formDraft/updateFormDraft/handler.test.ts, packages/config/src/handlers/formDraft/updateFormDraft/handler.ts
I have changed the logic for the default form config. If the draft version is **0** then the national sys admin can publish the default form config, but if the national sys admin already make a form draft and the draft version increased from 0 then they have to move the form draft to in preview first for published. Otherwise, the publish button will be disabled.
=> ocrvs-3788 Fixed default form not published issue

packages/gateway/package.json
Gateway was failing to start because of the missing dependency
=> Added the missing peer dependency(fp-ts) of io-ts in gateway

packages/client/package.json
@euanmillar Disabling this temporarily until we amend this script to support esnext features.
=> Disable generate-test-forms from precommit

packages/client/src/views/SysAdmin/Config/Application/Components.tsx, packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/NIDNumPattern.tsx, packages/client/src/views/SysAdmin/Config/Application/Tabs/GeneralProperties/PhoneNumPattern.tsx, packages/components/src/Text/Text.stories.tsx, packages/components/src/Text/Text.tsx
Closes #4056 
* Implements `overflowWrap` to `Text`
* Changes regex Texts to overflow anywhere
---
=> OCRVS-4056 Fix application config regex overflow

packages/client/src/forms/index.ts, packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
1. GIVEN I am a DCR (Registrar) or Registrar (Reg Agent), and I am reviewing a submitted application in which the signature block has been used, WHEN I make an edit to the application, THEN the previously used signature block should still be present on the review page. I am then able to leave the existing signature or delete and upload a new one, as required.
2. GIVEN I am a DCR (Registrar) or Registrar (Reg Agent), and I am reviewing a submitted application in which the signature block has NOT been used (because the B1 form has been attached), WHEN I make an edit to the application, THEN the signature block should not appear or be required.
=> Fix the signature requirements only for draft and IN_PROGRESS changes

docker-compose.deploy.yml
MINIO_SERVER_URL had to be accessible internally using the name of the service in docker-compose otherwise minio-console cant resolve the server through Traefik.
=> MINIO_SERVER_URL must be internal for minio-console to work

packages/components/src/LocationSearch/LocationSearch.tsx, packages/components/src/SearchTool/SearchTool.tsx, packages/components/src/ToggleMenu/ToggleMenu.tsx
Closes #4644
Adding the `useCapture` -flag fixes the issue:
**useCapture:**
A boolean value indicating whether events of this type will be dispatched to the registered listener before being dispatched to any EventTarget beneath it in the DOM tree. Events that are bubbling upward through the tree will not trigger a listener designated to use capture. Event bubbling and capturing are two ways of propagating events that occur in an element that is nested within another element, when both elements have registered a handle for that event. The event propagation mode determines the order in which elements receive the event. See [DOM Level 3 Events](https://www.w3.org/TR/DOM-Level-3-Events/#event-flow) and [JavaScript Event order](https://www.quirksmode.org/js/events_order.html#link4) for a …
=> fix(client): on click menus now open the menu again

packages/client/.gitignore, packages/client/src/views/UserAudit/UserAudit.tsx
In this PR, we remove the vertical dot menu for users with the local_system_admin role.
Before 
After
=> Fix navigate the organisation

dev.sh
Two new totally optional command line parameters for yarn dev
`--only-dependencies` - Starts docker-compose
`--only-services`  - Starts all microservices
These allow the user to run OpenCRVS in two separate terminal windows. 
This way the user can shutdown only the services if needed while getting better terminal output when debugging
=> Implement more advanced yarn dev experience

docker-compose.deploy.yml, packages/client/graphql.schema.json, packages/client/src/utils/gateway.ts, packages/gateway/src/features/systems/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/user-mgnt/src/constants.ts, packages/user-mgnt/src/utils/system.ts
To test this, I have just added these to `dev.sh`:
```
export NATIONAL_ID_OIDP_CLIENT_ID="xyz"
export NATIONAL_ID_OIDP_BASE_URL="http://test/foo"
export NATIONAL_ID_OIDP_ESSENTIAL_CLAIMS="first_name,last_name"
export NATIONAL_ID_OIDP_VOLUNTARY_CLAIMS="testi"
```
=> feat(national-id-verification): Pass OIDP claims to frontend

packages/client/src/views/OIDPVerificationCallback/OIDPVerificationCallback.tsx, packages/client/src/views/OIDPVerificationCallback/utils.ts
Amends OIDP Verification Callback
- checks the ?state= query parameter for a JSON string like: { pathname: "/path/somewhere" }
- checks that the &nonce= parameter matches the one in localStorage, removes it if yes, throws if not
- redirects to the pathname in state
=> feat(national-id-verification): check nonce in verification callback

packages/client/src/declarations/index.ts, packages/config/src/models/config.ts
For the birth spec, an unhandled exception is thrown in case of a field agent that causes the entire test to fail. This should be fixed when https://github.com/opencrvs/opencrvs-core/pull/4778 is merged with develop. 
For advanced search spec, the child's exact date of birth date is disabled (not sure why) and that blocks further input typing, consequently causing the test to fail. 
Some amends are also done in https://github.com/opencrvs/opencrvs-farajaland/pull/506
=> Fix e2e tests

packages/client/src/utils/apolloClient.ts
apollo-cache-persist was failing to initialize after deploying without this change
=> Change importing * to module

packages/workflow/src/features/events/handler.ts
This was a bug introduced when merging the marriage feature into develop
=> Remove duplicate check if not a new entry

packages/components/src/Link/Link.tsx
- Reduces text-underline-offset to 2px. So when Link element is a button. The underline shows properly.
- Before it would cut off leaving less than 1px underline if bold14 and no underline if bold12
=> fix underline with links

packages/dashboards/update-database.sh
The existing `command -v` did not work for my machine:
```
opencrvs-core git:(dashboard-demo-data) lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
This updates the script to use "which" which seems to work on my machine.
=> fix(metabase): update-database script 'envsubst' -check for Ubuntu

packages/migration/migrations/user-mgnt/20221229110512-modify-user-roleAndtype-fieldName.js
Now if you run migrations against an empty database, the migration I've edited creates default system roles for you automatically. Previously an exception got thrown if "roles" collection did not exist before migrations were run. 
This change enables us to:
- Guide migrations to a direction where they can be used for preparing a valid database state from an empty database
- Allows implementing countries to first migrate and only then add any seed data via populate scripts
- For our use: this is a key enabler for us to populate custom user roles
=> [OCRVS-4967] Enable running migrations against a completely empty database

packages/client/src/forms/configuration/default/marriage.ts
Farajaland: https://github.com/opencrvs/opencrvs-farajaland/pull/538
=> Fixed spelling of 'two' for 2nd witness while declaring marriage records

packages/client/src/utils/referenceApi.ts
This fixes an initialization issue on a first OpenCRVS load:
Our scenario:
- We’ve customized districtPrimary  field (or rather, we have a field that has it as its precedingFieldId)
- We started noticing the error in the screenshot. This happens randomly which has made debugging even more difficult
- After a long time of reading the code I traced it here. ADMIN_LEVELS seems to be undefined
- Looking at the config endpoint, ADMIN_LEVELS  is returned correctly
More details in the code comment
=> HOTFIX: Address fields exception

packages/gateway/src/features/bookmarkAdvancedSearch/schema.graphql, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/features/search/types.ts, packages/search/src/features/search/utils.ts
Allows RecordSearch API clients to search using the QR code value
=> feat(search): allow searching with record/composition/declaration id

packages/migration/migrate-mongo-config-performance.js
This fixes migrations using 'ANALYTICS_MONGO_URL' which doesn't exist, and it caused some migrations to fail
=> fix: performance mongo url in migrations

packages/client/src/views/RecordAudit/History.tsx, packages/client/src/views/UserAudit/UserAuditHistory.tsx
- fixes spacing on history label
=> fix: history label in record audit

packages/migration/utils/marriage-certificate-template-default.js
(fixes #5168) updated marriage certificate template svg to show groom and bride name in different lines.
=> fixes #5168 : overflow in marriage certicate for long name

packages/client/src/views/RegisterForm/RegisterForm.tsx
Witness one & witness two both had the same group id which caused the key to stay the same even after changing the form page
=> ocrvs-5280 Use both section & group id for form key

packages/client/src/views/PrintCertificate/PDFUtils.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
This PR contains the fix for displaying the labels of the sub-sections in the review page and it also contains the addition of a new helper for capitalising translated information
=> Add declarant label for a better reading for record audit page

packages/client/src/i18n/messages/constants.ts, packages/client/src/views/Performance/RegistrationsList.test.tsx, packages/client/src/views/Performance/RegistrationsList.tsx, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx, packages/client/src/views/RecordAudit/DeclarationInfo.tsx, packages/client/src/views/RecordAudit/History.tsx, packages/client/src/views/RegisterForm/review/SignatureGenerator.tsx
fixes #5476 
[farajaland pr](https://github.com/opencrvs/opencrvs-farajaland/pull/581)
=> 5476: fixed missing french traslations

packages/user-mgnt/src/model/user.ts
We use [UUID](https://github.com/opencrvs/opencrvs-core/blob/b2127fddd42eff4ac88d93ed530ae2ab610bc0b1/packages/user-mgnt/src/features/userSearchRecord/handler.ts#L109) to create a new search object for a user so having an index for it is not required
=> Remove unique prop from user's searches schema

packages/client/src/forms/user/fieldDefinitions/createUser.ts
GIVEN that I am creating a new user with type Local Leader or Field Agent, THEN it should not be mandatory to add Organisation type and Organisation fields.
EXPECTED BEHAVIOUR: Only Health Worker should have the option to add Organisation Type and Organisation.
=> GN-025 : Account creation

infrastructure/nginx-default.conf
I have tested this on staging and it works.
https://csp-evaluator.withgoogle.com/
**Before:**
**After:**
=> fix(pentest): remove unsafe inline CSP

infrastructure/nginx-default.conf
I have tested this on staging and it works.
before:
```
➜  ~ curl -I -L https://login.farajaland-staging.opencrvs.org/ | grep server
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0  1887    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
server: nginx/1.25.1
```
after:
```
➜  ~ curl -I -L https://login.farajaland-staging.opencrvs.org/ | grep server
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0  1887    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
server: nginx
```
=> fix(pentest): remove nginx version from being exposed

packages/client/src/forms/configuration/default/death.ts, packages/client/src/forms/register/fieldMappings/birth/query/registration-mappings.ts, packages/client/src/views/PrintCertificate/PDFUtils.ts
This PR contains:
- a handlebar for text concatenation
- the addition of a template (SVG) to have the gender value in the death certificate
- Add a plainInputTransformerSection function to get the untranslated values of the various fields for SVGs.
=> GN-034 French translation of the nationalities must be in the feminine form. 

packages/client/src/user/userReducer.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserForm.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
When modifying a user's details, this Pr enables the confirmation button to be activated and deactivated if no changes have been made.
=> GN-035 : the 'Confirm' button should be inactive until any change

packages/metrics/src/features/registration/fhirUtils.test.ts, packages/metrics/src/features/registration/fhirUtils.ts, packages/metrics/src/features/registration/pointGenerator.ts
**If we understood this issue correctly, what happens is:**
- Registration agent creates a record (thus first task type for the event is now `VALIDATED`)
- Record may or may not go through other tasks
- Someone else marks the record voided
- Metrics tries to log this event with the record initiator with the assumption that `DECLARED` was the first state for the record = field agent started it
**Our proposed fix:**
Also consider `VALIDATED` as a starting state for a record
https://new-legacy-digital-ltd.sentry.io/organizations/new-legacy-digital-ltd/issues/4233583642/events/684ba7cbdd814284a66a4570ef3c0068/
=> Sentry : Error POST /events/birth/mark-voided in metric

packages/data-seeder/src/certificates.ts, packages/data-seeder/src/constants.ts, packages/data-seeder/src/index.ts, packages/data-seeder/src/locations.ts, packages/data-seeder/src/roles.ts, packages/data-seeder/src/users.ts
I didnt really see the need for the additional variable: GATEWAY_GQL_HOST when we already have GATEWAY_HOST.
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/680
=> Rename seed vars, deprecate old secrets

packages/migration/package.json
Getting this bug:
```
ERROR: Could not migrate up 20230602090436-update-identifier-with-system.js: Cannot find package 'mongoose' imported from /usr/src/app/packages/migration/build/dist/src/migrations/hearth/20230602090436-update-identifier-with-system.js Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'mongoose' imported from /usr/src/app/packages/migration/build/dist/src/migrations/hearth/20230602090436-update-identifier-with-system.js
```
=> Mongoose package required in migration service

packages/gateway/src/features/search/root-resolvers.ts, packages/gateway/src/features/search/schema.graphql, packages/gateway/src/features/search/utils.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/features/search/service.ts, packages/search/src/features/search/types.ts
https://github.com/opencrvs/opencrvs-core/issues/5837
Allows inputting multiple fields to event search so that DCI API can support multiple sorted fields. This is backwards compatible with sort / sortColumn -style of sorting.
=> allow sorting searchEvents by multiple fields

docker-compose.deps.yml, packages/client/src/components/form/FormFieldGenerator.tsx
We wanted to include a link to in one of our form pages and found this to be possible just by using the paragraph input type. It should be completely safe to render the HTML as it's coming from the country config and is defined by the SIs.
```
fields: [
{
name: 'supportingDocs',
type: 'PARAGRAPH',
label: {
defaultMessage:
'Click {link} to print page 2 of the Municipal Form No. 102 (supporting docs)',
values: {
link: '<a target="_blank" href="https://drive.google.com/file/d/1XWPVW2zQ6X1fL93-RE1plaXZVpVS_Wh3/view">here</a>'
},
description: 'Supporting documents link text',
id: 'form.section.documents.birth.supportingDocsLinkText'
},
initialValue: '',
validator: [],
conditionals: []
},
```
=> Allow HTML elements to be used in PARAGRAPH type form fields

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/index.ts, packages/client/src/forms/utils.ts, packages/client/src/views/CorrectionForm/utils.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
In Cameroon, for child's place of birth we only show fields for
- Municipality
- Locality
And no "Country". For us this means that in Record audit, Place of birth we were only able to show `<Municipality>, `. This hidden input allows us to include new values to the form data without showing the field in review or in the form. I'm pretty sure it's useful for others as well
=> Add a new field type 'HIDDEN' for hard coded values

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/forms/utils.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx
This PR corrects the display of the ID document label according to the select option of the ID type and also allows the FIELD_AGENT option to be removed from the choice of informantType when the user is REGISTRATION_AGENT.
=> Remove FIELD_AGENT as informantType options when user is REGISTRATION

packages/commons/tsconfig.json, packages/components/tsconfig.json
We mostly try to go to the actual source files for these two packages. Prior one for the type defintions and later for the source component files
=> Turn `declarationMap` on for commons and components package

packages/client/src/forms/utils.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx
This PR can be used to upload a user's signature by forcing the scenario in which the validate button is activated.
=> Opencrvs confirm button remains inactive

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/handlebarHelpers.ts, packages/client/src/forms/utils.ts, packages/client/src/offline/actions.ts, packages/client/src/offline/reducer.ts, packages/client/src/setupTests.ts, packages/client/src/utils/referenceApi.ts, packages/client/src/views/PrintCertificate/PDFUtils.ts, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx, packages/config/src/handlers/forms/validation.ts, packages/login/src/common/LoginBackgroundWrapper.tsx, packages/login/src/login/selectors.ts
Allow country config to have configurable handlebar [helpers](https://handlebarsjs.com/guide/expressions.html#helpers)
Requires: https://github.com/opencrvs/opencrvs-farajaland/pull/763
=> OCRVS 6085: Configurable handlebar helpers

setup.sh
google-chrome is for client not for server. Then no need to check.
If we install OpenCRVS into Terminal Server that hasn't GUI interface, so no google-chrome for viewing then the installation will not run.
=> Update setup.sh remove of google-chrome

packages/client/src/forms/handlebarHelpers.ts, packages/client/src/setupTests.ts, packages/client/src/utils/referenceApi.ts, packages/client/src/views/PrintCertificate/PDFUtils.ts
Example usage in country config would now be 
```ts
import * as Handlebars from 'handlebars'
import { type IntlShape } from 'react-intl'
type HelperProps = { intl: IntlShape }
export function myIntlHelper({ intl }: HelperProps): Handlebars.HelperDelegate {
return function (this: any, args: string[]) {
const idParts = args.slice(0, -1)
if (idParts.some((part) => part === undefined)) {
return ''
}
const id = idParts.join('.')
return intl.formatMessage({
id,
defaultMessage: 'Missing translation for ' + id
})
}
}
```
=> Add support for passing intl and other context variables to custom handlebar helpers

packages/search/src/features/records/service.ts
Fixes download failing on develop due to `Unresolved reference found: Location/foo Make sure to add a join to getFHIRBundleWithRecordID query so that all resources of the records are returned Resource: Bundle`
=> fix: don't resolve Patient.address.extension

packages/client/src/views/PrintCertificate/ReviewCertificateAction.tsx, packages/client/src/views/PrintCertificate/utils.ts
When in the Print in Advance flow, core now exposes a new handlebar "printInAdvance" with a boolean value, which country implementations can check in their certificates to hide particulars fields from showing up in it. For example, registrar's name/signature can be conditionally hidden in the certificates for print in advance using this handlebar.
N.B. Currently farajaland repo is not using this new handlebar
=> ocrvs-6126 Introduce a new handlebar "printInAdvance"

packages/migration/src/migrations/user-mgnt/20231106130956-email-mobile-unique-index.ts, packages/user-mgnt/src/model/user.ts
When creating a user user-mgnt was not checking for uniqueness for emailForNotification without an index.
Also if mobile was not a required field, you couldnt submit it empty without the sparse:true flag and an index forcing users to enter in a mobile number regardless.
Tested in seeding and in the UI
=> OCRVS-6022:  Allow null values for user mobile and emailForNotification when creating users but still check for uniqueness

packages/client/graphql.schema.json, packages/client/src/forms/utils.ts, packages/client/src/tests/schema.graphql, packages/client/src/transformer/index.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/client/src/views/DataProvider/marriage/queries.ts, packages/client/src/views/RecordAudit/ActionDetailsModal.tsx, packages/client/src/views/ReviewCorrection/ReviewCorrection.tsx, packages/client/src/views/ViewRecord/query.ts, packages/gateway/src/features/registration/schema.graphql, packages/gateway/src/features/registration/type-resolvers.ts, packages/gateway/src/graphql/common.graphql, packages/gateway/src/graphql/config.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/search/src/elasticsearch/utils.ts, packages/workflow/src/records/correction-request.ts, packages/workflow/src/records/fhir.ts
We noticed a bug happening when user requested a correction with non-string fields. When the changes eventually got applied, an "age" field for instance would have a string value that caused gateway type validations to fail.
PR implements a generic value field in GraphQA so that correction can describe different fields without having to cast to string
=> Fix input field Number when correcting a declaration (#6180)

packages/client/src/navigation/index.ts, packages/client/src/views/PrintRecord/Body.tsx, packages/client/src/views/PrintRecord/PrintRecord.tsx
This PR remove blank space after header when we want to print declaration (CTRL + P) and also open new tab when you click "print declaration".
=> Print declaration : remove blank space after header (CTRL + P) and open in new tab

packages/client/src/i18n/messages/user.ts, packages/client/src/i18n/messages/views/userSetup.ts, packages/client/src/tests/languages.json, packages/client/src/views/Settings/PasswordChangeModal.tsx, packages/client/src/views/UserSetup/CreatePassword.tsx, packages/login/src/i18n/messages/views/resetCredentialsForm.ts, packages/login/src/views/resetCredentialsForm/updatePasswordForm.tsx
Increases the security of a password change, by increasing it to 12 characters.
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/867
=> update password copy to suggest a 12 character long passphrase

.github/workflows/build-images-from-branch.yml, .github/workflows/lint-and-test.yml, .github/workflows/publish-release.yml, .trivyignore.yaml, packages/auth/Dockerfile, packages/client/Dockerfile, packages/components/Dockerfile, packages/config/Dockerfile, packages/config/src/handlers/forms/validation.ts, packages/dashboards/Dockerfile, packages/documents/Dockerfile, packages/gateway/Dockerfile, packages/login/Dockerfile, packages/metrics/Dockerfile, packages/migration/Dockerfile, packages/notification/Dockerfile, packages/scheduler/Dockerfile, packages/search/Dockerfile, packages/user-mgnt/Dockerfile, packages/webhooks/Dockerfile, packages/workflow/Dockerfile, trivy.yaml
Add [trivy](https://trivy.dev) to be able to:
- Check packages for known vulnerabilities
- Check for any potential misconfigurations in configs
- Check that licenses are properly matching
Runs both in CI and CD - idea being that CD runs it agains the build images and CI just for the repo.
Theres a `.trivyignore.yaml` for tuning findings. Currently couple HIGH and one CRITICAL but none of them seem too applicable to our use case.
Example from [build pipeline](https://github.com/opencrvs/opencrvs-core/actions/runs/7800090618/job/21272357025)
Also:
- Use `node` user where we can (to make `trivy` happy about it but its also a nice security practice)
- Pull latest OS packages with `apt-get upgrade` or equivalent during builds
=> Add and configure Trivy for security scans

packages/client/src/views/RecordAudit/RecordAudit.tsx, packages/client/src/workqueue/reducer.ts
1. When we first download multiple declarations, we enqueue the declarations for being downloaded and create `declaration.data = {}` in the state. Then when the `UPDATE_REGISTRAR_WORKQUEUE_SUCCESS` is dispatched, we were checking `hasStatusChanged` & `isNotSubmitting`. And since the `declaration.data` is empty the `hasStatusChanged` function compares `undefined !== workqueueDeclarationStatus`. Thus it finds that the status of the declaration has changed. So here, now we check `isNotSubmittingOrDownloading`.
2. When we reinstate a declaration it is not removed from the declarationState. Thus it stays assigned after the reinstating action is complete. And since we compare the workqueue data's status with the status of the declaration in store, we get a scenario like, `ARCHIVED !== …
=> Unassign fix

packages/workflow/src/records/fhir.ts
We use `status` and `encounter` of task for the correction flow. So for new task creation, we keep the previous ones.
=> [State Transitions] Fix task creation taking previous status and encounter into account

.trivyignore.yaml
Ignores the Metabase vulnerability errors until we upgrade to v0.49 where they will be fixed. 
https://github.com/opencrvs/opencrvs-core/actions/runs/8265986110/job/22613148216
Trivy has passed here
=> fix(security): ignore metabase vulnerability errors until v0.49

packages/components/src/Button/Button.styles.ts, packages/components/src/Button/Button.tsx
Testing cherry-picking commits from form-elements branch. 
This PR adds a fullWidth prop to Button. So we can do things like so in the futue:
=> comp: Adds full width options to Button

packages/notification/src/features/email/service..ts
Due to recent notification schema changes in Farajaland as part of mass email PR, the existing calls to the notification endpoint were responding 400. So, in the farajaland PR https://github.com/opencrvs/opencrvs-farajaland/pull/976 the schema is reverted back to the previous one and this core change is applied to comply with the reverted schema.
=> [HOTFIX] Implementation changes due schema changes

.github/workflows/build-images-from-branch.yml, .github/workflows/cd-manual-e2e.yml, .github/workflows/create-backup-data-action.yml, .github/workflows/lint-and-test.yml, .github/workflows/publish-release.yml, .github/workflows/reset-env-action.yml, .github/workflows/trigger-e2e.yml
First step of https://github.com/opencrvs/opencrvs-core/issues/6519
- Upgrade all versions of containers to latest LTS (22.04)
- Lock the version to ^^ so we dont float and all runs are predictable
No breakage expected, especially since many places already got on 22.04 due to latest
=> Upgrade all actions to Ubuntu 22.04 and lock the version

packages/config/src/config/constants.ts, packages/config/src/handlers/locations/hierarchy.ts
The base in URL doesn't support pathname so had to resolve the URL manually.
=> fix: remove trailing slash from FHIR_URL

packages/dashboards/run-dev.sh
Fixes Metabase local environment start script from exiting before saving changes to SQL file
[Closes: #6926]
=> fix: #6926 - Metabase local environment start script 

packages/components/src/Radio/RadioButton.tsx, packages/components/src/Radio/RadioGroup.tsx
1. Sets z-index to 1 instead of 2. 
Fixed the issue with select above the Urban/Rural radioButtons. When a use selected an option that was above the radiobuttons. Then the radio button would trigger. Setting z-index to 1. Fixed this issue
2. Input width overflowing...
minor updates to styling to checked state. removes yellow border
=> Fix: RadioButton z-index and input width

.trivyignore.yaml
tested running trivy for v0.49 and the error isn't there anymore
=> chore: ignore metabase vulnerability

.trivyignore.yaml, packages/client/src/views/RegisterForm/RegisterForm.tsx, packages/client/src/views/SysAdmin/Team/user/UserList.tsx
Ensure the currentPageNumber is reset to 1 whenever the location parameter changes to avoid issues where no data is found and the table and pagination components disappear.
=> Fix: Reset pagination to page 1 when location changes

CHANGELOG.md, packages/client/src/forms/register/mappings/event-specific-fields/marriage/query/event-mappings.ts
Updated logic to use `isValidPlainDate` function to check date values, ensuring that null or invalid date values do not cause issues. This change allows the retrieval of incomplete marriage declarations even when the date of marriage is missing.
=> Fix Check for valid date to handle incomplete marriage declarations

packages/gateway/package.json
eslint ignores the "files" path provided in the config if it's run on an individual file. Therefore, when lint-staged pipes the grapql files to the eslint command it returns an error.
=> fix: only run prettier for staged graphql files

packages/config/src/services/hearth.ts
If locations were updated or the database was cleared, the services might memoize locations incorrectly.
Remove the memoize from fetchLocations. It's a pre-mature optimization, as we haven't faced performance issues before adding this.
=> fix: memoization causing cache invalidation issues with locations

packages/search/src/features/records/service.ts
The MongoDB aggregate query's maximum size is 16 MB. The aggregate within it grows too large as the $lookup joins the full DocumentReference -collection to it. This happens if `resourceIds` is empty, as $lookup considers it to be a subset of everything and joins everything to it.
Don't allow `resourceIds` to be empty, add a placeholder value if it is.
=> fix: mongo aggregate query hitting the memory limit

.trivyignore.yaml
Why do we have it?
```
info Has been hoisted to "braces"
info Reasons this module exists
- "workspace-aggregator-1bc5bc23-ff24-435a-bd4c-0e2022fe4ae6" depends on it
- Hoisted from "_project_#micromatch#braces"
- Hoisted from "_project_#@opencrvs#login#msw#chokidar#braces"
info Disk size without dependencies: "80KB"
info Disk size with unique dependencies: "104KB"
info Disk size with transitive dependencies: "244KB"
info Number of shared dependencies: 4
=> Found "lint-staged#braces@2.3.2"
info Reasons this module exists
- "_project_#lint-staged#micromatch" depends on it
- Hoisted from "_project_#lint-staged#micromatch#braces"
info Disk size without dependencies: "120KB"
info Disk size with unique dependencies: "1.47MB"
info Disk size with transitive dependencies: "3.98MB"
info Number of …
```
=> chore: ignore braces vulnerability issue

renovate.json
- Add `":semanticCommits"` preset to Renovate's `extends` array [^1]
We want Renovate to _always_ use Semantic Commits style:
- https://github.com/renovatebot/renovate/discussions/29676
If in the future, you want Renovate to automatically detect Semantic Commits, you can change the line to `:semanticCommitsDisabled`
[^1]: [Renovate docs, manually enabling or disabling semantic commits](https://docs.renovatebot.com/semantic-commits/#manually-enabling-or-disabling-semantic-commits)
=> chore: force Renovate to use Semantic Commits

.trivyignore.yaml
```
➜  client git:(ignore-trivy-again) yarn why ws
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "ws"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "@types/react@18.3.1" is incompatible with requested version "@types/react@^16"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ws@8.13.0"
info Has been hoisted to "ws"
info Reasons this module exists
- "workspace-aggregator-28f9bf1d-42ec-4629-bbea-390756f234dd" depends on it
- Hoisted from "_project_#@opencrvs#client#@graphql-codegen#cli#@graphql-tools#url-loader#@graphql-tools#executor-graphql-ws#ws"
- Hoisted from "_project_#@opencrvs#client#@graphql-codegen#cli#@graphql-tools#url-loader#@graphql-tools#executor-legacy-ws#ws"
info Disk size without dependencies: "180KB"
info Disk …
```
=> chore: handle `ws` security error

CHANGELOG.md, packages/client/src/App.tsx, packages/client/src/components/interface/Navigation.test.tsx, packages/client/src/components/interface/Navigation.tsx
https://github.com/opencrvs/opencrvs-core/issues/6975
Deprecated items in Admin UI that can now be configured directly from the country configuration. This helps us maintain the configuration options. Due to our experience in country installations, we've noticed that the functional configuration needs technical knowledge, which is required anyway when configuring forms in country configuration. 
Note that this pull request doesn't remove the stale code left behind of these views. Some parts of the application like advanced search depend on some of the admin UI code, so it's being done in a separate PR https://github.com/opencrvs/opencrvs-core/issues/7156
=> chore: deprecate admin UI menu items

.trivyignore.yaml
```
➜  client git:(ignore-trivy-again) yarn why ws
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "ws"...?
[2/4] 🚚  Initialising dependency graph...
warning Resolution field "@types/react@18.3.1" is incompatible with requested version "@types/react@^16"
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "ws@8.13.0"
info Has been hoisted to "ws"
info Reasons this module exists
- "workspace-aggregator-28f9bf1d-42ec-4629-bbea-390756f234dd" depends on it
- Hoisted from "_project_#@opencrvs#client#@graphql-codegen#cli#@graphql-tools#url-loader#@graphql-tools#executor-graphql-ws#ws"
- Hoisted from "_project_#@opencrvs#client#@graphql-codegen#cli#@graphql-tools#url-loader#@graphql-tools#executor-legacy-ws#ws"
info Disk size without dependencies: "180KB"
info Disk …
```
=> chore(v1.5.0): handle `ws` security error

packages/client/src/i18n/messages/views/verifyCertificate.ts, packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx, packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts
Farajaland PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/150
=> fix: amend date of certification for verifying certificate

docker-compose.ci.yml, docker-compose.demo-deps.yml, docker-compose.deps.yml, docker-compose.dev-deps.yml, docker-compose.dev.yml, docker-compose.yml
This is to fix the following error in deployments
```
Updating docker swarm stack with new compose files
version mismatched between two composefiles : 3.12 and 3.3
error Command failed with exit code 1.
```
=> Explicitly define 3.3 as compose file versions

packages/migration/package.json, packages/migration/run-migrations.sh, packages/migration/src/migrations/hearth/20240527130750-reindex-elasticsearch.ts, packages/migration/src/reindex-search.ts, packages/migration/src/utils/elasticsearch-helper.ts, packages/migration/src/utils/reindex-search.ts, packages/search/src/config/routes.ts, packages/search/src/features/reindex/handler.ts, packages/search/src/features/reindex/reindex.ts, yarn.lock
#7240
* reindexes ElasticSearch always after running migrations. 
* auto-generates the index timestamp when reindexing
* `tsx`. Node.js enhanced with esbuild to run TypeScript & ESM files. I had issues running `ts-node` within migrations and `tsx` was a drop-in replacement.
=> feat: reindex elasticsearch after running migrations

packages/gateway/src/features/user/root-resolvers.ts
Due to QA [running into the rate limit](https://github.com/opencrvs/opencrvs-core/issues/5930) with the team page, we can increase the limit from 10 to 20. It should still be quite slow for brute-forcing attacks, although it allows a bit more flexibility for `a.mweene` `b.mweene` `c.mweene` ... `k.mweene` types of brute-force attacks where the attacker might already know something about the user.
Bruteforce attacks in general should be fairly well mitigated though, as they need a JWT, and VPN access.
=> fix: increase rate limit on team searches

packages/components/.storybook/main.ts, packages/components/package.json, packages/components/src/Button/Button.stories.mdx, packages/components/src/Divider/Divider.stories.tsx, packages/components/src/SideNavigation/LeftNavigation.stories.tsx, packages/components/stories/colors.stories.mdx, packages/components/stories/iconography.stories.mdx, packages/components/stories/intro.stories.mdx, packages/components/stories/releases.stories.mdx, packages/components/stories/typography.stories.mdx, yarn.lock
* updates Storybook changelog for 1.5.0
* fixes the bug why it wasn't running
* removes remark-gfm as an unused dependency
I looked through all the pages in Storybook after removing remark-gfm and didn't get errors nor did the pages look weird.
=> fix: storybook

packages/search/src/features/search/service.test.ts, packages/search/src/features/search/service.ts
When we have no records in ElasticSearch, first load of the application always give an error to console:
```
[10:38:11.030] ERROR: ElasticSearch: bad request. Error: search_phase_execution_exception: [query_shard_exception] Reason: No mapping found for [dateOfDeclaration] in order to sort on
```
As it's an non-issue and gets fixed when first declaration is made, it should be ignored from console. ElasticSearch offers a "unmapped_type", which maps the field to any type we want if it doesn't exist. I set it to "keyword" as it's the default we use in the search fields. I amended the search request to include that, unless the advanced `sortBy` is used.
=> fix: bad requests in elastic search when there is no mapping

packages/client/src/utils/gateway.ts, packages/client/src/views/VerifyCertificate/VerifyCertificatePage.tsx, packages/client/src/views/VerifyCertificate/useVerificationRecordDetails.ts
#7064
* adds `date` to the death history query
* run generate-gateway-types
* tie the view types into the queried types to have stricter type-safety
=> fix: date of certification not being visible on death

infrastructure/nginx-default.conf
#7303
Content policy didn't allow fetching fonts from country config. I added the wildcard to the fonts as well and deployed this to farajaland-dev. Seems to be working there.
=> fix: allow fonts from country config

packages/client/src/declarations/index.ts, packages/client/src/views/AdvancedSearch/AdvancedSearchResult.tsx
[#6118](https://github.com/opencrvs/opencrvs-core/issues/6118)
I noticed the refetch queries were a bit random compared to the ones actually being searched. I updated them to match each other. After this deployment, I couldn't reproduce the unassignment issue on development. 
As I couldn't reproduce this locally, but only on farajaland-dev, I think it could be worth deploying this to QA and trying it.
=> fix: advanced search refetch queries not matching the searched ones

docker-compose.ci.yml, docker-compose.demo-deps.yml, docker-compose.deps.yml, docker-compose.dev-deps.yml, docker-compose.dev.yml, docker-compose.yml
Current compose V2 spec (yes, its very confusing how we are at V2 vs previously 3.x versions..) deprecated and removed usage of `version`. 
Even though this is still accepted as value its
- Validated to match (which can cause issue in cases of mismatch)
- Throwing warnings due to deprecation
Combination means it does nothing but potentially causes issues :)
See more details here https://docs.docker.com/compose/intro/history/
and explicit note about `version` in the spec here https://github.com/compose-spec/compose-spec/blob/master/04-version-and-name.md
=> Remove deprecated version from compose files

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/index.ts, packages/client/src/tests/forms.json, packages/client/src/views/SysAdmin/Config/Systems/Systems.tsx, packages/components/src/TextInput/TextInput.tsx
We removed the usage of the deprecated `inputFieldWidth` field from countryconfig here: https://github.com/opencrvs/opencrvs-countryconfig/pull/201
This PR deprecates them core entirely
=> chore!: remove deprecated inputFieldWidth

.github/workflows/build-images-from-branch.yml, packages/Dockerfile.base, packages/auth/Dockerfile, packages/client/Dockerfile, packages/components/Dockerfile, packages/config/Dockerfile, packages/documents/Dockerfile, packages/gateway/Dockerfile, packages/login/Dockerfile, packages/metrics/Dockerfile, packages/migration/Dockerfile, packages/notification/Dockerfile, packages/search/Dockerfile, packages/user-mgnt/Dockerfile, packages/webhooks/Dockerfile, packages/workflow/Dockerfile
- Upgrade to `docker/build-push-action` to v6 to get summaries ( see more at https://github.com/docker/build-push-action/releases )
- Bring back caching based on current branch (could also potentially test later multi source caching with eg. always develop in addition)
- Change `VERSION` used for this purpose to `BRANCH` to avoid overlap in existing usage
=> Restore docker branch caching

CHANGELOG.md, packages/client/src/App.tsx, packages/client/src/components/interface/Navigation.test.tsx, packages/client/src/components/interface/Navigation.tsx, packages/client/src/views/SysAdmin/Config/Certificates/Certificates.test.tsx, packages/client/src/views/SysAdmin/Config/Certificates/Certificates.tsx
I removed both the `preview` & `print` options from the action menu
Also removed the short description in the certificates page as it contained a broken link to documentation
=> fix: bring back certificate & notification config

package.json, yarn.lock
specific version `@4.2.5` is used through 
```
└─┬ @opencrvs/metrics@1.5.0 -> ./packages/metrics
└─┬ mongodb@4.17.2
└─┬ @aws-sdk/credential-providers@3.433.0
└─┬ @aws-sdk/client-sts@3.433.0
└── fast-xml-parser@4.2.5
```
Which in our case should not be a problem since we are not using aws. Other dependencies accept ^4.x.x
=> fix(vulnerability): resolve fast-xml-parser to 4.4.1

.github/workflows/auto-pr-to-release.yml
Same changes as https://github.com/opencrvs/opencrvs-countryconfig/pull/217
Issue:
1. When the PR bot was successful, the first commit got removed due `cherry-pick` behaviour.  In `git cherry-pick h4shba..h4ashb` left side is exclusive. It differs from what `git log` shows with corresponding range syntax.
2. The commands provided by PR had the same behaviour. From a quick look there has not been many manual "Merge changes from PR" fixes that utilise the provided syntax. People tend to fix it by other means.
3. When referring to commit range, it can exists in multiple branches. Picking from `develop`
yields different result than the feature branch.
Changes:
1. Include first commit to cherry-pick range
2. Print out commits to PR body when automatic cherry-pick fails.
Sample PR: …
=> Include first commit to range, render commits to body

.github/workflows/auto-pr-to-release.yml
See initial discussion: https://github.com/opencrvs/opencrvs-core/pull/7397
Problems:
1. When feature branch includes merge commits (e.g. someone merges develop in to keep branch up-to-date) automation will fail
2. It's not completely safe to ignore the merge commits if they happen to include some meaningful changes for the release (Hopefully we can ignore this?)
3. If one includes merge commits the resulting set will end up with unrelated commits (https://github.com/opencrvs/opencrvs-core/compare/auto-pr-release-v1.6.0-7344-10229-test vs https://github.com/opencrvs/opencrvs-core/pull/7394)
Initial suggestions:
- In order for this to work we should either a) knowingly ignore the merges b) enforce rebasing of develop on feature branches
- If we go with a) we might not want to use ranges …
=> Get cherry picked commits based on git log results against base sha

CHANGELOG.md, packages/client/src/components/DateRangePickerForFormField.tsx, packages/components/src/Checkbox/Checkbox.tsx
The logic for toggling between range and exact date was not working as
expected, and the CheckBox's label was overlapping over the 'edit' link
https://github.com/opencrvs/opencrvs-core/issues/7417
=> fix: date range edit not being clickable in advanced search

packages/client/src/utils/date-formatting.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/Performance/RegistrationsList.test.tsx, packages/client/src/views/Performance/RegistrationsList.tsx, packages/metrics/src/features/totalMetrics/handler.ts
https://github.com/orgs/opencrvs/projects/4/views/2?pane=issue&itemId=74602069
What happens:
Depending on language and browser settings the registration list view might crash when given english date inputs e.g. ('July 2024')
How it was fixed:
Use the epoch time property from the same payload.
- Improve types and split code
=> fix(registration-list): use time property instead of date for safer date format generation

CHANGELOG.md, packages/commons/src/fhir/patient.ts, packages/notification/src/features/utils.ts, packages/notification/src/features/utilsForPartiallyCompletedRecord.ts
https://github.com/opencrvs/opencrvs-core/blob/4ee08fbab548b0c3f191406d57f7222d63ebd713/packages/commons/src/fhir/patient.ts#L42-L45
With this type we are basically saying that family (i.e. "lastName") will always be there. And although we also mentioned this on our form definitions here: https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/src/form/birth/index.ts#L189 but Uganda doesn't want that and have made it to be an optional field.
Anyway we also say that the "firstName" is a required field but our types don't really reflect that tbh (as I mentioned above we've only made "family" field to be a required field but not the "given" (i.e. firstName) field).
Now when I'm trying to register a declaration in Uganda without providing lastName for informant, this line throws an …
=> fix: keep `family` field as optional

CHANGELOG.md, packages/workflow/src/records/fhir.ts, packages/workflow/src/records/handler/create.ts
The event location information was missing in the bundle that gets sent to ElasticSearch fot newly created declarations, this caused Advanced Search not to work when searching by event location
https://github.com/opencrvs/opencrvs-core/issues/7494
=> fix: add the missing location details to a newly created declaration which was causing advanced search to break

CHANGELOG.md, packages/commons/src/fhir/practitioner.ts, packages/gateway/src/features/registration/type-resolvers.test.ts, packages/gateway/src/features/registration/type-resolvers.ts, packages/gateway/src/features/registration/utils.ts
=> fix: correct user role not showing if role is updated

CHANGELOG.md, packages/workflow/src/records/handler/create.test.ts, packages/workflow/src/records/handler/create.ts
The logic to check if a bundle contains the require location resource
was incorrect, it's fixed now by checking that all the encounter locations
exist a resources in the bundle
https://github.com/opencrvs/opencrvs-core/issues/7494
=> fix: Refactor bundleIncludesLocationResources() function logic to properly check if location resources are included in a bundle

CHANGELOG.md, packages/workflow/src/features/registration/sms-notification-utils.ts, packages/workflow/src/records/notification.ts
Country Config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/274
=> chore: get informant notification from country config

packages/migration/src/migrations/hearth/20240919155854-change-practitioner-family-name-from-array-to-string.ts
Issue:
1. At least on versions 1.2 - 1.2.1 `Practitioner.name[elem].family` used to be `string[]`
2. At some stage, probably during 2023,  value changed to `string`
3. Mismatch created issues during data indexing.
Solution:
Create migration to map the value to string.
=> fix(practitioner): migrate Practitioner.name.family to unified type

packages/workflow/src/records/fhir.ts
Revert "fix: include `UNASSIGNED_EXTENSION_URL` in the extension list of correctedTask"
This reverts commit dd2a7638b03cee51ef81b950601fc5fb26c2d2c1.
=> fix: exclude `UNASSIGNED_EXTENSION_URL` from the extension list of correctedTask

CHANGELOG.md, packages/commons/src/fhir/location.ts, packages/commons/src/fhir/transformers/fhir-builders.test.ts, packages/commons/src/fhir/transformers/utils.ts
Cause of issue:
When a correction to a birth or death record was made from HEALTH_FACILITY to another type, instead of creating a new location, the original facility resource was edited. 
This changed the type to PRIVATE_HOME or OTHER so when the facility dropdown is populated, the value is filtered out as it is no longer a HEALTH_FACILITY.
fixes: https://github.com/opencrvs/opencrvs-core/issues/7528
=> fix(v1.7.0): Modify location builder so it does not edit health facilities

.github/workflows/trigger-e2e-environment.yml
Splits the E2E action into two steps to allow outputting step summary after the trigger-e2e step. This step summary has a link to the E2E environment to debug so it's useful to have it visible.
=> chore(e2e): output step summary after triggering

packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Before          |  After
:-------------------------:|:-------------------------:
=> fix: label param in required error messages

packages/notification/src/features/sentForUpdates/handler.ts, packages/notification/src/features/utils.ts
birth/death rejection notification requires a name in notification payload
https://github.com/opencrvs/opencrvs-countryconfig/blob/release-v1.6.0/src/translations/notification.csv#L6
=> fix: notification content

packages/migration/src/migrations/hearth/20220822085901-rejected-declarations-started-by.ts, packages/migration/src/migrations/hearth/20221017133354-restore-supporting-document.ts, packages/migration/src/migrations/hearth/20221031131452-add_practioner_id_event_registrations.ts, packages/migration/src/migrations/hearth/20221110092434-add_identifiers_DOB_gender_location.ts, packages/migration/src/migrations/hearth/20221128065238-migrate-documents-to-minio.ts, packages/migration/src/migrations/hearth/20230127063226-update-practitioner-role.ts, packages/migration/src/migrations/hearth/20230221105416-create-performance-views.ts, packages/migration/src/migrations/hearth/20230328065851-change-certified-status-to-issused.ts, packages/migration/src/migrations/hearth/20230602120944-populate-valid-locationid.ts, packages/migration/src/migrations/hearth/20231123125224-deceased-birth-date.ts, packages/search/src/features/reindex/reindex.ts
Issue:
When running migrations, we assume arrays always contain at least one item. This results to failure during the process.
Fix:
Introduce conditional checks to remaining files, even if they might work without 99% of the time.
____
Issue:
Reindexing throws an error when single document fails to be indexed to elasticsearch.
Most likely the implicit schema that gets created prevents some of the items being added.
Fix:
Allow elasticsearch to drop the documents but keep track of them.
=> fix(migration): introduce conditionality and continue indexing on failure

CHANGELOG.md, packages/client/src/views/RegisterForm/review/ReviewSection.test.tsx, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
Missing address lines which were not required showed up as empty, making the UI look a little messy.
Fixes https://github.com/opencrvs/opencrvs-core/issues/5192
=> fix(v1.7.0): Improvement to only show items with values in review

packages/config/src/handlers/forms/formsHandler.ts
There was an extra `/` in the url that was being hit when running in dev mode.
=> fix: use URL constructor to build the url

.husky/pre-commit, .trivyignore.yaml, CHANGELOG.md, license-config.json, package.json, packages/auth/package.json, packages/client/package.json, packages/commons/package.json, packages/components/package.json, packages/config/package.json, packages/data-seeder/package.json, packages/documents/package.json, packages/gateway/package.json, packages/login/package.json, packages/metrics/package.json, packages/migration/package.json, packages/notification/package.json, packages/search/package.json, packages/user-mgnt/package.json, packages/webhooks/package.json, packages/workflow/package.json, yarn.lock
Run `yarn` to install the updated dependencies
The hooks path needs to be set to the `.husky` folder using:
```
git config --local core.hooksPath .husky/
```
Check if it's been set properly using:
```
git config core.hooksPath
```
The above command should return ".husky/"
Add a random comment to a ts/tsx file, e.g. `/packages/client/src/App.tsx`
Then stage the changes & try to commit:
```
git add /packages/client/src/App.tsx
git commit
```
If you see an output similar to this:
```
❯ packages/client/package.json — 1 file
❯ src/**/*.{ts,tsx} — 1 file
✔ prettier --write
✔ eslint --fix
✔ stylelint
```
Then congratulations, the precommit hook is running perfectly :smiley: 
Now if you see "Can't find Husky, skipping pre-commit hook" when trying to commit  run these commands:
```
rm -rf …
```
=> feat: run lint-staged by itself without lerna

packages/client/src/components/form/Button.tsx
For some reason if the http endpoint is not working, then the user may want to enter value into another input for a manual intervention. But in that case the fetch button should not be mandatory and should not block submission of the record. Thus as a workaround, a solution can be applied where there would be two fetch buttons with same appearance, one of them is required, the other one is not. When there is an error, the required one can be kept hidden and the optional one is shown disabled. But prior to this change the latter button was not touched. This change make all triggers that point to the same http request touched on request resolved.
https://github.com/user-attachments/assets/2bd44d36-750f-48dd-a455-b85bd8d7e2e6
=> fix: make all triggers of a specific http request touched on request change

CHANGELOG.md, packages/gateway/src/rate-limit.test.ts, packages/gateway/src/rate-limit.ts
With this payload to `/auth/authenticate`
```
{ username: 'test.user', password: 'test' }
```
the cached rate-limiting key was `username:/auth/authenticate`.
It's supposed to be `test.user:/auth/authenticate`.
=> fix(rate-limit): use the value of an object key, instead of the key itself

packages/search/src/features/search/handler.test.ts, packages/search/src/features/search/handler.ts
* fix: include all child location in `getStatusWiseRegistrationCountHandler`
* fix: unit test
* refactor: include children location directly to matchRules
* fix: use terms for matchRule
* fix: test: remove one http response
* chore: remove comment
=> fix: include all child location in `getStatusWiseRegistrationCountHandler` (#7917)

.github/workflows/publish-release.yml
Bring the same changes to production releases as we did for lower env builds in https://github.com/opencrvs/opencrvs-core/pull/6919
=> Hotfix builds by matching them to branch builds

docker-compose.yml, packages/auth/src/tests/util.ts, packages/client/src/App.tsx, packages/client/src/views/PrintCertificate/usePrintableCertificate.ts, packages/client/src/views/SearchResult/SearchResult.tsx
Farajaland PR: https://github.com/opencrvs/opencrvs-farajaland/pull/1165
=> (User roles) fix: update mock url object of auth

packages/components/src/Headings/Headings.tsx, yarn.lock
[This change](https://github.com/opencrvs/opencrvs-core/pull/6991/files) made the space above heading 3 and the border too tight compared to other components.
Before:
When upgrading Niue and Uganda, it became clear so this change makes the space similar to other components:
After:
For comparison with other components:
=> Fix spacing of Heading3

packages/client/src/v2-events/.eslintrc.js, packages/client/src/v2-events/features/debug/debug.tsx
- Allow arrow functions inside functions.
- Prevent using string literals within components
=> fix: improve linting in client/events

packages/client/src/views/RegisterForm/DeclarationForm.test.tsx
A single flaky test `packages/client/src/views/RegisterForm/DeclarationForm.test.tsx` passed locally but not on CI. I added a `waitForElement` to make sure the element gets rendered before counting the children.
=> fix: a failing test on client's DeclarationForm

packages/events/src/service/indexing/indexing.test.ts, packages/events/src/service/indexing/indexing.ts, packages/events/src/storage/__mocks__/elasticsearch.ts, packages/events/src/storage/elasticsearch.ts, packages/events/src/tests/global-setup.ts, packages/events/src/tests/setup.ts, packages/events/tsconfig.json
make es only start up once in the beginning of events tests, use a new index for all test cases
=> Events V2: Fix for how fake ES is set up

packages/data-seeder/src/locations.ts
events service is not setup in all environment combinations. Only log the error instead of throwing since the service is not required yet.
=> fix: log error instead of throwing for v2 events

packages/events/src/index.ts
If events configuration cannot be fetched from events service, crash the service. In development mode, instruct nodemon to restart after a 3 second delay
=> Events v2: restart events service automatically

packages/client/src/forms/register/mappings/query/field-mappings.ts, packages/client/src/forms/utils.ts
Dynamic selects are the only ones causing performance issues so only memoizing them reduces the regression risk
=> chore: Refactor to only memoize for dynamic selects

CHANGELOG.md, packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/forms/utils.ts
When we added the ability to create a 6th location level, we noticed that the address select performance in the Uganda configuration made using the form sluggish.
This issue was previously encountered in an old Cameroon project where selects had many thousands of values.  Pyry fixed it partially in the Cameroon project but a minor tweak is required to complete the job.  This PR solves the performance problem and should be cherry-picked into the 1.6.3 release branch.  Uganda will go live with a githash (unofficial tagged hotifix) from that branch and if any issues are found in UAT, then we will upgrade from the same branch so as not to impact on core timelines for general UAT on the hotfix release.
Basically the FormSectionComponent renders very slowly but it's not due to the …
=> fix: slow render of location options

packages/commons/src/fixtures/tennis-club-membership-event.ts, packages/events/src/router/event/__snapshots__/event.actions.validate.test.ts.snap, packages/events/src/router/event/event.actions.validate.test.ts, packages/events/src/service/config/config.ts
Change business rules to allow action definition without (active) form
=> fix: allow defining action without active form

packages/client/src/App.tsx, packages/client/src/config.ts, packages/client/src/v2-events/.eslintrc.js, packages/client/src/v2-events/routes/routes.ts
Adds a mechanism for the client to decide if they want Events v2 to be default or not regardless of environment variables in country config.
`http://localhost:3000/?V2_EVENTS=true`
Will set up a flag in local storage
that from that point forwards will dictate which view is render as default
=> Events v2: client-side feature flag for showing Events v2 as the default view

packages/gateway/src/features/user/usersAPI.ts, packages/gateway/src/graphql/data-source.ts
RESTDataSource throws errors of type GraphQLError so checking for custom error instances won't work, that's why we need to match against GraphQLError & check for 'UNAUTHENTICATED' code explicitly.
=> fix(ocrvs-8437): explicitly check for code

packages/client/src/forms/certificate/fieldDefinitions/collectorSection.ts, packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.test.tsx, packages/client/src/views/PrintCertificate/collectorForm/CollectorForm.tsx
=> fix(ocrvs-8561): only show field level errors in print forms

packages/client/src/forms/register/mappings/event-specific-fields/birth/query/registration-mappings.ts, packages/client/src/views/IssueCertificate/IssueCollectorForm/IssueFormForOthers.tsx
When transforming the gql payload to draft, only pick the certificateTemplateId and not the collector details from the print flow.
=> fix(ocrvs-8566): only store certificateTemplateId

packages/client/package.json
Chromatic has their own CI runners that we can use now
=> chore: test only changed files on chromatic. Stop failing on changes

packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistory.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/EventHistory/EventHistoryModal.tsx
Fix event history modal title to display proper action name, instead of 'technical' action name
Before:
After:
=> fix event history modal title

packages/client/src/v2-events/features/events/actions/declare/Declare.stories.tsx, packages/client/src/v2-events/layouts/form/FormHeader.tsx
- Form header menu is only shown if it has items
- Declare story test checks that event menu is shown for undeclared form
Before:
After:
=> Hide event action header menu if it doesnt have any actions (e.g. on register form)

packages/client/src/v2-events/features/events/actions/declare/Review.stories.tsx, packages/client/src/v2-events/features/events/actions/declare/Review.tsx, packages/client/src/v2-events/features/events/components/Review.tsx, packages/components/src/ResponsiveModal/ResponsiveModal.tsx
Configure different confirm modal messages for each declare case.
=> feat: add separate translations on confirm modal for different scopes

packages/client/package.json, packages/client/src/App.tsx, yarn.lock
react-router v7_startTransition was introduced in this PR: https://github.com/opencrvs/opencrvs-core/pull/8703
However it changed the routing on some actions, and caused farajaland e2e tests to fail and possibly to some functionality to change.
In this PR we firstly update the react-router-dom package to 6.28.1, which supports warning suppression by setting the value to false, and we set the `v7_startTransition ` value to false.
=> Disable react-router v7_startTransition, to fix problems with routing

packages/webhooks/src/environment.ts
Fixes webhook failing to start because of missing `QA_ENV` variable
=> fix: set default value for QA_ENV

packages/client/src/v2-events/components/forms/inputs/FileInput/fixtures.ts, packages/client/src/v2-events/features/events/actions/declare/Review.stories.tsx, packages/client/src/v2-events/features/events/fixtures.ts, packages/client/src/v2-events/features/events/useEvents/procedures/create.ts, packages/client/src/v2-events/features/events/useEvents/useEvents.test.tsx, packages/commons/src/conditionals/conditionals.test.ts, packages/commons/src/events/EventDocument.ts, packages/commons/src/events/EventMetadata.ts, packages/commons/src/events/state/index.test.ts, packages/commons/src/events/state/index.ts, packages/events/src/router/event/event.create.test.ts, packages/events/src/service/deduplication/deduplication.test.ts, packages/events/src/service/events/events.ts, packages/events/src/service/indexing/indexing.ts
* Generate a `trackingId` as part of the event create-action
* Index the tracking id as a `keyword` to elasticsearch
* Add test for checking for generated tracking ID
This PR does not contain displaying of the tracking ID on the summary page, since its not in the scope of the issue.
=> Tracking ID saved for events

packages/config/src/handlers/dashboardQueries/defaultQueries.ts, packages/migration/src/migrations/hearth/20250303113723-create-id-field-for-corrections.ts
The `_id` field was being used for deduping the corrections which was behaving inconsistently. So it had to be switched to another field, in this case the newly created `id`, which we are sure would be unique across both the `Task` & `Task_histories` collections.
countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/461
=> fix(ocrvs-8505): create a new id field for corrections

packages/client/src/v2-events/features/events/registered-fields/DateField.tsx, packages/components/src/DateField/DateField.tsx
Add leading zeroes to month and date field if missing. Also fix bug on V1 and V2 input fields, see comment below.
https://github.com/user-attachments/assets/eb5ece70-7795-4048-b70c-c411f42eba17
=> fix bug in old datefield, add leading zeros to new date field mm and dd

packages/config/src/config/hearthClient.ts, packages/config/src/handlers/locations/locationTreeSolver.test.ts, packages/config/src/handlers/locations/locationTreeSolver.ts, packages/config/src/server.ts, packages/metrics/src/config/hearthClient.ts, packages/metrics/src/features/certifications/service.ts, packages/metrics/src/features/corrections/service.ts, packages/metrics/src/features/locationStatistics/service.ts, packages/metrics/src/features/metrics/metricsGenerator.ts, packages/metrics/src/features/payments/service.ts, packages/metrics/src/features/performance/viewRefresher.ts, packages/metrics/src/features/registration/handler.test.ts, packages/metrics/src/server.ts, packages/metrics/src/utils/batchHelpers.ts, packages/search/src/config/hearthClient.ts, packages/search/src/features/records/service.ts, packages/search/src/server.ts
- Mongo client was declared outside the scope of the calling function so after the called closed the connection, it could not be reopened. 
-  Solved by moving instantiation inside the function.
- Mongo has a BSON limit of 16mb so requests were failing. 
- Projected only `id`, `type` and `name` to cut down on bundle size.
- Influx DB has a hard limit on header size, so with 20k location ids joined in the query, this was exceeded. 
- Solved by querying in batches of 1000
-  A reduce in the locationStatistics was causing a timeout because the spread operator was creating a new object every iteration, with 100k iterations.
-  Changed to array index assignment.
=> fix(v1.6.3) Fix mongo client connection errors and other performance enhancements

packages/client/src/src-sw.ts
Added an explicit registerRoute call for the certificates endpoint to stop them from getting registered with the MINIO route.
=> fix: use network first policy for certificates

packages/config/src/handlers/locations/children.ts, packages/config/src/handlers/locations/locationTreeSolver.ts, packages/metrics/src/configApi.ts, packages/metrics/src/features/certifications/service.ts, packages/metrics/src/features/corrections/service.ts, packages/metrics/src/features/declarationsStarted/service.ts, packages/metrics/src/features/getTimeLogged/utils.ts, packages/metrics/src/features/metrics/metricsGenerator.ts, packages/metrics/src/features/payments/service.ts
Currently the performance view checks all child locations for registration stats.
But only offices can have registrations attached to them.
So filter locations for metric by type `CRVS_OFFICE` to improve query performance. 
Fixes: https://github.com/opencrvs/opencrvs-core/issues/8575
=> fix: Filter metrics locations by office as other types cant have stats

CHANGELOG.md, packages/client/src/views/Organisation/AdministrativeLevels.tsx
Linked to this Issue: #8782
The Locations hierarchy in the Organization menu is limited to: 
Country -> ADMIN_STRUCTURE -> CRVS_OFFICE
This limits our scope of making locations inactive using the FHIR Location API, to the following types ADMIN_STRUCTURE and CRVS_OFFICE. HEALTH_FACILITY was ignored in this investigation, as it does not appear in the Organization menu.
Initial thought was to add a query parameter `status=active ` to the `loadLocations` and `loadFacilities` calls in [referenceApi.ts](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/client/src/utils/referenceApi.ts#L279)
But the locations and facilities data from the above mentioned calls are used elsewhere than the Organization menu as well, which breaks rendering of location data while viewing records where …
=> fix: filter out inactive locations in the Organisations menu

CHANGELOG.md, packages/client/src/views/PrintCertificate/PDFUtils.ts
Linked to this Issue: #8885
Fix rendering of Custom Date fields, by explicitly handling plain dates in certificate date handler
=> fix: explicitly handle plain dates in certificate date handler

CHANGELOG.md, packages/config/src/handlers/locations/utils.ts
We were providing an absolute path instead of a relative one that we needed to pass
https://github.com/opencrvs/opencrvs-core/issues/8606
=> Fix typo in getLocationsByIdentifier() hearth url

.github/workflows/check-missing-translation.yml
- If a matching countryconfig PR is found while checking for missing translations, we sync the countryconfig PR with latest `develop` so that we get changes from both the newest develop and the branch.
- If merge conflicts appear in `opencrvs-countryconfig/src/translations/client.csv`, we abort the merge.
- Run workflow file through prettier.
This was tested with countryconfig branch:
https://github.com/opencrvs/opencrvs-countryconfig/tree/check-missing-translation-use-branch-synced-with-develop
Discussion on slack: https://opencrvsworkspace.slack.com/archives/C07NQAULENB/p1742893406570809?
thread_ts=1742892993.373889&cid=C07NQAULENB
=> translation check workflow: matching countryconfig branch is now synced with develop

.github/workflows/deploy-to-feature-environment.yml
Manually triggering the e2e pipeline was failing because the gh cli needs the `GH_TOKEN` environment variable
=> fix: pass GH_TOKEN to authorize gh cli

packages/commons/src/events/state/index.test.ts, packages/commons/src/events/state/index.ts, packages/components/src/ImageUploader/ImageUploader.tsx
This fixes bug: https://github.com/opencrvs/opencrvs-core/issues/9065
There was an issue `deepDropNulls()` where it turned arrays into objects
=> fix bug with deepDropNulls(), where it turned arrays into objects

packages/dashboards/run.sh
This PR is followup to  https://github.com/opencrvs/opencrvs-core/pull/9120
```
Warning: OPENCRVS_METABASE_DB_USER, OPENCRVS_METABASE_DB_PASS and 
OPENCRVS_METABASE_DB_AUTH_DB environment variables are not defined
Using H2 (Metabase) connection without authentication
Initializing Metabase database
...
```
=> fix: metabase startup on kubernetes localhost env

packages/client/src/v2-events/features/events/registered-fields/Number.tsx
https://github.com/opencrvs/opencrvs-core/issues/8893
If number input has a `min` value of 0 or larger, dont allow entering minus sign to input. This is similar to how it works in V1 currently.
=> in number inputs, dont allow minus sign if min is 0 or larger

packages/documents/src/minio/constants.ts
While testing on local kubernetes setup PWA was trying to communicate with minio on https URL:
=> fix: Allow to define http protocol for minio

packages/commons/src/conditionals/conditionals.test.ts, packages/commons/src/conditionals/conditionals.ts
Fix bug with isBefore and isAfter validations when referring to other fields.
Previously the validation failed if the reference field was undefined. We want it to pass.
E.g.:
Validator: `field('mother.dob').isBefore().date(field('child.dob'))` should pass even if child.dob is undefined.
=> field reference validation should pass if reference field is undefined

packages/client/src/v2-events/features/events/components/Review.tsx
https://github.com/opencrvs/opencrvs-core/issues/9157
Don't hide `<Output/>` values on the review page unless they are undefined/null. We want to show empty strings.
Before:
After:
=> Don't hide outputs from review page unless they are undefined.

packages/client/src/v2-events/features/events/components/Pages.tsx
https://github.com/opencrvs/opencrvs-core/issues/9144
This caused a bug, where:
1. if there are hidden pages on the form
2. user presses browser's 'back' button on review page
3. `pageIdx` would be calculated from all pages, not just visible pages, i.e. it would be too large and would not find a page
4. frontend crashes with confusing error
=> Calculate pageIdx from visiblePages, not all pages

.github/PULL_REQUEST_TEMPLATE.md
No need to have the PR template in comments by default
=> remove comment tags from pr template

packages/commons/src/fhir/transformers/utils.ts
Add fix for updating informant type in birth declaration from any to mother, father.
Fix already exists in release-v1.7.0 but the fix in there is spread over several commits affecting several files. Since 1.6.3 is not going to be merged into develop, applying the fix without cherry picking
=> fix updates to informant type from any to mother, father

packages/client/src/user/userReducer.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.tsx, packages/client/src/views/SysAdmin/Team/user/userCreation/UserReviewForm.tsx, packages/gateway/src/features/user/root-resolvers.test.ts, packages/gateway/src/features/user/root-resolvers.ts, packages/gateway/src/features/user/utils/index.ts, packages/gateway/src/location.ts, packages/workflow/src/utils/location.ts
#9188 
Allow users to create/update users only in their own jurisdiction.
=> fix: ensure user create/update is allowed only in jurisdiction

packages/client/src/components/form/FormFieldGenerator.tsx, packages/client/src/utils/locationUtils.ts
Fixes advanced search sluggishness mentioned in #8575
We had tried using lodash memoize to cache one layer of the expensive operation but another expensive object creation was missed. I tried lodash memoize &  `React.useMemo` side by side and profiling showed that we are getting far better performance with the later.
=> perf: use useMemo to cache expensive function call

packages/events/src/router/event/__snapshots__/event.delete.test.ts.snap, packages/events/src/router/event/event.delete.test.ts, packages/events/src/service/events/events.ts
This fixes both:
https://github.com/opencrvs/opencrvs-core/issues/9213
https://github.com/opencrvs/opencrvs-core/issues/9206
E2e tests: https://github.com/opencrvs/opencrvs-farajaland/pull/1336
Fix logic for disallowing event deletion. Previously e.g. READ actions prevented event deletion, which we dont want.
=> Fix logic for disallowing event deletion

packages/client/src/v2-events/custom-api/index.ts, packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenu.tsx, packages/client/src/v2-events/utils.ts, packages/commons/src/events/ActionDocument.ts, packages/commons/src/events/ActionInput.ts, packages/commons/src/events/ActionType.ts, packages/commons/src/events/test.utils.ts, packages/commons/src/events/utils.test.ts, packages/commons/src/events/utils.ts, packages/events/src/router/event/event.actions.archive.test.ts, packages/events/src/router/event/event.actions.correction.test.ts, packages/events/src/router/event/event.actions.declare.test.ts, packages/events/src/router/event/event.actions.printCertificate.test.ts, packages/events/src/router/event/event.actions.reject.test.ts, packages/events/src/router/event/event.actions.test.ts, packages/events/src/router/event/event.actions.validate.test.ts, packages/events/src/router/event/event.delete.test.ts, packages/events/src/service/events/events.ts
Link to the GitHub issue https://github.com/opencrvs/opencrvs-core/issues/9102
- Adds `Unassign` action with every writeActions
- Exception: Don't add Unassign action when it's an intermediate action. (declare for validateOnDeclare)
=> Automatically unassign user when submitting an action

packages/client/src/v2-events/features/events/registered-fields/Data.stories.tsx, packages/client/src/v2-events/features/events/registered-fields/Data.tsx, packages/commons/src/events/FieldConfig.ts
Link to the GitHub issue: https://github.com/opencrvs/opencrvs-core/issues/9195
country pr: https://github.com/opencrvs/opencrvs-countryconfig/pull/640
Data field config value now supports translation config along with string value.
=> refactor data entry and field config

packages/client/src/v2-events/components/forms/File.interaction.stories.tsx, packages/client/src/v2-events/components/forms/FormFieldGenerator/GeneratedInputField.tsx, packages/client/src/v2-events/components/forms/inputs/FileInput/File.stories.tsx, packages/client/src/v2-events/components/forms/inputs/FileInput/SimpleDocumentUploader.tsx, packages/client/src/v2-events/features/events/components/DocumentViewer.tsx, packages/commons/src/events/FieldConfig.ts
Github issue: https://github.com/opencrvs/opencrvs-core/issues/9211
Countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/651
* File input selector now shows upload button even if file is already selected (as in V1)
* File input selector now shows configured file name or label, instead of actual file name (as in V1)
* File select on review page now shows configured file name along with label (as in V1)
=> File selector fixes

CHANGELOG.md, packages/commons/src/fhir/practitioner.ts, packages/gateway/src/features/registration/recordHistory.test.ts
Records generated for demo purposes include history entries dated before even a user was created in the system. Therefore, those history entries are unable to be matched against the role of the user in that particular time period. We are now using the first role entry available for that user in those cases.
P.S. Ignore the broken profile images please. I only restored mongo & elasticsearch locally so the minio documents weren't available in the system.
=> fix: use closest role entry when none available

packages/client/src/v2-events/components/forms/FormFieldGenerator/FormSectionComponent.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/EventSummary.tsx, packages/client/src/v2-events/hooks/useSimpleFieldStringifier.ts, packages/client/src/v2-events/messages/utils.tsx, packages/commons/src/conditionals/validate.ts, packages/commons/src/events/SummaryConfig.ts, packages/commons/src/events/utils.ts
Issue: https://github.com/opencrvs/opencrvs-core/issues/9044#issuecomment-2808408860
Countryconfig PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/646
Support field id references on summary page. They will use label and output as configured in the event configuration.
=> Support referencing fields in event summary fields

packages/client/src/v2-events/components/forms/validation.ts, packages/client/src/v2-events/features/events/components/Review.tsx, packages/commons/src/conditionals/validate.ts, packages/events/src/router/middleware/validate/index.ts, packages/events/src/router/middleware/validate/utils.ts
Fix backend field validations not working correctly in cases where multiple fields with the same id were configured in the form, with some of them being conditionally visible and some of them hidden.
Now it allows payload to include data for any field id which has at least one visible instance.
Also do some minor refactoring.
=> fix backend validation for duplicate field ids

packages/events/src/router/middleware/validate/__snapshots__/validate.test.ts.snap, packages/events/src/router/middleware/validate/index.ts, packages/events/src/router/middleware/validate/utils.ts, packages/events/src/router/middleware/validate/validate.test.ts
* Move and rename function `getFormFieldErrors()` -> `getFieldErrors()`
* Write simple unit tests for function
=> move and rename function, add unit tests

CHANGELOG.md, packages/search/src/features/records/service.ts
Reduce record aggregation query memory usage by not grouping all records into a single array
Resolves: https://github.com/opencrvs/opencrvs-core/issues/9116
=> Fix migration issue discovered when restoring an OpenCRVS instace with a large number of records

packages/client/src/v2-events/features/events/actions/register/Review.tsx, packages/client/src/v2-events/features/events/actions/validate/Review.tsx, packages/client/src/v2-events/features/events/components/Action/DeclarationAction.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/ActionMenuStories/ActionMenu.common.tsx, packages/commons/src/events/state/index.ts
Resolves https://github.com/opencrvs/opencrvs-core/issues/9275
E2e test: https://github.com/opencrvs/opencrvs-farajaland/pull/1359
Use previous action annotation data as default values for current action annotation. This means that on birth declaration, the signature and comment will be persisted.
=> Use previous action annotation data as default for current action annotation

CHANGELOG.md, packages/client/src/views/SearchResult/SearchResult.tsx, packages/search/src/features/search/search.test.ts, packages/search/src/features/search/service.test.ts, packages/search/src/features/search/service.ts, packages/search/src/features/search/utils.test.ts, packages/search/src/features/search/utils.ts
Link to the GitHub issue #9272 
Context and description of fix:
The existing [ES query](https://github.com/opencrvs/opencrvs-core/blob/develop/packages/search/src/features/search/utils.ts#L39C3-L68C4) for quick name searches was way to broad.
This PR modifies the ES query for quick name searches.
In addition the results for quick name searches were sorted by `dateOfDeclaration`, which seems a bit odd as we would want to see ES hits with the highest score on top instead. This PR also removes the default sorting criteria of Quick searches if a `sortColumn` is not provided
[Screen Recording](https://www.loom.com/share/7041e50a5c94471db364a4000202bbcd?sid=cb459d3f-c4aa-4c36-b6c6-8400c8cfe30c)
=> Improve relevance of quick searches using name

packages/client/src/v2-events/features/workqueues/Workqueue.tsx, packages/commons/src/events/EventConfig.ts
Resolves https://github.com/opencrvs/opencrvs-core/issues/9412
Use configured fallback title if actual title resolves to empty string
=> Use configured fallback title if actual title resolves to empty string

.github/workflows/lint-and-test.yml
This change prevents our temporary Git access tokens for momentarily leaking into the cached artefact. There's a small period when the token is valid and could be abused by a malicious actor
=> Do not upload .git with the cache artifact

CHANGELOG.md, docker-compose.deps.yml
Backgroung for this PR is documented at https://redis.io/blog/agplv3/
Slack link: https://opencrvsworkspace.slack.com/archives/C07M2FETFFB/p1746432546347569
Related PRs:
- https://github.com/opencrvs/e2e/pull/54
- https://github.com/opencrvs/opencrvs-farajaland/pull/1377
=> fix: Switch from valkey to redis

CHANGELOG.md, packages/migration/src/migrations/hearth/20250508091242-remove-duplicate-practitioner-role.ts, packages/workflow/src/records/state-transitions.ts
fixes: https://github.com/opencrvs/opencrvs-core/pull/9491
On view and download, a bundle with the Task and PractitionerRole was sent to Hearth.
This caused the PractitionerRole to be updated and created an additional PractitionerRole_history entry every time. 10 views meant 10 new PractitionerRole_history entries.
Semantically, PractitionerRole should only be updated if the role changes.
However, the comments in the code imply that the role is required for the declaration history view.
On inspection of the history code in the type resolver, to get the role of the user at the time of the task, it just calls a function to get the role history of the user and finds the correct role at the timestamp of the task:
https://github.com/opencrvs/opencrvs-core/blob/7a382177187187a1121cbe423d11ec3682 …
=> fix: Remove PractitionerRole from Hearth bundle on every view and download

packages/client/src/v2-events/features/drafts/useDrafts.ts, packages/client/src/v2-events/features/events/actions/declare/Pages.interaction.stories.tsx, packages/client/src/v2-events/features/events/actions/declare/Review.interaction.stories.tsx, packages/client/src/v2-events/features/events/components/Action/AnnotationAction.tsx, packages/client/src/v2-events/features/events/components/Action/DeclarationAction.tsx, packages/client/src/v2-events/features/events/useActionAnnotation.ts, packages/client/src/v2-events/features/events/useEventFormData.ts
Resolves: https://github.com/opencrvs/opencrvs-core/issues/9288
* Use form and annotation values from zustand states (`useEventFormData` and `useActionAnnotation`) when initialising action forms. This means that state will be sustained through, for example, the screen lock / pin code mechanism.
* Refactor `useEventFormData` and `useActionAnnotation`, remove unneeded initial state setting functions
* Fix some test cases which used event form data from state, even though they shouldn't
=> Use zustand form and annotation data when initialising action forms

CHANGELOG.md, packages/client/src/user/userReducer.ts, packages/client/src/views/SysAdmin/Team/user/userCreation/CreateNewUser.test.tsx, packages/commons/src/authentication.ts, packages/commons/src/scopes.ts, packages/gateway/src/features/user/root-resolvers.test.ts, packages/gateway/src/features/user/root-resolvers.ts
During user creation/update, the allowed roles are determined using the roles defined in user.create/user.update scope.
=> feat(ocrvs-9523): user.create/user.update scopes can define roles

CHANGELOG.md, packages/config/src/handlers/forms/validation.ts
Countries like Somalia have a form field for Child's NID that means that not just the work completed for https://github.com/opencrvs/opencrvs-core/pull/7469 is needed, a form filed is required.
Countries like Sri Lanka want to put the fathers details page first but cannot as they cant have a radio button that says mother's address is the same as the fathers.
https://github.com/opencrvs/opencrvs-core/issues/9582
=> Chore: Add "child nid" & "mother address same as father's" supported form field config validations

packages/client/src/views/CorrectionForm/utils.ts, packages/client/src/views/RegisterForm/review/ReviewSection.tsx
A `custom section` containing a `custom address field` was `hidden` from the field agent.
After submitting a declaration, the registration agent will review the record and encode the details needed for the custom section. When a custom address field was updated and the registration agent goes back to the review page, it throws `Uncaught TypeError: Cannot read properties of undefined (reading 'countryPrimarySectionName')`
Link this pull request to the GitHub issue: https://github.com/opencrvs/opencrvs-core/issues/9477
=> Fix "Uncaught TypeError: Cannot read properties of undefined" when updating custom field address of a hidden section

packages/client/src/views/OfficeHome/queries.ts
The default sort column got removed in #9343 but as the workqueue results are expected to come as sorted by the previous default parameter, we need to explicitly set it now.
=> fix: explicitly set sort column for workqueue queries

CHANGELOG.md, packages/client/src/forms/register/mappings/query/registration-mappings.ts, packages/client/src/forms/user/fieldDefinitions/createUser.ts, packages/client/src/i18n/messages/views/userForm.ts, packages/client/src/profile/queries.ts, packages/client/src/user/queries.ts, packages/client/src/utils/gateway.ts, packages/client/src/views/DataProvider/birth/queries.ts, packages/client/src/views/DataProvider/death/queries.ts, packages/gateway/src/features/user/root-resolvers.ts, packages/gateway/src/features/user/schema.graphql, packages/gateway/src/features/user/type-resolvers.ts, packages/gateway/src/graphql/schema.d.ts, packages/gateway/src/graphql/schema.graphql, packages/user-mgnt/src/features/updateUser/handler.ts, packages/user-mgnt/src/model/user.ts, packages/workflow/src/records/user.ts
Added a custom `fullHonorificName` on the user management page that can be used in the certificate
Pull request to the GitHub issue: https://github.com/opencrvs/opencrvs-core/issues/8706
Countryconfig: https://github.com/opencrvs/opencrvs-countryconfig/pull/750
=> Add custom fullHonorificName on the user management page

CHANGELOG.md, packages/client/src/forms/register/mappings/query/registration-mappings.test.ts, packages/client/src/forms/register/mappings/query/registration-mappings.ts
It's possible to enter local numbers for default users when setting up openCRVS.
Previously this code was throwing an exception for local numbers when editing the user.
This refactor allows local numbers to be parsed at local.
Fixes: https://github.com/opencrvs/opencrvs-core/issues/9634
=> fix: Return local number if number is in local format already

CHANGELOG.md, packages/gateway/src/features/registration/type-resolvers.ts
The helper function ensures that the first role is returned as the fallback if none found at the given point in time.
=> fix: use helper to find the role

packages/events/src/index.ts
Example error log: `@opencrvs/events: [13:17:43.257] WARN: Error for request: 'POST /events'. Error: 'FORBIDDEN'`
=> dont log stack trace

.github/workflows/build-images-from-branch.yml, .github/workflows/deploy-to-feature-environment.yml
Add support to core PR e2e deployment for using the PR base/target farajaland branch if found. This means that the e2e deployments on PRs will resolve the opencrvs-farajaland branch thus:
1. Use branch with same name as PR branch if found
2. Use branch with same name as PR base/target branch if found
3. Fallback to develop branch
=> PR e2e deployment uses base branch as farajaland branch

development-environment/setup-countryconfig.sh
I’m noticing that this [PR](https://github.com/opencrvs/opencrvs-core/pull/8004
) has broken the [bash setup.sh](https://documentation.opencrvs.org/setup/3.-installation/3.1-set-up-a-development-environment/3.1.2-install-opencrvs-locally) script for setting up a local development environment: 
The IPP group are unable to run the script because this branch should be **master**, not develop
=> Changing the setup script to use develop instead of master breaks it

packages/client/src/views/PrintRecord/Body.tsx
Don't show hidden fields in the declaration print preview similar to the review section
=> fix: don't show hidden fields in print view

packages/client/.storybook/preview-head.html, packages/client/src/setupTests.ts, packages/client/src/v2-events/cache.ts, packages/client/src/v2-events/features/files/cache.ts
- Use bucket variable from window.config (in order to get e2e working)
- Add try catches
=> chore: use MINIO_BUCKET through window.config

packages/commons/src/conditionals/validate.ts, packages/commons/src/events/ActionType.ts, packages/events/src/router/event/__snapshots__/event.actions.notify.test.ts.snap, packages/events/src/router/event/actions/index.ts, packages/events/src/router/event/event.actions.notify.test.ts, packages/events/src/router/middleware/validate/index.ts
E2e tests: https://github.com/opencrvs/opencrvs-farajaland/pull/1462
* Add payload validation to Notify API
* Minor improvement to `validateAction()`
* Add tests
=> Add validation to Notify API

packages/client/.storybook/main.ts, packages/client/package.json, yarn.lock
Take into use storybook [source-link addon](https://storybook.js.org/addons/storybook-addon-source-link) that adds a button to the Storybook toolbar that opens the file containing the Story in an IDE like VSCode.
=> Enable links between Storybook UI to the code file

packages/client/src/views/SysAdmin/Performance/PerformanceHome.tsx, packages/config/src/handlers/locations/handler.ts, packages/config/src/handlers/locations/utils.ts, packages/data-seeder/src/locations.ts, packages/metrics/src/features/locationStatistics/service.ts, packages/metrics/src/features/metrics/utils.ts
[Issue #8092](https://github.com/opencrvs/opencrvs-core/issues/8092)
=> remove completeness component for lower locations

packages/events/src/context.ts, packages/events/src/server.test.ts
When Authorization header is missing, throw HTTP 401 Unauthorized instead of HTTP 500
=> Handle requests with missing auth header gracefully

packages/events/DATABASE.md
Improves Postgres documentation with the roles used. Also adds information about how the database is initalized locally.
=> docs(postgres): add info about database roles and initialization

packages/events/DATABASE.md, packages/events/package.json, packages/events/src/tests/postgres-migrations.sql, packages/events/src/tests/postgres.ts, packages/events/src/tests/setup.ts
Updates the tests to use a database dump. This is useful when new migrations are created and the test database needs to be updated.
=> use database dump in tests

packages/client/src/i18n/messages/views/correction.ts, packages/client/src/v2-events/components/forms/FormFieldGenerator/FormFieldGenerator.interaction.stories.tsx, packages/client/src/v2-events/components/forms/FormFieldGenerator/FormFieldGenerator.tsx, packages/client/src/v2-events/components/forms/FormFieldGenerator/FormSectionComponent.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Pages.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Review.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/CorrectionDetails.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx, packages/client/src/v2-events/features/events/components/Pages.tsx, packages/client/src/v2-events/features/events/components/Review.tsx, packages/commons/src/conditionals/validate.ts, packages/commons/src/events/FieldConfig.ts, packages/commons/src/events/test.utils.ts, packages/commons/src/fixtures/forms.ts, packages/events/src/router/event/__snapshots__/event.actions.correction.test.ts.snap, packages/events/src/router/event/event.actions.correction.test.ts, packages/events/src/router/middleware/validate/index.ts
Resolves https://github.com/opencrvs/opencrvs-core/issues/9735
CC PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/844
e2e tests: https://github.com/opencrvs/opencrvs-farajaland/pull/1492
- Add support for `isCorrectable` for form fields, this is true by default
- If in correction flow, disable fields with `isCorrectable: false`
- If in correction flow, hide/skip pages if all its fields either have `isCorrectable: false` or are non-interactive fields (such as paragraphs, dividers, etc)
- If in correction flow, hide change buttons on review page for fields with `isCorrectable: false`
- Fix bug on correction review page, where the continue button was enabled even though no changes were present
- Add new title translation for correction request confirmation modal
- Minor …
=> Allow excluding certain declaration fields from configuration, fix bug on correction review page

packages/commons/src/events/CompositeFieldValue.ts
When creating a declaration and only providing a first name or last name (not both), the draft is not saved correctly. Instead of remaining in "My drafts", the record is prematurely moved to the "Assigned to you" workqueue with the title `"No name provided"`.
1. Login as FA, RA, or Registrar.
2. Start a new declaration and fill in all required fields **except full name**.
3. Provide only a first name or a surname in the Name field.
4. Save the draft.
5. Observe that:
- The draft briefly appears in “My drafts”
- Then title changes to `No name provided`
- Record moves to “Assigned to you” workqueue
The declaration should remain in “My drafts” even when only a partial name (either first or last name) is provided.
---
Updated the `NameFieldUpdateValue` schema to allow `nullish` values for …
=> support creating draft even with incomplete name field

CHANGELOG.md, packages/client/src/forms/register/mappings/query/field-mappings.ts
With this change, booleanTransformer can be used as a certificate template transformer.  This supports a handlebar detailsExist in a cert
Resolves: #9631
=> Allow booleanTransformer to be used as a certificate handlebar transformer

packages/client/src/v2-events/features/events/Search/SearchResult.tsx, packages/client/src/v2-events/features/events/useEvents/outbox.ts, packages/client/src/v2-events/features/events/useEvents/procedures/create.ts, packages/client/src/v2-events/features/workqueues/EventOverview/EventOverview.tsx, packages/client/src/v2-events/layouts/EventOverview/index.tsx, packages/commons/src/events/state/index.ts
As `dateOfEvent` could be configured, it needs to be resolved separately in outbox. The reason being, first time declarations only have "CREATE" action in the `EventDocument` which doesn't include the latest `declaration` values. So `getCurrentEvent` state is unable to resolve `dateOfEvent`
includes a fix for #8449
=> fix: resolve dateOfEvent in outbox

packages/client/src/v2-events/features/drafts/useDrafts.ts, packages/client/src/v2-events/features/events/actions/register/Review.interaction.stories.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/useActionMenuItems.ts
I wasn't exactly sure what caused the documents of a draft to go missing. Previously in OpenCRVS however, if you nuked your local storage, you automatically lost everything including the draft itself.
I changed the logic now so that if there's a draft the server knows about, owned by you, then those event documents are downloaded to your browser automatically. 
This is based on the following assumptions:
- It's not possible someone else would have taken over the event document. Someone adding an action to a record should have cleared all draft from the record. If that was the case you would never receive the draft to your browser
=> [OCRVS-9254] Download event to browser automatically if user has a remote draft open for said event

packages/client/.storybook/preview.tsx, packages/client/src/profile/profileReducer.ts, packages/client/src/utils/authUtils.ts, packages/client/src/utils/userUtils.ts, packages/client/src/v2-events/layouts/sidebar/Sidebar.tsx, packages/client/src/v2-events/routes/config.tsx, packages/client/src/v2-events/trpc.tsx
The problem was, we didn't clear React Query when user logged out. 
I also discovered another flakiness issue with the original OpenCRVS logout – it seems data clearing was ran in parallel with the browser redirects which might have caused tokens not invalidated properly and in some cases local data not clearing out correctly.
=> [OCRVS-9946] Clear user's local events data when they logout

CHANGELOG.md, packages/migration/src/migrations/hearth/20250716162802-update-practitioner-role-history-collection-for-new-userroles.ts, packages/migration/src/utils/role-helper.ts
Addresses: https://github.com/opencrvs/opencrvs-core/issues/9989
The migrations for roles in 1.7 did not include the PractionerRole and history collections so when the task history is viewed, it still references the previous system role rather than the new role based on the role alias.
The PractionerRole has two codes,:
- http://opencrvs.org/specs/roles - which contained the System role
- http://opencrvs.org/specs/types - which contained the alias in a json object
So to generate the correct role name, the english label in the `types` code can be used, using the same logic used to create the new role ids (`toUpperCase().replace(' ',  '_')`).
An existing migration removed the `types` code on the PractitionerRole so that had to be modified and another migration created to do the same on …
=> Fix migration of PractitionerRole and history to match new role names

packages/client/src/v2-events/features/events/actions/correct/utils.ts
Bug was caused by conditionally hidden, but unchanged fields becoming visible. We dont want to show them on the summary.
=> Fix bug with displaying unchanged fields in correction summary

CHANGELOG.md, packages/migration/src/migrations/user-mgnt/20240628124653-remove-userroles.ts, packages/migration/src/utils/role-helper.ts
Fixes: https://github.com/opencrvs/opencrvs-core/issues/10049
During the automatic role upgrade, roles can be created with apostrophes. 
e.g.
v1.6 role: 
```
{
systemRole: "REGISTRATION_AGENT",
alias: "Registrar's Assistant"
}
```
The migration will create a new role of REGISTRAR'S_ASSISTANT.
This fixes the migrations to remove special characters.
Accompanying country-config PR: https://github.com/opencrvs/opencrvs-countryconfig/pull/893
=> Update migrations to remove special characters from role ids on generation

packages/commons/src/events/utils.ts
We were subtracting one less than the value, e.g. for `last7days` we were subtracting 6 from the current date. Now we are subtracting the same as the value.
=> fix: subtract same days as the value

packages/commons/src/conditionals/conditionals.test.ts, packages/commons/src/conditionals/conditionals.ts, packages/events/src/router/event/event.search.test.ts, packages/events/src/service/indexing/indexing.ts
- The custom normalizer used for email fields is equivalent to the built-in `lowercase` normalizer
- Remove `_` from the list of allowed characters in names
- Switching to the `classic` analyzer from the custom `human_name` analyzer as the `word_delimiter` filter was causing more issues than it solved. The classic tokenizer is a grammar based tokenizer that is good for English language documents. This tokenizer has heuristics for special treatment of acronyms, company names, email addresses, and internet host names.
This PR addresses both #10018 & #10041 
https://github.com/opencrvs/opencrvs-countryconfig/pull/911
N.B.: This fix requires a reset of environment.
=> fix: tweak email & name field analyzers in elasticsearch

packages/events/nodemon.json, packages/events/package.json, packages/events/src/index.ts, yarn.lock
Switching to `ts-node-dev` instead of `nodemon` as it inherently watches any referenced file, so workspace dependencies are watched by default. Plus it shares Typescript compilation process between restarts. This significantly increases speed of restarting compared to the competition.
=> perf: reduce events service restart churning

packages/client/src/v2-events/hooks/useWorkqueue.ts
This bug was caused by workqueue initialising a HTTP request even when the browser was offline.
I changed the fetching logic so it primarily tries to use 
A way to reproduce the bug was for instance
1. Start a new declaration and go offline
2.  `["event", "search"]` delete queries prefixed like this. These are the workqueue searches
3. Submit a declaration
4. App should now crash
=> [OCRVS-10125] Only fetch workqueues when online

packages/client/src/v2-events/features/events/actions/declare/Review.interaction.stories.tsx, packages/commons/src/events/CompositeFieldValue.ts
An empty field inside `NAME` never triggered an error because:
1. Zod type allowed for empty strings
2. The component itself can emit empty string values i.e. `{firstname: 'Riku', surname: ''}`
3. `validEnglishName` validation doesn't require any length for the string
I opted for fixing the first one because configuring a name field with `required: true` but without supplying a custom validator should be a valid configuration. This rules out fixing number 3.  Another option would have been making the NAME component so it never emits empty strings but it would imply the caller of the component cannot know if a user just emptied out the input vs if it was never touched.
```
{
id: 'applicant.name',
type: FieldType.NAME,
required: true
}
```
=> [OCRVS-10005] Make name subfields require at least one character to be valid

packages/commons/package.json, packages/components/package.json
Running tsc with watch clears output by default unless the preserveWatchOutput flag is provided.
=> chore: prevent console from getting cleared

packages/client/src/v2-events/features/drafts/useDrafts.ts, packages/client/src/v2-events/features/events/EventSelection.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx, packages/client/src/v2-events/features/events/actions/declare/Pages.interaction.stories.tsx, packages/client/src/v2-events/features/events/actions/declare/Pages.tsx, packages/client/src/v2-events/features/events/actions/declare/Review.tsx, packages/client/src/v2-events/features/events/actions/register/Pages.tsx, packages/client/src/v2-events/features/events/actions/register/Review.tsx, packages/client/src/v2-events/features/events/actions/validate/Pages.tsx, packages/client/src/v2-events/features/events/actions/validate/Review.tsx, packages/client/src/v2-events/features/events/components/Action/AnnotationAction.tsx, packages/client/src/v2-events/features/events/components/Action/DeclarationAction.tsx, packages/client/src/v2-events/features/events/useEventFormData.ts, packages/client/src/v2-events/features/events/useEventFormNavigation.tsx, packages/client/src/v2-events/layouts/form/FormHeader.tsx, packages/client/src/v2-events/layouts/workqueues/index.tsx
Removes `unmount` based logic around when form state is cleared and replaces it with explicit function instead
=> [OCRVS-10151] Ensure form state is not cleared without explicit user action

packages/client/src/v2-events/features/events/Search/SearchResult.tsx, packages/client/src/v2-events/features/events/useEventFormNavigation.tsx, packages/client/src/v2-events/features/workqueues/EventOverview/components/useActionMenuItems.ts, packages/client/src/v2-events/layouts/EventOverview/index.tsx, packages/commons/src/events/state/index.ts
**Problem**: sometimes when creating a draft offline, then going back online you could see record details flickering for some time
This was mostly because the draft that was created had an older creation time than the stored actions that came back from the server (CREATED) thus nullifying the draft's details
=> [OCRVS-10122] Ensure latest draft state is always shown properly in workqueues

packages/client/src/v2-events/features/files/useFileUpload.ts, packages/documents/src/features/uploadDocument/handler.test.ts, packages/documents/src/features/uploadDocument/handler.ts
After changing the logic where files are deleted on backend, we want to introduce a way to find possible "orphan" files. (e.g. files that were uploaded but never referenced in action payloads).
- Add event id as part of file path when possible
- Add simple test cases for parsing
=> feat: add event id as part of file path when possible

packages/client/src/v2-events/features/events/registered-fields/Address.tsx, packages/client/src/v2-events/features/events/registered-fields/AdministrativeArea.tsx, packages/client/src/v2-events/features/events/registered-fields/Checkbox.tsx, packages/client/src/v2-events/features/events/registered-fields/LocationSearch.tsx, packages/client/src/v2-events/features/events/registered-fields/RadioGroup.tsx, packages/client/src/v2-events/features/events/registered-fields/Select.tsx, packages/client/src/v2-events/features/events/registered-fields/SelectCountry.tsx, packages/commons/src/events/FieldConfig.ts
We were pretty close with our previous solution of exporting the inferred types, but apparently we explicitly need to set type for Zod schema for that to take proper effect. With this change, we are getting:
- ~80% reduction in number of lines in the commons build
- ~60% reduction in commons build time
=> perf: give FieldConfig an explicit type

packages/components/src/AppBar/AppBar.tsx, packages/components/src/Frame/Frame.tsx
Fix broken `FrameHeader` in https://github.com/opencrvs/opencrvs-core/commit/9b57635baf1eb3eb8b5f085c77ace6898626087d
=> [HOTFIX] Fix broken FrameHeader

packages/client/src/v2-events/custom-api/index.ts, packages/client/src/v2-events/features/events/actions/correct/request/CleanedUpCorrectionPayload.stories.tsx, packages/client/src/v2-events/features/events/actions/correct/request/Summary/Summary.tsx, packages/client/src/v2-events/features/events/useEvents/procedures/actions/action.ts
Issue: https://github.com/opencrvs/opencrvs-core/issues/10253
🛠️ Fix: Correction Request Field Filtering
🔍 Problem
When we directly want to correct fields like `informant.name`,
`informant.age`, the actionUpdate payload looks like this:
{
"informant.name": { "firstname": "Jon", "surname": "Jane" },
"informant.age": "44",
"informant.dobUnknown": true
}
At one point, before the correction request procedure is called, we run
`omitHiddenPaginatedFields` validation which considers this actionType as
a standard declaration.
Since the visibility of these fields in this declaration depends on
`informant.relation`, and that field is not available here, all the fields
in this actionUpdate gets filtered, and the intended correction request is
not made. …
=> Clean and filter declaration updates before mutation

packages/client/src/v2-events/features/events/actions/correct/request/Summary/CorrectionDetails.tsx, packages/client/src/v2-events/features/events/components/Output.tsx, packages/client/src/v2-events/features/events/components/Review.tsx, packages/commons/src/conditionals/validate.ts, packages/commons/src/events/state/index.ts
This PR fixes an issue in the correction workflow where multiple fields share the **same label** but have **different field IDs**.  
In correction view, only one such field is visible at a time due to conditionals, causing previous values under other IDs to be missed during comparison.
---
- Fields like `child.birthLocation` and `child.address.privateHome` share the same label **"Location of birth"** but have different IDs.
- In correction view, only one is visible; previous form data may have values under a different field ID with the same label.
- This leads to missing changes or inaccurate display of previous values.
---
- Added `findPreviousValueWithSameLabel()` to find previous values across all fields sharing the same label on the current page.
- Updated the `Output` component to …
=> ✨ Handle previous value lookup for fields sharing the same label in correction view

packages/commons/src/events/FieldConfig.ts, packages/commons/src/fixtures/forms.ts
Country config pull request: https://github.com/opencrvs/opencrvs-countryconfig/pull/966
Adds a meta field `analytics` that filters all other fields away from the `declaration` except the ones marked as analytics fields.
=> allow filtering specific fields for analytics

packages/events/src/router/event/actions/declare.ts, packages/events/src/router/event/actions/index.ts
Typescript tries to use the `ActionProcedure` type for building the `AppRouter` one but due to how our build process works, the type is not available to be imported by default. It will instead need to be manually copied over from events/build to toolkit/build. So we opted to not expose the type altogether.
countryconfig: https://github.com/opencrvs/opencrvs-countryconfig/pull/982
=> fix: keep `ActionProcedure` as an internal type

packages/commons/src/events/test.utils.ts, packages/events/src/router/event/event.getDuplicates.test.ts, packages/events/src/router/event/index.ts, packages/events/src/router/middleware/authorization/index.ts, packages/events/src/service/deduplication/deduplication.ts, packages/events/src/service/events/events.ts, packages/events/src/storage/postgres/events/events.ts, packages/events/src/tests/generators.ts, packages/events/src/tests/utils.ts
As a part of duplicate check, we need to be able to access those events marked as duplicate for comparison.
- Create endpoint for getting duplicates
- Create helpers for fetching full event in one call
- Allow passing in configuration for generator in tests.
=> feat: create get duplicates endpoint

packages/client/src/v2-events/features/events/actions/dedup/DuplicateComparison.tsx, packages/client/src/v2-events/features/events/actions/dedup/Review.stories.tsx, packages/client/src/v2-events/features/events/components/Output.tsx, packages/components/src/ComparisonListView/ComparisonListView.tsx
Issue: https://github.com/opencrvs/opencrvs-core/issues/10400
This PR updates the duplicate comparison view to handle cases where multiple fields share the same label.  
It ensures that such fields are rendered in a single comparison row rather than duplicating rows.
Additionally, a new Storybook scenario is introduced to validate this behavior with `Contact Method` and `Contact` fields.
---
- **DuplicateComparison.tsx**
- Replaced `ValueOutput` with `Output` for richer rendering (supports `previousForm`, `formConfig`, etc.).
- Added deduplication step to collapse fields with the same label (`reduce` logic).
- **Review.stories.tsx**
- Created `overriddenEventConfig` with new `contactMethod` and conditional `contact` fields.
- Added `DuplicateWithSameLabels` story:
- Validates that …
=> Show fields with same label in same row in deduplication comparison

.github/workflows/build-images-from-branch.yml
Goal of this PR is to address issue like this one: https://github.com/opencrvs/opencrvs-core/actions/runs/17669000166
workflow was successfully build, but final image tag was `refs-tags-v1.9.0-beta.2` instead of `v1.9.0-beta.2`
Problem was is complicated logic and not taking into account edge case scenarios like tag can be supplied from workflow_dispatch (refs-tags-v1.9.0-beta.2) or workflow_call (v1.9.0-beta.2)
This PR refactors the workflow script to use built-in GitHub Actions variables for determining the branch name, instead of manually parsing and handling the branch from multiple possible sources like at https://github.com/opencrvs/opencrvs-countryconfig/blob/develop/.github/workflows/publish-to-dockerhub.yml#L92.
- Replaces manual branch detection and variable manipulations with: …
=> fix: Simplify Branch Name Detection in Workflow

packages/commons/src/events/DeduplicationConfig.ts, packages/commons/src/events/deduplication.ts, packages/commons/src/fixtures/v2-birth-event.ts, packages/events/src/router/event/event.actions.correction-2.test.ts, packages/events/src/service/deduplication/__snapshots__/deduplication.test.ts.snap, packages/events/src/service/deduplication/deduplication.test.ts, packages/events/src/service/deduplication/deduplication.ts
Introduce strict value match and `not` helper for deduplication checks.
https://github.com/opencrvs/opencrvs-countryconfig/pull/1011
=> feat: support for strict value and `not` helper

packages/client/src/components/interface/Navigation.test.tsx, packages/client/src/components/interface/Navigation.tsx
Resolves https://github.com/opencrvs/opencrvs-core/issues/10517
Agreed with Tameem that the rest of the code will be cleaned up as part of 1.10 v1 cleanup. So only remove the items from navbar for now.
After (desktop):
After (mobile):
=> Remove Performance and Vital statistics from navbar

packages/commons/src/conditionals/conditionals.test.ts, packages/commons/src/conditionals/conditionals.ts
https://github.com/opencrvs/opencrvs-core/issues/10393
This PR defines `isGreaterThan` and `isLessThan` conditionals to compare numbers.
- Added `defineComparison(fieldId, value, keyword)` utility:
- Handles both **field reference** (`{ $$field: '...' }`) and **numeric value** comparisons.
- Dynamically applies either `exclusiveMinimum` or `exclusiveMaximum` based on the given keyword.  
- `isGreaterThan` → uses `exclusiveMinimum` via `defineComparison`.  
- `isLessThan` → uses `exclusiveMaximum` via `defineComparison`.  
```ts
field('employee.salary').isGreaterThan(10000)
field('person.yearsMarried').isLessThan({ $$field: 'person.yearsSinceGraduation' })
```
=> Introduced isGreaterThan isLessThan conditionals

CHANGELOG.md, docker-compose.deps.yml
This PR aims to implement cherry-pick commit with switch to default Redis image, more details are at https://github.com/opencrvs/opencrvs-core/issues/10173
Changes were tested in develop branch of upcoming v1.9.0 release
- Deployment link: https://github.com/opencrvs/opencrvs-farajaland/actions/runs/18134101869/job/51608179933
- Environment is up and running: https://register.farajaland-dev.opencrvs.dev/
- Login is working as expected (only login functionality is effected by this change)
=> fix: Switch to official redis image (#10173)

packages/gateway/package.json
Since the command already has `yarn gen:types:watch` the first one is unnecessary and caused unnecessary file changes on development env
=> Fix issue with `packages/gateway/src/graphql/schema.d.ts` changing on development env

CHANGELOG.md, packages/auth/src/features/oauthToken/client-credentials.ts, packages/events/src/router/event/index.ts, packages/events/src/service/events/import.test.ts, packages/events/src/service/events/import.ts
Add bulk import endpoint to speed up migration.
Create an exception for the import/export client so that it uses the regular 7 day default expiry, rather than the 10 minute expiry used by other system clients.
Issue: https://github.com/opencrvs/opencrvs-core/issues/10589
=> Add bulk import endpoint

.github/workflows/build-images-from-branch.yml
We got multiple reports from countries about issues building ARM images on private github repositories.
This PR aims to disable ARM images build unless manually triggered.
> NOTE: For private repositories ARM runners are available only for paid plans
- https://github.com/orgs/community/discussions/148648
=> fix: Disable build arm images on tag
